Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-11, with the labels that each got.

#1637 Override default server kubeconfig url for aws actuator e2e
  sjb/config/test_cases/ci-kubernetes-aws-actuator.yml
  sjb/generated/ci-kubernetes-aws-actuator.xml
Labels: size/XS

#1636 Add missing test_pull_request_origin_web_console jobs for 3.9 and 3.11
  sjb/config/test_cases/test_pull_request_origin_web_console_311.yml
  sjb/config/test_cases/test_pull_request_origin_web_console_39.yml
Labels: size/XS

#1638 Generate console jobs
  sjb/generated/test_pull_request_origin_web_console_311.xml
  sjb/generated/test_pull_request_origin_web_console_39.xml
Labels: size/XXL

#1639 Remove crd e2e for actuator
  sjb/config/test_cases/pull-ci-openshift-cluster-api-provider-libvirt-crd-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-provider-libvirt-crd-e2e.xml
Labels: size/XL

#1640 Bump gimme go version in kubernetes node e2e tests
  sjb/config/test_cases/ci-kubernetes-conformance-node-e2e-containerized-rhel.yml
  sjb/config/test_cases/ci-kubernetes-conformance-node-e2e-rhel.yml
  sjb/generated/ci-kubernetes-conformance-node-e2e-containerized-rhel.xml
  sjb/generated/ci-kubernetes-conformance-node-e2e-rhel.xml
Labels: size/S

#1634 move jenkins plugins from openshift/origin:master to openshift/origin…
  sjb/config/test_cases/test_branch_jenkins_client_plugin.yml
  sjb/config/test_cases/test_branch_jenkins_openshift_login_plugin.yml
  sjb/config/test_cases/test_branch_jenkins_plugin.yml
  sjb/config/test_cases/test_branch_jenkins_sync_plugin.yml
  sjb/generated/test_branch_jenkins_client_plugin.xml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_branch_jenkins_plugin.xml
  sjb/generated/test_branch_jenkins_sync_plugin.xml
  sjb/generated/test_pull_request_jenkins_client_plugin.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_plugin.xml
  sjb/generated/test_pull_request_jenkins_sync_plugin.xml
Labels: approved, lgtm, size/M

#1642 Tweaking emails
  jobs/build/ocp/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
Labels: size/S

#1643 Updating job to invoke a jenkins job on cr.ops.openshift.com
  jobs/build/aws-ami/Jenkinsfile
Labels: size/L

#1645 Updating payload to be correct format
  jobs/build/aws-ami/Jenkinsfile
Labels: size/S

#1648 Removing the ami-updater job
  jobs/build/ami-updater/Jenkinsfile
  jobs/build/ami-updater/roles/fstab_mount_options/README.md
  jobs/build/ami-updater/roles/fstab_mount_options/meta/main.yml
  jobs/build/ami-updater/roles/fstab_mount_options/tasks/main.yml
  jobs/build/ami-updater/roles/registry_credentials_sync/README.md
  jobs/build/ami-updater/roles/registry_credentials_sync/files/ops-registry-secret-sync.service
  jobs/build/ami-updater/roles/registry_credentials_sync/files/ops-registry-secret-sync.sh
  jobs/build/ami-updater/roles/registry_credentials_sync/meta/main.yml
  jobs/build/ami-updater/roles/registry_credentials_sync/tasks/main.yml
  jobs/build/ami-updater/update_base_ami.yml
Labels: size/XL

#1649 Update ART mailing list recipients
  jobs/build/ocp_3.11_test/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
Labels: size/XS

#1650 Replace OIT with Doozer
  build-scripts/ose_images/README.md
  build-scripts/ose_images/ose.conf
  build-scripts/ose_images/ose_images.sh
  docs/sop/cut-new-release.md
  jobs/build/buildvm-maint/Jenkinsfile
  jobs/build/buildvm-maint/scripts/maintenance.sh
  jobs/build/ocp-parallel
  jobs/build/ocp/Jenkinsfile
  jobs/build/ocp_3.11_test/Jenkinsfile
  jobs/build/openshift-online/Jenkinsfile
  jobs/build/openshift-online/scripts/merge-and-build-openshift-scripts.sh
  jobs/build/ose/Jenkinsfile
  jobs/build/ose/scripts/build-and-push.sh
  jobs/build/ose/scripts/merge-and-build.sh
  jobs/build/refresh-images/Jenkinsfile
  jobs/build/scan-images/Jenkinsfile
  jobs/build/scan-images/README.md
  pipeline-scripts/buildlib.groovy
Labels: size/XXL

#1651 Remove online:stg and fix merge-and-build.sh
  jobs/build/ocp/Jenkinsfile
  jobs/build/ose/scripts/merge-and-build.sh
Labels: size/L

#1652 MAO Makefile: e2e renamed to integration
  sjb/config/test_cases/ci-kubernetes-machine-api-operator.yml
  sjb/generated/ci-kubernetes-machine-api-operator.xml
Labels: size/XS

#1653 MAO: e2e binary to integration
  sjb/config/test_cases/ci-kubernetes-machine-api-operator.yml
  sjb/generated/ci-kubernetes-machine-api-operator.xml
Labels: size/XS

#1656 Move oc quay mirror into scheduled-jobs
  scheduled-jobs/build/oc-mirror-quay-dev/Jenkinsfile
  scheduled-jobs/build/oc-mirror-quay-dev/README.md
Labels: size/XS
