Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-03, with the labels that each got.

#1174 add origin version variable to image registry job
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/generated/merge_pull_request_wildfly_images.xml
  sjb/generated/push_wildfly_images.xml
Labels: size/S

#1175 cicd-control: updated yum variable
  tower-scripts/bin/cicd-control.sh
Labels: size/XS

#1176 Build the image registry in release-3.9
  sjb/config/test_cases/test_branch_image_registry_extended.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_crio.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_containerized.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_in_tree.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_system_containers.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_update.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_update_containerized.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_update_system_containers.yml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_branch_origin_extended_conformance_crio.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_containerized.xml
  sjb/generated/test_branch_origin_extended_conformance_install_in_tree.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_branch_origin_extended_conformance_install_update.xml
  sjb/generated/test_branch_origin_extended_conformance_install_update_containerized.xml
  sjb/generated/test_branch_origin_extended_conformance_install_update_system_containers.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_containerized.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_crio.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_in_tree.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_update.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_update_containerized.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_update_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_origin_extended_conformance_crio.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install_update.xml
Labels: size/M

#1178 update jobs for logging 39
  sjb/config/test_cases/test_pull_request_openshift_ansible_logging_39.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible_39.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible_json_file_39.yml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_39.xml
Labels: size/XXL

#1179 logging sync ansible 3.9
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible_json_file_39.yml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_39.xml
Labels: size/M

#1180 DRY out the origin conformance install parents
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_install.yml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
Labels: size/XXL

#1182 remove jminter from devexp jenkins emails
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/config/test_cases/test_branch_origin_extended_builds.yml
  sjb/config/test_cases/test_branch_origin_extended_clusterup.yml
  sjb/config/test_cases/test_branch_origin_extended_image_ecosystem.yml
  sjb/config/test_cases/test_branch_origin_extended_image_registry.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/push_wildfly_images.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_clusterup.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
Labels: size/S

#1190 fix done/fi typo
  sjb/actions/clonerefs.py
  sjb/generated/push_origin_release.xml
  sjb/generated/test_branch_origin_cmd.xml
  sjb/generated/test_branch_origin_end_to_end.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_networking.xml
  sjb/generated/test_branch_origin_extended_networking_minimal.xml
  sjb/generated/test_branch_origin_unit.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_39.xml
  sjb/generated/test_pull_request_origin_cmd.xml
  sjb/generated/test_pull_request_origin_end_to_end.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_clusterup.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_origin_extended_ldap_groups.xml
  sjb/generated/test_pull_request_origin_extended_networking.xml
  sjb/generated/test_pull_request_origin_extended_networking_minimal.xml
  sjb/generated/test_pull_request_origin_unit.xml
Labels: size/M

#1172 Fall back to vX.Y for image tag during install
  sjb/config/common/test_cases/origin_installed_release.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_crio.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_containerized.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_system_containers.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_update_containerized.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_update_system_containers.yml
  sjb/generated/merge_pull_request_jenkins_client_plugin.xml
  sjb/generated/merge_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/merge_pull_request_jenkins_plugin.xml
  sjb/generated/merge_pull_request_jenkins_sync_plugin.xml
  sjb/generated/test_branch_jenkins_client_plugin.xml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_branch_jenkins_plugin.xml
  sjb/generated/test_branch_jenkins_sync_plugin.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_conformance_crio.xml
  sjb/generated/test_branch_origin_extended_conformance_install_containerized.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_branch_origin_extended_conformance_install_update_containerized.xml
  sjb/generated/test_branch_origin_extended_conformance_install_update_system_containers.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_jenkins_client_plugin.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_plugin.xml
  sjb/generated/test_pull_request_jenkins_sync_plugin.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_containerized.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_crio.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_update_containerized.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_update_system_containers.xml
  sjb/generated/test_pull_request_origin_extended_conformance_crio.xml
Labels: size/L

#1195 Bump OSE_MASTER to 3.10
  jobs/build/ose/Jenkinsfile
Labels: size/XS

#1197 Remove cron schedules from AMI jobs
  sjb/config/test_cases/ami_build_origin_int_rhel_base.yml
  sjb/config/test_cases/ami_build_origin_int_rhel_crio.yml
  sjb/config/test_cases/ami_build_origin_int_rhel_install.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_base.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/ami_build_origin_int_rhel_install.xml
Labels: size/S

#1198 Remove the install stage AMI job
  sjb/config/test_cases/ami_build_origin_int_rhel_install.yml
  sjb/generated/ami_build_origin_int_rhel_install.xml
Labels: size/L

#1201 removing OSE_MASTER reference
  jobs/build/ose/Jenkinsfile
  jobs/build/ose/scripts/merge-and-build.sh
Labels: size/M

#1203 Remove unused merge job for WildFly
  sjb/config/test_cases/merge_pull_request_wildfly_images.yml
  sjb/generated/merge_pull_request_wildfly_images.xml
Labels: size/L

#1204 Add a script to remove jobs from Jenkins after deletion here
  sjb/remove-jobs.sh
Labels: size/M

#1205 Remove timer from extended non-conformance tests
  sjb/config/test_cases/test_branch_origin_extended_builds.yml
  sjb/config/test_cases/test_branch_origin_extended_clusterup.yml
  sjb/config/test_cases/test_branch_origin_extended_gssapi.yml
  sjb/config/test_cases/test_branch_origin_extended_image_ecosystem.yml
  sjb/config/test_cases/test_branch_origin_extended_image_registry.yml
  sjb/config/test_cases/test_branch_origin_extended_ldap_groups.yml
  sjb/config/test_cases/test_branch_origin_extended_networking.yml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_clusterup.xml
  sjb/generated/test_branch_origin_extended_gssapi.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_branch_origin_extended_ldap_groups.xml
  sjb/generated/test_branch_origin_extended_networking.xml
Labels: size/M

#1207 aws-ami build: switch to using crio from rpm
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1188 build/refresh-images: disable ami job
  jobs/build/refresh-images/Jenkinsfile
Labels: size/XS

#1208 Build more in logging jobs, explicitly set repos to use
  sjb/children.sh
  sjb/config/common/test_cases/origin_release_with_ecosystem.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_logging_36.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_logging_37.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_logging_39.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/parents.sh
Labels: size/XL

#1054 Adding buildvm snapshot email to buildvm-maint
  jobs/build/buildvm-maint/Jenkinsfile
  jobs/build/buildvm-maint/scripts/gen_snapshot.sh
  jobs/build/buildvm-maint/scripts/snapshot.sh
Labels: size/M

#1212 Make image tag logic more consistent, stop passing tag explicitly
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/config/common/test_cases/origin_installed_release.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_containerized.yml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_branch_jenkins_client_plugin.xml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_branch_jenkins_plugin.xml
  sjb/generated/test_branch_jenkins_sync_plugin.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_containerized.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
  sjb/generated/test_pull_request_jenkins_client_plugin.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_plugin.xml
  sjb/generated/test_pull_request_jenkins_sync_plugin.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_containerized.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
Labels: size/L

#1213 Fix sync in push jobs
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/push_wildfly_images.xml
Labels: size/M

#1214 remove repo sync override
  sjb/config/test_cases/test_pull_request_jenkins_images.yml
  sjb/generated/test_pull_request_jenkins_images.xml
Labels: size/M

#1215 Update jobs based on s2i to use clonerefs and initupload
  sjb/config/common/test_cases/s2i.yml
  sjb/config/test_cases/test_branch_jenkins_images.yml
  sjb/config/test_cases/test_branch_wildfly_images.yml
  sjb/config/test_cases/test_pull_request_jenkins_images.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/push_wildfly_images.xml
  sjb/generated/test_branch_jenkins_images.xml
  sjb/generated/test_branch_wildfly_images.xml
  sjb/generated/test_pull_request_jenkins_images.xml
  sjb/generated/test_pull_request_wildfly_images.xml
Labels: size/XL

#1218 Always record the Origin metadata
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/config/common/test_cases/origin_release.yml
  sjb/generated/push_origin_release.xml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_origin_end_to_end.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_branch_origin_extended_networking.xml
  sjb/generated/test_branch_origin_extended_networking_minimal.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_end_to_end.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_clusterup.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_origin_extended_ldap_groups.xml
  sjb/generated/test_pull_request_origin_extended_networking.xml
  sjb/generated/test_pull_request_origin_extended_networking_minimal.xml
Labels: size/XXL

#1219 print the s2i version
  sjb/config/common/test_cases/s2i.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/push_wildfly_images.xml
  sjb/generated/test_branch_jenkins_images.xml
  sjb/generated/test_branch_wildfly_images.xml
  sjb/generated/test_pull_request_jenkins_images.xml
  sjb/generated/test_pull_request_wildfly_images.xml
Labels: size/S

#1222 push out the new agent images
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/generated/push_jenkins_images.xml
Labels: size/M

#1223 fix a typo
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/generated/push_jenkins_images.xml
Labels: size/S

#1217 Add separate jobs for openshift-ansible release-3.x branches
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_release_36.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_release_37.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_release_39.yml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
Labels: size/XXL

#1225 Sync master in push jobs so they can be periodic
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/config/test_cases/push_origin_release.yml
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/push_origin_release.xml
  sjb/generated/push_wildfly_images.xml
Labels: size/S

#1228 Use Prow variable for target branch in Jenkins push
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/generated/push_jenkins_images.xml
Labels: size/XS

#1119 Create jenkins setup for pull-request/branch jobs for ovn-kubernetes project
  sjb/config/test_cases/test_branch_ovn_kubernetes_unit.yml
  sjb/config/test_cases/test_pull_request_ovn_kubernetes_rhel.yml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_ovn_kubernetes_rhel.xml
Labels: size/XL

#1230 Move crio and kubernetes jobs to prow
  sjb/config/common/test_cases/kubernetes.yml
  sjb/config/test_cases/ci-kubernetes-conformance-node-e2e-containerized-rhel.yml
  sjb/config/test_cases/ci-kubernetes-conformance-node-e2e-rhel.yml
  sjb/config/test_cases/test_pull_request_crio_ami_rhel.yml
  sjb/generated/ci-kubernetes-conformance-node-e2e-containerized-rhel.xml
  sjb/generated/ci-kubernetes-conformance-node-e2e-rhel.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
Labels: size/L

#1236 always use latest logging image version
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
Labels: size/XS

#1237 Use logging images with release_commit tag for security
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
Labels: size/S

#1238 Remove more openshift_image_tag values
  sjb/config/test_cases/test_branch_origin_extended_conformance_crio.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_containerized.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_update_containerized.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_update_system_containers.yml
  sjb/generated/test_branch_origin_extended_conformance_crio.xml
  sjb/generated/test_branch_origin_extended_conformance_install_containerized.xml
  sjb/generated/test_branch_origin_extended_conformance_install_update_containerized.xml
  sjb/generated/test_branch_origin_extended_conformance_install_update_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_containerized.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_crio.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_update_containerized.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_update_system_containers.xml
  sjb/generated/test_pull_request_origin_extended_conformance_crio.xml
Labels: size/M

#1239 json-file: Use logging images with release_commit tag for security
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file.yml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
Labels: size/S

#1243 GCP tags are incorrect
  sjb/config/common/test_cases/origin_release_install_gce.yml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha_39.xml
  sjb/generated/test_pull_request_openshift_ansible_launch_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce_36.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce_37.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_origin_launch_gce.xml
Labels: size/M

#1244 aws-ami: added branch capabilities
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1248 aws-updater: enable crio by default. This might change in the future, until then, let's default it
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1246 Pass in ansible branch appropriate for release
  jobs/build/ocp/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/XS

#1192 Collect entire journal since boot for crio tests
  sjb/config/common/test_cases/crio.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
Labels: size/M

#1191 catalog: change origin build and add logging
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/config/test_cases/test_pull_request_origin_service_catalog.yml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_pull_request_origin_service_catalog.xml
Labels: size/L

#1249 Fix image registry jobs
  sjb/config/test_cases/test_branch_image_registry_extended.yml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
Labels: lgtm, size/S

#1240 Drop extended_networking_minimal
  sjb/config/common/test_suites/origin_fast.yml
  sjb/config/test_cases/test_branch_origin_extended_networking_minimal.yml
  sjb/config/test_cases/test_pull_request_origin_extended_networking_minimal.yml
  sjb/generated/test_branch_origin_extended_networking_minimal.xml
  sjb/generated/test_pull_request_origin_extended_networking_minimal.xml
Labels: size/XXL

#1210 Use proper oc binary and openshift images when testing origin-web-console
  sjb/config/test_cases/test_branch_origin_web_console.yml
  sjb/generated/test_branch_origin_web_console.xml
  sjb/generated/test_pull_request_origin_web_console.xml
Labels: do-not-merge/hold, size/L, ¯\_(ツ)_/¯

#1250 Remove option from journalctl generated artifact
  sjb/config/common/test_cases/crio.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
  sjb/generated/test_pull_request_ovn_kubernetes_rhel.xml
Labels: size/M

#1251 Doubling kibana memory limit to help it start up more frequently
  sjb/inventory/group_vars/OSEv3/logging.yml
Labels: size/XS

#1252 add origin to synced repos
  sjb/config/test_cases/test_branch_image_registry_extended.yml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
Labels: lgtm, size/XS

#1232 Introduce JJ for kubernetes-incubator/descheduler
  sjb/config/test_cases/ci-kubernetes-descheduler-e2e-gce.yml
  sjb/generated/ci-kubernetes-descheduler-e2e-gce.xml
Labels: size/XL

#1253 aws-ami: added an option to pass in openshift-ansible git url; for testing purposes
  jobs/build/aws-ami/Jenkinsfile
Labels: size/S

#1254 Move logging and metrics push jobs as postsubmits
  sjb/config/test_cases/push_origin_aggregated_logging_release.yml
  sjb/config/test_cases/push_origin_metrics_release.yml
  sjb/generated/push_origin_aggregated_logging_release.xml
  sjb/generated/push_origin_metrics_release.xml
Labels: size/L

#1255 Use clonerefs in kube metrics/cluster operator
  sjb/config/test_cases/test_branch_cluster_operator_unit.yml
  sjb/config/test_cases/test_branch_kubernetes_metrics_server_unit.yml
  sjb/config/test_cases/test_pull_request_cluster_operator_unit.yml
  sjb/config/test_cases/test_pull_request_kubernetes_metrics_server_unit.yml
  sjb/generated/test_branch_cluster_operator_unit.xml
  sjb/generated/test_branch_kubernetes_metrics_server_unit.xml
  sjb/generated/test_pull_request_cluster_operator_unit.xml
  sjb/generated/test_pull_request_kubernetes_metrics_server_unit.xml
Labels: size/XL

#1256 Use ansible 3.9 for 3.7 and 3.8 installs (needed for GCP)
  sjb/config/common/test_cases/origin_release_install_gce.yml
  sjb/config/common/test_cases/origin_release_install_gce_37.yml
  sjb/config/common/test_cases/origin_release_install_gce_38.yml
  sjb/config/common/test_cases/origin_release_install_gce_39.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_gce_37.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_gce_38.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_gce.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_gce_37.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_gce_39.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_gce_ha.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_gce_ha_39.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_gce.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_gce_37.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_gce_39.yml
  sjb/generated/ci-kubernetes-descheduler-e2e-gce.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce_37.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce_39.xml
  sjb/generated/test_branch_origin_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_gce_37.xml
  sjb/generated/test_branch_origin_extended_conformance_gce_38.xml
  sjb/generated/test_branch_origin_extended_conformance_gce_39.xml
  sjb/generated/test_branch_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha_39.xml
  sjb/generated/test_pull_request_openshift_ansible_launch_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce_37.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_origin_launch_gce.xml
  sjb/push-update.sh
Labels: size/L

#1260 dedicated can now use a passed in version of openshift ansible
  tower-scripts/bin/cicd-control.sh
Labels: size/S

#1258 Use clonerefs on the remaining simpler jobs
  sjb/config/test_cases/test_branch_image_registry_integration.yml
  sjb/config/test_cases/test_branch_image_registry_unit.yml
  sjb/config/test_cases/test_branch_online_console_extensions.yml
  sjb/config/test_cases/test_branch_online_hibernation_unit.yml
  sjb/config/test_cases/test_branch_origin_web_console_server_check.yml
  sjb/config/test_cases/test_pull_request_image_registry_integration.yml
  sjb/config/test_cases/test_pull_request_image_registry_unit.yml
  sjb/config/test_cases/test_pull_request_online_console_extensions.yml
  sjb/config/test_cases/test_pull_request_online_hibernation_unit.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_tox.yml
  sjb/config/test_cases/test_pull_request_origin_web_console_server_check.yml
  sjb/generated/test_branch_image_registry_integration.xml
  sjb/generated/test_branch_image_registry_unit.xml
  sjb/generated/test_branch_online_console_extensions.xml
  sjb/generated/test_branch_online_hibernation_unit.xml
  sjb/generated/test_branch_origin_web_console_server_check.xml
  sjb/generated/test_pull_request_image_registry_integration.xml
  sjb/generated/test_pull_request_image_registry_unit.xml
  sjb/generated/test_pull_request_online_console_extensions.xml
  sjb/generated/test_pull_request_online_hibernation_unit.xml
  sjb/generated/test_pull_request_openshift_ansible_tox.xml
  sjb/generated/test_pull_request_origin_web_console_server_check.xml
Labels: size/XXL

#1259 Use clonerefs on simple origin jobs
  sjb/config/test_cases/test_branch_origin_check.yml
  sjb/config/test_cases/test_branch_origin_cross.yml
  sjb/config/test_cases/test_branch_origin_integration.yml
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/config/test_cases/test_branch_origin_verify.yml
  sjb/config/test_cases/test_pull_request_origin_cross.yml
  sjb/config/test_cases/test_pull_request_origin_integration.yml
  sjb/config/test_cases/test_pull_request_origin_verify.yml
  sjb/generated/test_branch_origin_check.xml
  sjb/generated/test_branch_origin_cross.xml
  sjb/generated/test_branch_origin_integration.xml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_branch_origin_verify.xml
  sjb/generated/test_pull_request_origin_cross.xml
  sjb/generated/test_pull_request_origin_integration.xml
  sjb/generated/test_pull_request_origin_verify.xml
Labels: size/XXL

#1261 Remove deleting GCP bucket contents
  sjb/config/common/test_cases/origin_release_install_gce.yml
  sjb/config/common/test_cases/origin_release_install_gce_37.yml
  sjb/config/common/test_cases/origin_release_install_gce_38.yml
  sjb/config/common/test_cases/origin_release_install_gce_39.yml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce_37.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce_39.xml
  sjb/generated/test_branch_origin_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_gce_37.xml
  sjb/generated/test_branch_origin_extended_conformance_gce_38.xml
  sjb/generated/test_branch_origin_extended_conformance_gce_39.xml
  sjb/generated/test_branch_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha_39.xml
  sjb/generated/test_pull_request_openshift_ansible_launch_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce_37.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_origin_launch_gce.xml
Labels: size/L

#1262 clean up wildfly push job
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/config/test_cases/test_branch_wildfly_images.yml
  sjb/generated/push_wildfly_images.xml
  sjb/generated/test_branch_wildfly_images.xml
  sjb/generated/test_pull_request_wildfly_images.xml
Labels: size/M

#1263 Copy the web console image into the crio storage layer
  sjb/config/test_cases/test_branch_origin_extended_conformance_crio.yml
  sjb/generated/test_branch_origin_extended_conformance_crio.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_crio.xml
  sjb/generated/test_pull_request_origin_extended_conformance_crio.xml
Labels: size/M

#1264 Adding parallel ocp build
  jobs/build/ocp-parallel
Labels: size/XS

#1266 update devex job email lists
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/config/test_cases/test_branch_origin_extended_builds.yml
  sjb/config/test_cases/test_branch_origin_extended_clusterup.yml
  sjb/config/test_cases/test_branch_origin_extended_image_ecosystem.yml
  sjb/config/test_cases/test_branch_origin_extended_image_registry.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/push_wildfly_images.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_clusterup.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
Labels: size/S

#1267 Add .8 and .9 and change the default
  Jenkinsfile
Labels: size/XS

#1265 Use clonerefs on all prow jobs
  sjb/config/test_cases/test_branch_origin_extended_conformance_crio.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_containerized.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_in_tree.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_update.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_update_containerized.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_install_update_system_containers.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_containerized.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_crio.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_in_tree.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_update.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_update_containerized.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_update_system_containers.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_crio.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_install_update.yml
  sjb/generated/test_branch_origin_extended_conformance_crio.xml
  sjb/generated/test_branch_origin_extended_conformance_install_containerized.xml
  sjb/generated/test_branch_origin_extended_conformance_install_in_tree.xml
  sjb/generated/test_branch_origin_extended_conformance_install_update.xml
  sjb/generated/test_branch_origin_extended_conformance_install_update_containerized.xml
  sjb/generated/test_branch_origin_extended_conformance_install_update_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_containerized.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_crio.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_in_tree.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_update.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_update_containerized.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_update_system_containers.xml
  sjb/generated/test_pull_request_origin_extended_conformance_crio.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install_update.xml
Labels: size/XXL

#1268 Fix test_pull_request_origin_cross' parent
  sjb/config/test_cases/test_pull_request_origin_cross.yml
  sjb/generated/test_pull_request_origin_cross.xml
Labels: size/L

#1270 Fix usage of cluster up to use --tag instead of --version
  sjb/config/test_cases/test_pull_request_origin_service_catalog.yml
Labels: size/XS

#1271 Use '--tag' flag in UI tests
  sjb/config/test_cases/test_branch_origin_web_console.yml
  sjb/config/test_cases/test_branch_origin_web_console_server_e2e.yml
  sjb/generated/test_branch_origin_web_console.xml
  sjb/generated/test_branch_origin_web_console_server_e2e.xml
  sjb/generated/test_pull_request_origin_web_console.xml
  sjb/generated/test_pull_request_origin_web_console_server_e2e.xml
Labels: lgtm, size/S

#1272 Change oc cluster up to use --tag
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/generated/test_branch_origin_service_catalog.xml
Labels: size/XS

#1274 locking ansible version of ansible to 2.4
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS
