Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-05, with the labels that each got.

#1332 catalog: more generated files
  sjb/generated/push_origin_release.xml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_end_to_end.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_branch_origin_extended_conformance_k8s.xml
  sjb/generated/test_branch_origin_extended_gssapi.xml
  sjb/generated/test_branch_origin_extended_ldap_groups.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_openshift_ansible_install_upgrade_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_launch_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
  sjb/generated/test_pull_request_origin_end_to_end.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_origin_extended_gssapi.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_origin_extended_ldap_groups.xml
  sjb/generated/test_pull_request_origin_launch_gce.xml
Labels: size/XL

#1333 catalog: add ORIGIN_COMMIT file
  sjb/config/common/test_cases/origin_release_with_ecosystem.yml
  sjb/generated/push_origin_release.xml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_end_to_end.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_branch_origin_extended_conformance_k8s.xml
  sjb/generated/test_branch_origin_extended_gssapi.xml
  sjb/generated/test_branch_origin_extended_ldap_groups.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_openshift_ansible_install_upgrade_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_launch_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
  sjb/generated/test_pull_request_origin_end_to_end.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_origin_extended_gssapi.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_origin_extended_ldap_groups.xml
  sjb/generated/test_pull_request_origin_launch_gce.xml
Labels: size/L

#1337 aws-ami: changed the delimiters to commaas, not newlines because of jenkins bugs
  jobs/build/aws-ami/Jenkinsfile
Labels: size/S

#1342 Enabling ability to skip image builds for release builds
  Jenkinsfile
  jobs/build/ami-updater/Jenkinsfile
  jobs/build/aws-ami/Jenkinsfile
  jobs/build/buildvm-maint/Jenkinsfile
  jobs/build/make-puddle/Jenkinsfile
  jobs/build/ocp/Jenkinsfile
  jobs/build/openshift-online/Jenkinsfile
  jobs/build/ose/Jenkinsfile
  jobs/build/ose/scripts/merge-and-build.sh
  jobs/build/refresh-images/Jenkinsfile
  jobs/build/scan-images/Jenkinsfile
  jobs/devex/jenkins-bump-version/Jenkinsfile
  jobs/devex/jenkins-plugins/Jenkinsfile
  jobs/sprint/control/Jenkinsfile
  jobs/sprint/merge-gating/Jenkinsfile
  jobs/sprint/stage-to-prod/Jenkinsfile
  jobs/starter/operation/Jenkinsfile
  jobs/starter/perf/Jenkinsfile
  jobs/starter/rotate-log-access-key/Jenkinsfile
  jobs/starter/smoke-test/Jenkinsfile
  jobs/starter/upgrade/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/deploylib.groovy
  scheduled-jobs/build/logging-and-metrics-distgit-populator/Jenkinsfile
  scheduled-jobs/build/rhel7next/Jenkinsfile
Labels: size/L

#1343 remove defunct openshift rhel7 mirrors from rhel_base_images and kids
  sjb/config/common/test_cases/rhel_base_images.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/test_branch_jenkins_images.xml
  sjb/generated/test_pull_request_jenkins_images.xml
Labels: size/S

#1346 Adding authentication to quay.io
  pipeline-scripts/buildlib.groovy
Labels: size/XS

#1339 Bump k8s CI jobs to go1.10.1
  sjb/config/test_cases/ci-kubernetes-conformance-node-e2e-containerized-rhel.yml
  sjb/config/test_cases/ci-kubernetes-conformance-node-e2e-rhel.yml
  sjb/generated/ci-kubernetes-conformance-node-e2e-containerized-rhel.xml
  sjb/generated/ci-kubernetes-conformance-node-e2e-rhel.xml
Labels: size/M

#1349 Add catalog repo sync
  sjb/config/common/test_cases/origin_release_with_ecosystem.yml
  sjb/generated/test_branch_origin_end_to_end.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_end_to_end.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_gssapi.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_origin_extended_ldap_groups.xml
Labels: size/S

#1344 Added timing metrics and image list to email report
  jobs/build/ocp/Jenkinsfile
Labels: size/M

#1329 Add cluster_operator e2e test
  sjb/config/test_cases/test_branch_cluster_operator_e2e.yml
  sjb/config/test_cases/test_pull_request_cluster_operator_e2e.yml
  sjb/generated/test_branch_cluster_operator_e2e.xml
  sjb/generated/test_pull_request_cluster_operator_e2e.xml
Labels: size/XXL

#1352 Pass in buildlib to gather metrics
  jobs/build/ocp/Jenkinsfile
Labels: size/S

#1355 Adding RPM Only to job description
  jobs/build/ocp/Jenkinsfile
  jobs/build/ose/Jenkinsfile
Labels: size/S

#1354 just pass in the data needed
  jobs/build/ocp/Jenkinsfile
Labels: size/S

#1350 Bump k8s CI jobs to go1.10.2
  sjb/config/test_cases/ci-kubernetes-conformance-node-e2e-containerized-rhel.yml
  sjb/config/test_cases/ci-kubernetes-conformance-node-e2e-rhel.yml
  sjb/generated/ci-kubernetes-conformance-node-e2e-containerized-rhel.xml
  sjb/generated/ci-kubernetes-conformance-node-e2e-rhel.xml
Labels: size/S

#1351 cluster-operator: fix cluster cleanup by specifying fully qualified cluster type
  sjb/config/test_cases/test_branch_cluster_operator_e2e.yml
  sjb/generated/test_branch_cluster_operator_e2e.xml
  sjb/generated/test_pull_request_cluster_operator_e2e.xml
Labels: size/S

#1353 Skip cluster operator builds when deploying.
  sjb/config/test_cases/test_branch_cluster_operator_e2e.yml
  sjb/generated/test_branch_cluster_operator_e2e.xml
  sjb/generated/test_pull_request_cluster_operator_e2e.xml
Labels: lgtm, size/XS

#1356 gather-logs.py: gather-logs with 3.10 support. WARNING: 3.10 support is flaky and will probably change
  tower-scripts/bin/gather-logs.py
Labels: size/L

#1359 added verbosity option to cicd-control.py
  tower-scripts/bin/cicd-control.py
Labels: size/S

#1361 Do not create latest on non-image builds
  build-scripts/rcm-guest/publish-oc-binary.sh
  build-scripts/rcm-guest/push-to-mirrors.sh
  jobs/build/ocp/Jenkinsfile
  jobs/build/ose/Jenkinsfile
  jobs/build/ose/scripts/build-and-push.sh
  jobs/build/ose/scripts/merge-and-build.sh
  jobs/build/ose/scripts/rcm-guest-print-building-changelog-report.sh
Labels: size/M

#1363 catalog: restrict yum install to only one repo
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_pull_request_openshift_service_catalog.xml
  sjb/generated/test_pull_request_origin_service_catalog.xml
Labels: size/XS

#1364 Removed qualification to send CI bus message only for starter.
  jobs/starter/upgrade/Jenkinsfile
Labels: size/XS

#1365 Faster cloning for build jobs
  jobs/build/ose/scripts/merge-and-build.sh
  pipeline-scripts/buildlib.groovy
Labels: size/S

#1370 Fix failing install of openshift client
  sjb/config/test_cases/test_branch_cluster_operator_e2e.yml
  sjb/generated/test_branch_cluster_operator_e2e.xml
  sjb/generated/test_pull_request_cluster_operator_e2e.xml
Labels: size/XS

#1371 update openshift-ansible version in INT
  tower-scripts/bin/gogitit_online_int.yml
Labels: size/XS

#1374 Create latest symlink on rcm-guest
  build-scripts/rcm-guest/push-to-mirrors.sh
Labels: size/S

#1373 azure playbooks: use sync correctly
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/config/test_cases/azure_build_base_image_centos.yml
  sjb/config/test_cases/azure_build_base_image_rhel.yml
  sjb/config/test_cases/azure_build_node_image_centos_39.yml
  sjb/config/test_cases/azure_build_node_image_rhel_39.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_azure_39.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_azure_39.yml
  sjb/generated/azure_build_base_image_centos.xml
  sjb/generated/azure_build_base_image_rhel.xml
  sjb/generated/azure_build_node_image_centos_39.xml
  sjb/generated/azure_build_node_image_rhel_39.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: lgtm, size/XL

#1376 fixed the online role to get vendored
  tower-scripts/bin/cicd-control.py
Labels: size/XS

#1377 cicd-control.py: added a step to skip the ops cloning
  tower-scripts/bin/cicd-control.py
Labels: size/S

#1310 Split AMI build and validation steps, implement launch permission grant capability
  sjb/actions/host_script.py
  sjb/actions/provision.py
  sjb/config/common/test_cases/ami_build.yml
  sjb/config/test_cases/ami_build_origin_int_rhel_base.yml
  sjb/config/test_cases/ami_validate_origin_int_rhel_base.yml
  sjb/generate.py
  sjb/generated/ami_build_origin_int_rhel_base.xml
  sjb/generated/ami_validate_origin_int_rhel_base.xml
  sjb/syntax.md
  sjb/templates/test_case.xml
Labels: size/XL

#1381 Forgot to place build steps in override block
  sjb/config/test_cases/ami_build_origin_int_rhel_base.yml
  sjb/generated/ami_build_origin_int_rhel_base.xml
Labels: size/L

#1380 switch email notifications for cluster up tests
  sjb/config/test_cases/test_branch_origin_extended_clusterup.yml
  sjb/generated/test_branch_origin_extended_clusterup.xml
Labels: lgtm, size/S

#1383 Include verify_fail_log.yml from images:verify in build artifacts
  jobs/build/refresh-images/Jenkinsfile
Labels: size/XS

#1386 Added msg to the messageContent body to detect on datagrepper searches.
  jobs/starter/send-ci-msg/Jenkinsfile
Labels: size/XS

#1395 mlamouri joins the build/ocp fail mailing list
  jobs/build/ocp/Jenkinsfile
  jobs/build/ose/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
Labels: size/XS

#1396 Job to push cluster operator images
  sjb/config/test_cases/push_cluster_operator_images.yml
  sjb/generated/push_cluster_operator_images.xml
Labels: size/XL

#1389 Refresh version check
  jobs/build/refresh-images/Jenkinsfile
Labels: size/S

#1397 use buildlib function for kerberos ticket
  jobs/build/refresh-images/Jenkinsfile
Labels: size/XS

#1382 Add optional stage to attach images after a refresh
  jobs/build/refresh-images/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/M

#1398 cluster-operator: increase timeouts for cluster creation and teardown
  sjb/config/test_cases/test_branch_cluster_operator_e2e.yml
  sjb/generated/test_branch_cluster_operator_e2e.xml
  sjb/generated/test_pull_request_cluster_operator_e2e.xml
Labels: size/S

#1399 Azure build jobs for master.
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/test_cases/azure_build_node_image_centos.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_azure.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_azure.yml
  sjb/generated/azure_build_node_image_centos.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
Labels: lgtm, size/XXL

#1401 Enabling CI message for dedicated
  jobs/starter/send-ci-msg/Jenkinsfile
  jobs/starter/send-ci-msg/README.md
  jobs/starter/upgrade/Jenkinsfile
Labels: size/M

#1402 Adding test release addition to OCP builds
  jobs/build/ocp/Jenkinsfile
Labels: size/S

#1400 reformatted parameters in refresh-images
  jobs/build/refresh-images/Jenkinsfile
Labels: size/L

#1406 Missing comma and join use
  jobs/build/refresh-images/Jenkinsfile
Labels: size/M

#1411 azure: don't stomp .latest-rpms
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: lgtm, size/M

#1413 Adding install repo parameter to build node image.
  sjb/config/test_cases/azure_build_node_image_centos.yml
  sjb/generated/azure_build_node_image_centos.xml
Labels: lgtm, size/XS

#1414 cleaned parameter definitions for builvm-maint
  jobs/build/buildvm-maint/Jenkinsfile
Labels: size/S

#1416 fixed scalegroups typo
  tower-scripts/bin/cicd-control.py
Labels: size/XS

#1418 Fix CI msg position
  jobs/starter/upgrade/Jenkinsfile
Labels: size/M

#1419 Adding in /ORIGIN_RELEASE file
  jobs/package-dockertested/install-origin-release.sh
Labels: size/XS

#1421 Reformat the parameter list for aws-ami Jenkinsfile
  jobs/build/aws-ami/Jenkinsfile
Labels: size/L

#1423 Adjusting for tower2 hostname
  docs/sop/checklist-cluster-upgrade.md
  docs/sop/gather-cluster-logs.md
  jobs/starter/rotate-log-access-key/Jenkinsfile
  pipeline-scripts/deploylib.groovy
  tower-scripts/README.md
  tower-scripts/bin/cicd-control.py
  tower-scripts/bin/cicd-control.sh
  tower-scripts/bin/clone_ops_git_repos.yml
Labels: size/S

#1425 Removing jenkins imagestream update
  jobs/starter/operation/Jenkinsfile
  jobs/starter/upgrade/Jenkinsfile
Labels: size/S

#1424 Fix ext. conf. cri-o install newline escape typo
  sjb/config/test_cases/test_branch_origin_extended_conformance_crio_rpm.yml
  sjb/generated/test_branch_origin_extended_conformance_crio_rpm.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_crio_rpm.xml
Labels: size/S

#1427 Allow package override repos for starter clusters
  jobs/starter/upgrade/Jenkinsfile
Labels: size/XS

#1428 select a version of openshift-ansible for the 3.10 upgrade
  tower-scripts/bin/gogitit_online_int.yml
  tower-scripts/bin/gogitit_online_prod.yml
  tower-scripts/bin/gogitit_online_stg.yml
Labels: size/XS

#1378 Run "delete-yum-repos" during stage "upgrade: misc"
  jobs/starter/upgrade/Jenkinsfile
Labels: size/XS
