Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-07, with the labels that each got.

#1502 changed disk size for ami build
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1501 add auto-mode stage
  jobs/build/ocp/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/buildlib_test.groovy
Labels: size/M

#1503 ami-build: added python-docker to make upgrade less painful
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1420 Add alderaan pipeline scripts
  alderaan/Jenkinsfile
  alderaan/pipeline-scripts/browbeat.groovy
  alderaan/pipeline-scripts/conformance.groovy
  alderaan/pipeline-scripts/deployments_per_ns.groovy
  alderaan/pipeline-scripts/http.groovy
  alderaan/pipeline-scripts/logging.groovy
  alderaan/pipeline-scripts/mastervertical.groovy
  alderaan/pipeline-scripts/nodevertical.groovy
  alderaan/pipeline-scripts/ns_per_cluster.groovy
  alderaan/pipeline-scripts/openshift.groovy
  alderaan/pipeline-scripts/openstack.groovy
  alderaan/pipeline-scripts/pgbench.groovy
  alderaan/pipeline-scripts/podvertical.groovy
  alderaan/pipeline-scripts/scaleup.groovy
  alderaan/pipeline-scripts/tooling.groovy
  alderaan/property_files/browbeat.properties
  alderaan/property_files/conformance.properties
  alderaan/property_files/deployments_per_ns.properties
  alderaan/property_files/http.properties
  alderaan/property_files/mastervertical.properties
  alderaan/property_files/nodevertical.properties
  alderaan/property_files/ns_per_cluster.properties
  alderaan/property_files/openshift.properties
  alderaan/property_files/openshift_scaleup.properties
  alderaan/property_files/openstack.properties
  alderaan/property_files/pgbench.properties
  alderaan/property_files/podvertical.properties
  alderaan/property_files/setup_pbench.properties
Labels: size/XXL

#1506 update devex team emails
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/config/test_cases/push_jenkins_images_310.yml
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/config/test_cases/test_branch_origin_extended_builds.yml
  sjb/config/test_cases/test_branch_origin_extended_builds_310.yml
  sjb/config/test_cases/test_branch_origin_extended_image_ecosystem.yml
  sjb/config/test_cases/test_branch_origin_extended_image_ecosystem_310.yml
  sjb/config/test_cases/test_branch_origin_extended_image_registry.yml
  sjb/config/test_cases/test_branch_origin_extended_image_registry_310.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/push_jenkins_images_310.xml
  sjb/generated/push_wildfly_images.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_builds_310.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem_310.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_branch_origin_extended_image_registry_310.xml
Labels: size/M

#1507 add verbosity and error checking to auto-mode
  jobs/build/ocp/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/S

#1508 more auto-mode fix
  jobs/build/ocp/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/XS

#1509 auto-mode should fail on bad mode
  pipeline-scripts/buildlib_test.groovy
Labels: size/S

#1504 Modify browbeat pipeline script to load up all the params
  alderaan/pipeline-scripts/browbeat.groovy
  alderaan/property_files/browbeat.properties
  alderaan/property_files/openshift.properties
  alderaan/property_files/openstack.properties
Labels: size/L

#1358 catalog: add support for other branches
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_pull_request_openshift_service_catalog.xml
  sjb/generated/test_pull_request_origin_service_catalog.xml
Labels: size/M

#1499 sjb/children.sh: lookup parents only once
  sjb/children.py
  sjb/children.sh
Labels: size/M

#1514 Added ci bus message for silent mode.
  jobs/starter/upgrade/Jenkinsfile
Labels: size/M

#1519 Adding elasticsearch node selectors since they are required as of 3.11
  sjb/config/test_cases/test_branch_openshift_ansible_logging.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
Labels: lgtm, size/M

#1521 move logging nodeselectors to inventory logging.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
  sjb/inventory/group_vars/OSEv3/logging.yml
Labels: lgtm, size/M

#1522 hacking to bypass a-o rpm build
  jobs/build/ocp_3.11_test/Jenkinsfile
Labels: size/XXL

#1524 analyze-upgrade-log: Show Ansible errors in summary
  tower-scripts/bin/analyze-upgrade-log
Labels: size/M

#1523 Update cluster operator e2e test to reflect latest state
  sjb/config/test_cases/test_branch_cluster_operator_e2e.yml
  sjb/generated/test_branch_cluster_operator_e2e.xml
  sjb/generated/test_pull_request_cluster_operator_e2e.xml
Labels: size/L

#1527 [wip] revert openshift-ansible builds in groovy/jenkins
  jobs/build/ocp/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: do-not-merge/work-in-progress, size/M

#1529 Enable ansible-2.6 repo on master branches
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/config/common/test_cases/origin_built_installed_release_37.yml
  sjb/config/common/test_cases/origin_built_installed_release_38.yml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_branch_jenkins_client_plugin.xml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_branch_jenkins_plugin.xml
  sjb/generated/test_branch_jenkins_sync_plugin.xml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
  sjb/generated/test_pull_request_jenkins_client_plugin.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_plugin.xml
  sjb/generated/test_pull_request_jenkins_sync_plugin.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install_39.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
Labels: size/XXL

#1515 Update catalog to sync repos using sync
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/config/test_cases/test_branch_origin_service_catalog_310.yml
  sjb/config/test_cases/test_pull_request_openshift_service_catalog.yml
  sjb/config/test_cases/test_pull_request_origin_service_catalog.yml
  sjb/config/test_cases/test_pull_request_origin_service_catalog_310.yml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_branch_origin_service_catalog_310.xml
  sjb/generated/test_pull_request_openshift_service_catalog.xml
  sjb/generated/test_pull_request_openshift_service_catalog_310.xml
  sjb/generated/test_pull_request_origin_service_catalog.xml
  sjb/generated/test_pull_request_origin_service_catalog_310.xml
Labels: size/XXL

#1530 remove logging 3.10 release job
  sjb/config/test_cases/push_origin_aggregated_logging_release.yml
  sjb/config/test_cases/push_origin_aggregated_logging_release_310.yml
  sjb/generated/push_origin_aggregated_logging_release.xml
  sjb/generated/push_origin_aggregated_logging_release_310.xml
Labels: size/L

#1532 Use origin-cli for 3.10+ to get oc for console tests
  sjb/config/test_cases/test_branch_origin_web_console.yml
  sjb/generated/test_branch_origin_web_console.xml
  sjb/generated/test_pull_request_origin_web_console.xml
Labels: size/M

#1533 ami building: bump python version to 2.6
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1535 more ami building updates since we went to 2.6
  jobs/build/aws-ami/copy_ami_to_regions.yml
Labels: size/XS

#1534 Switch to using the AWS cluster operator account for co e2e
  sjb/config/test_cases/test_branch_cluster_operator_e2e.yml
  sjb/generated/test_branch_cluster_operator_e2e.xml
  sjb/generated/test_pull_request_cluster_operator_e2e.xml
Labels: size/XS

#1539 ami builder: updated the repos for amibuilding, added ops repo; added rootlog
  jobs/build/aws-ami/Jenkinsfile
Labels: size/M

#1540 ami build: fixed escaping
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1518 Add pre-release testing for OSA
  sjb/config/test_cases/azure_build_node_image_centos_310.yml
  sjb/config/test_cases/azure_build_node_image_centos_39.yml
  sjb/config/test_cases/azure_build_node_image_rhel_310.yml
  sjb/config/test_cases/azure_build_node_image_rhel_39.yml
  sjb/generated/azure_build_node_image_centos_310.xml
  sjb/generated/azure_build_node_image_centos_39.xml
  sjb/generated/azure_build_node_image_rhel_310.xml
  sjb/generated/azure_build_node_image_rhel_39.xml
Labels: sig/azure, size/L

#1541 Add support to create new jobs in openshift qe jenkins
  alderaan/Jenkinsfile
  alderaan/alderaan-watcher.sh
  alderaan/config/jjb.ini
  alderaan/jjb/dynamic/README.md
  alderaan/jjb/dynamic/alderaan-pipeline.yml
  alderaan/jjb/static/README.md
  alderaan/pipeline-scripts/create_jobs.groovy
  alderaan/property_files/jobs.properties
Labels: size/L

#1542 fixed formatting in get_changelog, switched to using OA_CHANGELOG for…
  jobs/build/ocp/Jenkinsfile
Labels: size/S

#1543 use the passed argument to mail_success instead of the global
  jobs/build/ocp/Jenkinsfile
Labels: size/XS
