Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-12, with the labels that each got.

#1664 fixing missing params
  jobs/build/custom/Jenkinsfile
Labels: size/XS

#1665 [WIP] Fixing scm
  jobs/build/custom/Jenkinsfile
Labels: do-not-merge/work-in-progress, size/S

#1666 add push for wildfly v15
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/generated/push_wildfly_images.xml
Labels: size/M

#1667 More fixes to custom job
  jobs/build/custom/Jenkinsfile
Labels: size/M

#1668 Removed partial build logic
  jobs/build/custom/Jenkinsfile
Labels: size/S

#1669 Adding automatic merge job
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/merge_ocp/merge_ocp.sh
Labels: size/L

#1670 Various fixes to merge job
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/merge_ocp/merge_ocp.sh
Labels: size/M

#1671 Tweaking merge_ocp.sh
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/merge_ocp/merge_ocp.sh
Labels: size/S

#1672 Adding merge ocp schedule job
  scheduled-jobs/build/merge/Jenkinsfile
  scheduled-jobs/build/merge/README.md
Labels: size/S

#1673 Adding disableConcurrentBuilds to merge_ocp
  jobs/build/merge_ocp/Jenkinsfile
Labels: size/XS

#1675 Remove aos-art-requests from failure mailing list
  jobs/build/ocp/Jenkinsfile
Labels: lgtm, size/XS

#1677 Update libvirt libs in packet instance to 4.5 to sync with libvirt libs in docker image
  sjb/config/test_cases/pull-ci-openshift-cluster-api-provider-libvirt-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-provider-libvirt-master-e2e.xml
Labels: size/S

#1678 Don't use web-console for 4.x
  jobs/build/ocp/Jenkinsfile
Labels: size/S
