Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-08, with the labels that each got.

#1549 cluster-operator e2e: switch to using coutil for cluster verification
  sjb/config/test_cases/test_branch_cluster_operator_e2e.yml
  sjb/generated/test_branch_cluster_operator_e2e.xml
  sjb/generated/test_pull_request_cluster_operator_e2e.xml
Labels: size/XS

#1552 Fix cluster-operator image push job
  sjb/config/test_cases/push_cluster_operator_images.yml
  sjb/generated/push_cluster_operator_images.xml
Labels: size/S

#1553 added grubby cmd to ami updater
  jobs/build/ami-updater/update_base_ami.yml
Labels: size/XS

#1554 Provide aws machine controller ci job
  sjb/config/test_cases/ci-kubernetes-aws-actuator.yml
  sjb/generated/ci-kubernetes-aws-actuator.xml
Labels: size/XL

#1555 Cleanup emails
  sjb/config/test_cases/test_branch_origin_extended_gssapi.yml
  sjb/config/test_cases/test_branch_origin_extended_gssapi_310.yml
  sjb/config/test_cases/test_branch_origin_extended_ldap_groups.yml
  sjb/config/test_cases/test_branch_origin_extended_ldap_groups_310.yml
  sjb/generated/test_branch_origin_extended_gssapi.xml
  sjb/generated/test_branch_origin_extended_gssapi_310.xml
  sjb/generated/test_branch_origin_extended_ldap_groups.xml
  sjb/generated/test_branch_origin_extended_ldap_groups_310.xml
Labels: lgtm, size/S

#1550 update logging proxy image to 1.1.0 - hardcode kibana proxy image
  sjb/config/test_cases/test_branch_openshift_ansible_logging.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
Labels: lgtm, size/M

#1556 sync Origin to get latest source
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/config/test_cases/test_branch_origin_service_catalog_310.yml
  sjb/config/test_cases/test_pull_request_openshift_service_catalog_310.yml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_branch_origin_service_catalog_310.xml
  sjb/generated/test_pull_request_openshift_service_catalog.xml
  sjb/generated/test_pull_request_openshift_service_catalog_310.xml
  sjb/generated/test_pull_request_origin_service_catalog.xml
  sjb/generated/test_pull_request_origin_service_catalog_310.xml
Labels: size/L

#1544 post GA deprecate 3.9 builds
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/config/test_cases/azure_build_node_image_rhel.yml
  sjb/config/test_cases/azure_build_node_image_rhel_310.yml
  sjb/config/test_cases/azure_build_node_image_rhel_39.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_azure_39.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_azure_39.yml
  sjb/generated/azure_build_node_image_rhel.xml
  sjb/generated/azure_build_node_image_rhel_310.xml
  sjb/generated/azure_build_node_image_rhel_39.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
Labels: sig/azure, size/XXL

#1559 Provide CI job for machine-api-operator
  sjb/config/test_cases/ci-kubernetes-machine-api-operator.yml
  sjb/generated/ci-kubernetes-machine-api-operator.xml
Labels: size/XL

#1562 Minor upgrades to the job
  sjb/config/test_cases/ci-kubernetes-aws-actuator.yml
  sjb/generated/ci-kubernetes-aws-actuator.xml
Labels: size/XS

#1561 cluster-operator e2e: Install python-devel tools
  sjb/config/test_cases/test_branch_cluster_operator_e2e.yml
  sjb/generated/test_branch_cluster_operator_e2e.xml
  sjb/generated/test_pull_request_cluster_operator_e2e.xml
Labels: size/XS

#1471 Increase timeout for cri-o e2e testing
  sjb/config/test_cases/test_branch_crio_e2e_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_ami_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_e2e_rhel.yml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
Labels: size/S

#1563 CRI-O: create /data/gcs
  sjb/config/common/test_cases/crio.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/ci-kubernetes-machine-api-operator.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
  sjb/generated/test_pull_request_ovn_kubernetes_rhel.xml
Labels: lgtm, size/L

#1564 Removing oreg variable from 310
  sjb/config/test_cases/azure_build_node_image_rhel_310.yml
  sjb/generated/azure_build_node_image_rhel_310.xml
Labels: size/XS

#1565 CRI-O: disable df -h collection
  sjb/config/common/test_cases/crio.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
  sjb/generated/test_pull_request_ovn_kubernetes_rhel.xml
Labels: size/M

#1569 Crio jq + docker
  sjb/config/common/test_cases/crio.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
  sjb/generated/test_pull_request_ovn_kubernetes_rhel.xml
Labels: lgtm, size/L
