Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-10, with the labels that each got.

#1597 add 4.0 choice to jenkins version job
  jobs/devex/jenkins-bump-version/Jenkinsfile
Labels: lgtm, size/XS

#1598 Use correct team email for auth extended tests
  sjb/config/test_cases/test_branch_origin_extended_gssapi.yml
  sjb/config/test_cases/test_branch_origin_extended_gssapi_310.yml
  sjb/config/test_cases/test_branch_origin_extended_ldap_groups.yml
  sjb/config/test_cases/test_branch_origin_extended_ldap_groups_310.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_310.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file_310.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file_310.xml
  sjb/generated/test_branch_origin_extended_gssapi.xml
  sjb/generated/test_branch_origin_extended_gssapi_310.xml
  sjb/generated/test_branch_origin_extended_ldap_groups.xml
  sjb/generated/test_branch_origin_extended_ldap_groups_310.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_310.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_310.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_310.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
Labels: size/M

#1601 allow merging of unrelated git histories
  jobs/devex/jenkins-bump-version/bump-jenkins.sh
Labels: size/XS

#1604 move jenkins login plugin PR test off old plugin test to new plugin test
  sjb/config/test_cases/test_branch_jenkins_openshift_login_plugin.yml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
Labels: size/XS

#1603 service-catalog ci for 311 needs to sync origin 311
  sjb/config/test_cases/test_pull_request_openshift_service_catalog_311.yml
  sjb/generated/test_pull_request_openshift_service_catalog_311.xml
Labels: size/XL

#1606 Adding ODCS Mode
  jobs/build/ocp/Jenkinsfile
Labels: size/S

#1609 Always continue on image build fail
  jobs/build/ocp/Jenkinsfile
Labels: size/M

#1610 add jobs to support logging 3.11
  sjb/config/test_cases/test_branch_openshift_ansible_logging_311.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file_311.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_logging_311.yml
  sjb/generated/test_branch_openshift_ansible_logging_311.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file_311.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_311.xml
Labels: size/XXL

#1613 add missing generated json files
  sjb/generated/test_branch_origin_aggregated_logging_json_file_311.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file-release-3.11.xml
Labels: size/XXL

#1614 Refreshing ART scheduled jobs
  scheduled-jobs/build/n-3/Jenkinsfile
  scheduled-jobs/build/n-3/README.md
  scheduled-jobs/build/n-4/Jenkinsfile
  scheduled-jobs/build/n-4/README.md
  scheduled-jobs/build/n-5/Jenkinsfile
  scheduled-jobs/build/n-5/README.md
  scheduled-jobs/build/n-6/Jenkinsfile
  scheduled-jobs/build/n-6/README.md
Labels: size/M

#1612 Enabling periodic pull of docker secret from amis
  jobs/build/ami-updater/roles/registry_credentials_sync/README.md
  jobs/build/ami-updater/roles/registry_credentials_sync/files/ops-registry-secret-sync.service
  jobs/build/ami-updater/roles/registry_credentials_sync/files/ops-registry-secret-sync.sh
  jobs/build/ami-updater/roles/registry_credentials_sync/meta/main.yml
  jobs/build/ami-updater/roles/registry_credentials_sync/tasks/main.yml
  jobs/build/ami-updater/update_base_ami.yml
Labels: size/L

#1600 Add support to convert xml templates to jjb
  alderaan/alderaan-watcher.sh
  alderaan/jjb/dynamic/alderaan-pipeline.yml
  alderaan/pipeline-scripts/conformance.groovy
  alderaan/pipeline-scripts/deployments_per_ns.groovy
  alderaan/pipeline-scripts/logging.groovy
  alderaan/pipeline-scripts/mastervertical.groovy
  alderaan/pipeline-scripts/networking.groovy
  alderaan/pipeline-scripts/nodevertical.groovy
  alderaan/pipeline-scripts/podvertical.groovy
  alderaan/pipeline-scripts/tooling.groovy
  alderaan/property_files/deployments_per_ns.properties
  alderaan/property_files/jobs.properties
  alderaan/property_files/mastervertical.properties
  alderaan/property_files/nodevertical.properties
  alderaan/property_files/ns_per_cluster.properties
  alderaan/property_files/podvertical.properties
  alderaan/property_files/setup_pbench.properties
  alderaan/xml/README.md
Labels: lgtm, size/L

#1595 Allow user to choose the jenkins slave to schedule the job on
  alderaan/Jenkinsfile
  alderaan/pipeline-scripts/browbeat.groovy
  alderaan/pipeline-scripts/conformance.groovy
  alderaan/pipeline-scripts/create_jobs.groovy
  alderaan/pipeline-scripts/deployments_per_ns.groovy
  alderaan/pipeline-scripts/http.groovy
  alderaan/pipeline-scripts/logging.groovy
  alderaan/pipeline-scripts/mastervertical.groovy
  alderaan/pipeline-scripts/mongodbycsb.groovy
  alderaan/pipeline-scripts/networking.groovy
  alderaan/pipeline-scripts/nodevertical.groovy
  alderaan/pipeline-scripts/ns_per_cluster.groovy
  alderaan/pipeline-scripts/openshift.groovy
  alderaan/pipeline-scripts/openstack.groovy
  alderaan/pipeline-scripts/pgbench.groovy
  alderaan/pipeline-scripts/podvertical.groovy
  alderaan/pipeline-scripts/scaleup.groovy
  alderaan/pipeline-scripts/tooling.groovy
Labels: lgtm, size/M

#1616 remove jenkins rhel image generation; defer to upcoming brew/prow
  sjb/config/common/test_cases/rhel_base_images.yml
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/config/test_cases/push_jenkins_images_310.yml
  sjb/config/test_cases/test_branch_jenkins_images.yml
  sjb/config/test_cases/test_branch_jenkins_images_310.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/push_jenkins_images_310.xml
  sjb/generated/test_branch_jenkins_images.xml
  sjb/generated/test_branch_jenkins_images_310.xml
  sjb/generated/test_pull_request_jenkins_images.xml
  sjb/generated/test_pull_request_jenkins_images_310.xml
Labels: size/XXL

#1618 delete stragler jenkins 310 job
  sjb/config/test_cases/test_pull_request_jenkins_images_310.yml
Labels: size/XS

#1619 aws-ami: bumped Jenkins version to 2.6.5
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1620 add extended test jobs for 311
  sjb/config/test_cases/test_branch_origin_extended_builds_311.yml
  sjb/config/test_cases/test_branch_origin_extended_image_ecosystem_311.yml
  sjb/config/test_cases/test_pull_request_origin_extended_builds_311.yaml
  sjb/config/test_cases/test_pull_request_origin_extended_image_ecosystem_311.yaml
  sjb/generated/test_branch_origin_extended_builds_311.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem_311.xml
Labels: size/XXL

#1621 aws_ami: updated volume size
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1622 fix yaml naming and generated proper 311 jobs
  sjb/config/test_cases/test_pull_request_origin_extended_builds_311.yml
  sjb/config/test_cases/test_pull_request_origin_extended_image_ecosystem_311.yml
  sjb/generated/test_pull_request_origin_extended_builds_311.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem_311.xml
Labels: size/XXL

#1624 no longer push jenkins-slave-maven and jenkins-slave-nodejs for v4.0 …
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/generated/push_jenkins_images.xml
Labels: size/M

#1625 ami-updater: added zstream yum repo
  jobs/build/ami-updater/update_base_ami.yml
Labels: size/S

#1627 send email to aos-art-requests on fail
  jobs/build/ocp/Jenkinsfile
  jobs/build/ose/Jenkinsfile
Labels: size/S

#1623 Introduce e2e for libvirt actuator
  sjb/config/test_cases/pull-ci-openshift-cluster-api-provider-libvirt-crd-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-cluster-api-provider-libvirt-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-provider-libvirt-crd-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-api-provider-libvirt-master-e2e.xml
Labels: size/XL

#1628 ART-238 | Always continue on AMI fail
  pipeline-scripts/buildlib.groovy
Labels: size/M

#1632 Use make to build e2e test binary
  sjb/config/test_cases/pull-ci-openshift-cluster-api-provider-libvirt-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-provider-libvirt-master-e2e.xml
Labels: size/XS

#1629 Add console jobs for enterprise-3.9 and enterprise-3.11
  sjb/config/test_cases/test_branch_origin_web_console_311.yml
  sjb/config/test_cases/test_branch_origin_web_console_39.yml
  sjb/generated/test_branch_origin_web_console_311.xml
  sjb/generated/test_branch_origin_web_console_39.xml
Labels: size/XXL

#1633 Removing --metadata-dir
  jobs/build/openshift-online/scripts/merge-and-build-openshift-scripts.sh
  jobs/build/ose/scripts/merge-and-build.sh
  jobs/build/scan-images/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/S
