Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-02, with the labels that each got.

#1104 CRI-O: fix crio version reporting
  sjb/config/test_cases/test_branch_origin_extended_conformance_crio.yml
  sjb/generated/test_branch_origin_extended_conformance_crio.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_crio.xml
  sjb/generated/test_pull_request_origin_extended_conformance_crio.xml
Labels: size/XS

#1111 add hibernation repo to gogitit
  tower-scripts/bin/gogitit_online_int.yml
  tower-scripts/bin/gogitit_online_prod.yml
  tower-scripts/bin/gogitit_online_stg.yml
Labels: size/S

#1110 move oit path to tools/bin
  jobs/build/buildvm-maint/Jenkinsfile
  jobs/build/openshift-online/scripts/merge-and-build-openshift-scripts.sh
  jobs/build/ose/scripts/merge-and-build.sh
  jobs/build/scan-images/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/S

#1112 buildvm-maint: add ose_images to PATH
  jobs/build/buildvm-maint/Jenkinsfile
Labels: size/XS

#1113 aws-ami-building: added some retry logic
  jobs/build/aws-ami/copy_ami_to_regions.yml
Labels: size/XS

#1105 Changing variable used to checking out branch for openshift-ansible
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible_json_file.yml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file.xml
Labels: size/M

#1116 Remove OCP pipeline jenkins source clone
  jobs/build/ocp/Jenkinsfile
  jobs/build/ose/scripts/merge-and-build.sh
  pipeline-scripts/buildlib.groovy
Labels: size/M

#1117 remove jenkins from sources.yml
  pipeline-scripts/buildlib.groovy
Labels: size/XS

#1115 Add images:verify to refresh-images pipeline
  jobs/build/refresh-images/Jenkinsfile
Labels: size/S

#1118 Fixing docker storage path.
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1123 Correct values for YUM_BASE_URL
  jobs/build/ocp/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/S

#1125 Build SRPMS for release work
  sjb/config/common/test_cases/origin_release_install_gce.yml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha.xml
  sjb/generated/test_pull_request_openshift_ansible_launch_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_origin_launch_gce.xml
Labels: size/S

#1106 force logging tag to latest for master branch; fix es5.x branch lookup
  sjb/config/test_cases/test_branch_openshift_ansible_logging.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible_json_file.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file.xml
Labels: size/L

#1126 Support using clonerefs and initupload for sync
  sjb/actions/clonerefs.py
  sjb/generate.py
  sjb/syntax.md
Labels: size/L

#1127 added docker options to aws ami builder
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1128 build/ocp: add a parameter to skip AMI build
  jobs/build/ocp/Jenkinsfile
Labels: size/XS

#1131 Correct repo url / disable ami builds
  jobs/build/ocp/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
Labels: size/M

#1130 Update image inspector jobs
  sjb/config/test_cases/merge_pull_request_image_inspecgtor_images.yml
  sjb/config/test_cases/push_image_inspector_images.yml
  sjb/config/test_cases/test_branch_image_inspector_images.yml
  sjb/config/test_cases/test_pull_request_image_inspector_images.yml
  sjb/generated/merge_pull_request_image_inspecgtor_images.xml
  sjb/generated/push_image_inspector_images.xml
  sjb/generated/test_branch_image_inspector_images.xml
  sjb/generated/test_pull_request_image_inspector_images.xml
Labels: lgtm, size/XL

#1121 Add openshift_image_tag and openshift_release to crio jobs
  sjb/config/test_cases/test_branch_origin_extended_conformance_crio.yml
  sjb/generated/test_branch_origin_extended_conformance_crio.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_crio.xml
  sjb/generated/test_pull_request_origin_extended_conformance_crio.xml
Labels: lgtm, size/M

#1132 add copy tags to aws ami build job
  jobs/build/aws-ami/Jenkinsfile
Labels: lgtm, size/XS

#1134 Ensure GCP tests capture json_file container logs
  sjb/config/common/test_cases/origin_release_install_gce.yml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha.xml
  sjb/generated/test_pull_request_openshift_ansible_launch_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_origin_launch_gce.xml
Labels: size/M

#1135 Fix broken imports in GCS finished script
  sjb/gcs/finished.py
Labels: size/XS

#1140 added the base_ami aws tag
  jobs/build/ami-updater/update_base_ami.yml
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1138 Move the unit test over to clonerefs
  sjb/config/test_cases/test_branch_origin_unit.yml
  sjb/config/test_cases/test_pull_request_origin_unit.yml
  sjb/generated/test_branch_origin_unit.xml
  sjb/generated/test_pull_request_origin_unit.xml
Labels: size/L, ¯\_(ツ)_/¯

#1142 Add ansible-2.4 to reposync
  build-scripts/rcm-guest/rhel7next.sh
  build-scripts/repo-conf/aos-signed-building-betatest.repo
  build-scripts/repo-conf/aos-signed-building.repo
  build-scripts/repo-conf/aos-unsigned-building.repo
  build-scripts/repo-conf/aos-unsigned-errata-building.repo
Labels: size/M

#1144 online repo now uses 'stg' branch instead of 'stage'
  jobs/build/openshift-online/scripts/merge-and-build-openshift-scripts.sh
Labels: size/XS

#1139 create a temp kubeconfig for use with service catalog e2e test
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/config/test_cases/test_pull_request_origin_service_catalog.yml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_pull_request_origin_service_catalog.xml
Labels: size/S

#1149 Update `sync` field doc and fix the Jinja for it
  sjb/actions/clonerefs.py
  sjb/syntax.md
Labels: size/XS

#1151 Add retries to the push script
  sjb/push-update.sh
Labels: size/M

#1147 Re-Add branch specific evars
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/config/common/test_cases/origin_installed_release.yml
  sjb/config/common/test_cases/origin_release_install_gce.yml
  sjb/generated/merge_pull_request_jenkins_client_plugin.xml
  sjb/generated/merge_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/merge_pull_request_jenkins_plugin.xml
  sjb/generated/merge_pull_request_jenkins_sync_plugin.xml
  sjb/generated/test_branch_jenkins_client_plugin.xml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_branch_jenkins_plugin.xml
  sjb/generated/test_branch_jenkins_sync_plugin.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_conformance_gce.xml
  sjb/generated/test_branch_origin_extended_conformance_k8s.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_jenkins_client_plugin.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_plugin.xml
  sjb/generated/test_pull_request_jenkins_sync_plugin.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_gce_ha.xml
  sjb/generated/test_pull_request_openshift_ansible_launch_gce.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_conformance_gce.xml
  sjb/generated/test_pull_request_origin_extended_conformance_k8s.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_origin_launch_gce.xml
  sjb/inventory/base.cfg
  sjb/inventory/master.cfg
Labels: size/L

#1153 Prefer sync block if present
  sjb/generate.py
Labels: size/XS

#1154 Move Origin CMD test to clonerefs
  sjb/config/test_cases/test_branch_origin_cmd.yml
  sjb/config/test_cases/test_pull_request_origin_cmd.yml
  sjb/generate.py
  sjb/generated/test_branch_origin_cmd.xml
  sjb/generated/test_pull_request_origin_cmd.xml
Labels: size/L

#1156 added perf testing aws account to the list of shared ami's
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1143 Move more jobs to clonerefs
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/config/common/test_cases/origin_release.yml
  sjb/config/common/test_cases/origin_release_with_ecosystem.yml
  sjb/config/test_cases/push_origin_release.yml
  sjb/config/test_cases/test_branch_origin_end_to_end.yml
  sjb/config/test_cases/test_branch_origin_extended.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance.yml
  sjb/config/test_cases/test_pull_request_origin_end_to_end.yml
  sjb/config/test_cases/test_pull_request_origin_extended.yml
  sjb/config/test_cases/test_pull_request_origin_extended_builds.yml
  sjb/config/test_cases/test_pull_request_origin_extended_clusterup.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance.yml
  sjb/config/test_cases/test_pull_request_origin_extended_image_ecosystem.yml
  sjb/config/test_cases/test_pull_request_origin_extended_image_registry.yml
  sjb/config/test_cases/test_pull_request_origin_extended_ldap_groups.yml
  sjb/config/test_cases/test_pull_request_origin_extended_networking.yml
  sjb/config/test_cases/test_pull_request_origin_extended_networking_minimal.yml
  sjb/config/test_suites/test_branch_origin.yml
  sjb/generated/push_origin_release.xml
  sjb/generated/test_branch_origin.xml
  sjb/generated/test_branch_origin_end_to_end.xml
  sjb/generated/test_branch_origin_extended.xml
  sjb/generated/test_branch_origin_extended_conformance.xml
  sjb/generated/test_branch_origin_extended_networking.xml
  sjb/generated/test_branch_origin_extended_networking_minimal.xml
  sjb/generated/test_pull_request_origin_end_to_end.xml
  sjb/generated/test_pull_request_origin_extended.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_clusterup.xml
  sjb/generated/test_pull_request_origin_extended_conformance.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_origin_extended_ldap_groups.xml
  sjb/generated/test_pull_request_origin_extended_networking.xml
  sjb/generated/test_pull_request_origin_extended_networking_minimal.xml
  sjb/prune.sh
Labels: size/XXL

#1157 Uncommented the CI message capabilities for OSO starter upgrades.
  jobs/starter/upgrade/Jenkinsfile
Labels: size/XS

#1155 create logging jobs to sync proper release versions
  sjb/config/test_cases/test_pull_request_openshift_ansible_logging_36.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_logging_37.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible_36.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible_37.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible_json_file_36.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible_json_file_37.yml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_37.xml
Labels: size/XXL

#1158 Allow for manual args to be passed to clonerefs
  sjb/actions/clonerefs.py
  sjb/generated/merge_pull_request_origin.xml
  sjb/generated/push_origin_release.xml
  sjb/generated/test_branch_origin_cmd.xml
  sjb/generated/test_branch_origin_end_to_end.xml
  sjb/generated/test_branch_origin_extended_networking.xml
  sjb/generated/test_branch_origin_extended_networking_minimal.xml
  sjb/generated/test_branch_origin_unit.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_origin.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_37.xml
  sjb/generated/test_pull_request_origin_cmd.xml
  sjb/generated/test_pull_request_origin_end_to_end.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_clusterup.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_origin_extended_ldap_groups.xml
  sjb/generated/test_pull_request_origin_extended_networking.xml
  sjb/generated/test_pull_request_origin_extended_networking_minimal.xml
  sjb/generated/test_pull_request_origin_unit.xml
Labels: size/L

#1164 Always push artifacts using BUILD in crio jobs
  sjb/config/common/test_cases/crio.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
Labels: size/S

#1166 Adding merge to web console for release-cut
  build-scripts/release-cut/merge-web-console.sh
Labels: size/M

#1167 aws ami: added some notes about perf account
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1162 Upload latest-build.txt for kubernetes conformance jobs
  sjb/config/common/test_cases/crio.yml
  sjb/config/common/test_cases/kubernetes.yml
  sjb/config/common/test_cases/origin.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/ci-kubernetes-conformance-node-e2e-containerized-rhel.xml
  sjb/generated/ci-kubernetes-conformance-node-e2e-rhel.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_clusterup.xml
  sjb/generated/test_branch_origin_extended_gssapi.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_branch_origin_extended_ldap_groups.xml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
Labels: size/L

#1168 Run clonerefs as the test user
  sjb/actions/clonerefs.py
  sjb/generated/push_origin_release.xml
  sjb/generated/test_branch_origin_cmd.xml
  sjb/generated/test_branch_origin_end_to_end.xml
  sjb/generated/test_branch_origin_extended_networking.xml
  sjb/generated/test_branch_origin_extended_networking_minimal.xml
  sjb/generated/test_branch_origin_unit.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file_37.xml
  sjb/generated/test_pull_request_origin_cmd.xml
  sjb/generated/test_pull_request_origin_end_to_end.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_clusterup.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_origin_extended_ldap_groups.xml
  sjb/generated/test_pull_request_origin_extended_networking.xml
  sjb/generated/test_pull_request_origin_extended_networking_minimal.xml
  sjb/generated/test_pull_request_origin_unit.xml
Labels: size/M
