Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-06, with the labels that each got.

#1429 Updating logging component images used
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
Labels: lgtm, size/S

#1432 Updating evars for missed logging job
  sjb/config/test_cases/test_branch_openshift_ansible_logging.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
Labels: lgtm, size/S

#1433 add push for wildfly v13
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/generated/push_wildfly_images.xml
Labels: size/XS

#1435 Add node logs to resultant tgz
  tower-scripts/bin/gather-logs.py
Labels: size/XS

#1335 analyze-upgrade-log enhancements
  tower-scripts/bin/analyze-upgrade-log
Labels: size/L

#1430 reformat parameter list in ocp jenkinsfile
  jobs/build/make-puddle/Jenkinsfile
  jobs/build/ocp/Jenkinsfile
  jobs/build/openshift-online/Jenkinsfile
  jobs/build/ose/Jenkinsfile
  jobs/build/scan-images/Jenkinsfile
Labels: size/L

#1440 Update sjb inventory for openshift_node_group_name
  sjb/inventory/group_vars/OSEv3/general.yml
  sjb/inventory/host_vars/localhost.yml
Labels: size/XS

#1439 Build Origin with Service Catalog for Install Origin Builds
  sjb/config/common/test_cases/origin_installed_release.yml
  sjb/generated/test_branch_jenkins_client_plugin.xml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_branch_jenkins_plugin.xml
  sjb/generated/test_branch_jenkins_sync_plugin.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_jenkins_client_plugin.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_plugin.xml
  sjb/generated/test_pull_request_jenkins_sync_plugin.xml
Labels: size/XXL

#1443 build doesnt need sources since theyre RPMs
  jobs/build/ose/scripts/merge-and-build.sh
Labels: size/XS

#1444 Updated infra selector to new format
  sjb/inventory/group_vars/OSEv3/general.yml
  sjb/inventory/host_vars/localhost.yml
Labels: size/XS

#1447 Revert ose openshift ansible rpm
  jobs/build/ose/Jenkinsfile
  jobs/build/ose/scripts/merge-and-build.sh
Labels: size/M

#1452 options in parameters are newline separated, not comma
  jobs/build/ocp/Jenkinsfile
Labels: size/XS

#1448 Add temporary call to openshift_node_groups in gce_upgrade job
  sjb/config/common/test_cases/origin_release_install_upgrade_gce.yml
  sjb/generated/test_pull_request_openshift_ansible_install_upgrade_gce.xml
Labels: size/S

#1437 Azure: Sync with changes from openshift-ansible for azure
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/config/test_cases/azure_build_base_image_centos.yml
  sjb/config/test_cases/azure_build_base_image_rhel.yml
  sjb/config/test_cases/azure_build_node_image_centos.yml
  sjb/config/test_cases/azure_build_node_image_centos_39.yml
  sjb/config/test_cases/azure_build_node_image_rhel_39.yml
  sjb/generated/azure_build_base_image_centos.xml
  sjb/generated/azure_build_base_image_rhel.xml
  sjb/generated/azure_build_node_image_centos.xml
  sjb/generated/azure_build_node_image_centos_39.xml
  sjb/generated/azure_build_node_image_rhel_39.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: lgtm, size/L

#1454 online-* operations can be run on any env
  tower-scripts/bin/cicd-control.sh
Labels: size/XS

#1455 Fixing parameter reorg from #1414
  jobs/build/buildvm-maint/Jenkinsfile
Labels: size/XS

#1457 Replace None with null in OCP
  jobs/build/ocp/Jenkinsfile
Labels: size/XS

#1456 Run extended tests with origin built installed release
  sjb/config/common/test_cases/origin_installed_release.yml
  sjb/config/test_cases/test_branch_jenkins_client_plugin.yml
  sjb/config/test_cases/test_branch_jenkins_openshift_login_plugin.yml
  sjb/config/test_cases/test_branch_jenkins_plugin.yml
  sjb/config/test_cases/test_branch_jenkins_sync_plugin.yml
  sjb/config/test_cases/test_branch_origin_extended_builds.yml
  sjb/config/test_cases/test_branch_origin_extended_image_ecosystem.yml
  sjb/config/test_cases/test_branch_origin_extended_image_registry.yml
  sjb/generated/test_branch_jenkins_client_plugin.xml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_branch_jenkins_plugin.xml
  sjb/generated/test_branch_jenkins_sync_plugin.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_jenkins_client_plugin.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_plugin.xml
  sjb/generated/test_pull_request_jenkins_sync_plugin.xml
Labels: size/XL

#1459 Pass buildlib into mail_success and get_rpm_changelog
  jobs/build/ocp/Jenkinsfile
Labels: size/XS

#1463 Quote label value so it's not interpretted as a boolean
  sjb/inventory/host_vars/localhost.yml
Labels: size/XS

#1464 Add Tim, remove Bruno from build related emails
  Jenkinsfile
  jobs/build/aws-ami/Jenkinsfile
  jobs/build/ocp/Jenkinsfile
  jobs/build/openshift-online/Jenkinsfile
  jobs/build/ose/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
Labels: size/S

#1434 catalog: specify version to execute
  sjb/config/test_cases/test_pull_request_origin_service_catalog_39.yml
  sjb/generated/test_pull_request_origin_service_catalog_39.xml
Labels: size/XS

#1466 azure: hold environments for debug
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_310.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: size/L

#1468 Pull correct branch for 3.10 azure jobs
  sjb/config/common/test_cases/origin_release_install_azure_310.yml
  sjb/generated/test_branch_origin_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_310.xml
Labels: sig/azure, size/XS

#1453 Avoid unnecessary builds in azure jobs
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_310.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: sig/azure, size/L

#1469 remove azure_build_base_image_centos_310 and azure_build_base_image_r…
  sjb/config/test_cases/azure_build_base_image_centos_310.yml
  sjb/config/test_cases/azure_build_base_image_rhel_310.yml
  sjb/generated/azure_build_base_image_centos_310.xml
  sjb/generated/azure_build_base_image_rhel_310.xml
Labels: lgtm, size/XL

#1415 Enable acs-engine e2e tests during azure ci jobs
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_310.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/config/test_cases/azure_build_node_image_centos.yml
  sjb/config/test_cases/azure_build_node_image_centos_310.yml
  sjb/config/test_cases/azure_build_node_image_centos_39.yml
  sjb/config/test_cases/azure_build_node_image_rhel_310.yml
  sjb/config/test_cases/azure_build_node_image_rhel_39.yml
  sjb/generated/azure_build_node_image_centos.xml
  sjb/generated/azure_build_node_image_centos_310.xml
  sjb/generated/azure_build_node_image_centos_39.xml
  sjb/generated/azure_build_node_image_rhel_310.xml
  sjb/generated/azure_build_node_image_rhel_39.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: size/XL

#1460 moved changelog extraction up a couple of levels
  jobs/build/ocp/Jenkinsfile
Labels: size/S

#1473 made name of oa_specfile variable consistent
  jobs/build/ocp/Jenkinsfile
Labels: size/XS

#1474 ensure origin code is synced before building+running tests
  sjb/config/test_cases/test_branch_jenkins_openshift_login_plugin.yml
  sjb/config/test_cases/test_branch_jenkins_plugin.yml
  sjb/config/test_cases/test_branch_jenkins_sync_plugin.yml
  sjb/config/test_cases/test_branch_origin_extended_builds.yml
  sjb/config/test_cases/test_branch_origin_extended_builds_310.yml
  sjb/config/test_cases/test_branch_origin_extended_image_ecosystem.yml
  sjb/config/test_cases/test_branch_origin_extended_image_ecosystem_310.yml
  sjb/config/test_cases/test_branch_origin_extended_image_registry.yml
  sjb/config/test_cases/test_branch_origin_extended_image_registry_310.yml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_branch_jenkins_plugin.xml
  sjb/generated/test_branch_jenkins_sync_plugin.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_builds_310.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem_310.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_branch_origin_extended_image_registry_310.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_plugin.xml
  sjb/generated/test_pull_request_jenkins_sync_plugin.xml
Labels: size/M

#1475 Add ansible-2.6 repos
  build-scripts/rcm-guest/rhel7next.sh
  build-scripts/repo-conf/aos-signed-building-betatest.repo
  build-scripts/repo-conf/aos-signed-building.repo
  build-scripts/repo-conf/aos-unsigned-building.repo
  build-scripts/repo-conf/aos-unsigned-errata-building.repo
Labels: size/M

#1476 3.10 job should be using 3.10 ansible image
  sjb/config/common/test_cases/origin_release_install_gce_310.yml
  sjb/generated/test_branch_origin_extended_conformance_gce_310.xml
  sjb/generated/test_branch_origin_extended_conformance_k8s_310.xml
  sjb/generated/test_pull_request_openshift_ansible_launch_gce_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_k8s_310.xml
  sjb/generated/test_pull_request_origin_launch_gce_310.xml
Labels: size/M

#1478 re indent jobs
  jobs/build/ocp/Jenkinsfile
Labels: size/L

#1479 added markllama git and keys to choices
  jobs/build/ocp/Jenkinsfile
Labels: size/XS

#1481 disable authentication for side effects during testing
  jobs/build/ocp/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/S

#1482 Adding pre-release scheduled job
  scheduled-jobs/build/ocp-pre-release/Jenkinsfile
  scheduled-jobs/build/ocp-pre-release/README.md
Labels: size/S

#1484 Make sure gogitit is run before gluster-deployer
  tower-scripts/bin/cicd-control.py
Labels: size/XS

#1485 Reorder stages
  jobs/build/ocp/Jenkinsfile
Labels: size/L

#1480 [WIP] Adding tests for openshift-ansible branch and pr.
  sjb/config/test_cases/test_branch_openshift_ansible_extended_conformance_azure.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_azure.yml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure.xml
Labels: do-not-merge/work-in-progress, lgtm, size/XXL

#1487 Adding 3.10 openshift-ansible azure tests.
  sjb/config/test_cases/test_branch_openshift_ansible_extended_conformance_azure_310.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_azure_310.yml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure_310.xml
Labels: size/XXL

#1488 updated to use m5.xlarge
  jobs/build/ami-updater/update_base_ami.yml
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1489 Fixing 310 image build rpm URL.
  sjb/config/test_cases/azure_build_node_image_centos_310.yml
  sjb/generated/azure_build_node_image_centos_310.xml
Labels: size/XS

#1490 Updating input image name to 3.10 on 3.10 branch.
  sjb/config/test_cases/azure_build_node_image_centos_310.yml
  sjb/generated/azure_build_node_image_centos_310.xml
Labels: size/XS

#1492 Updating vm size for jobs. Placing e2e tests on deployed clusters.
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_310.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/config/test_cases/azure_build_base_image_centos.yml
  sjb/config/test_cases/azure_build_base_image_rhel.yml
  sjb/config/test_cases/azure_build_node_image_centos.yml
  sjb/config/test_cases/azure_build_node_image_centos_310.yml
  sjb/config/test_cases/azure_build_node_image_centos_39.yml
  sjb/config/test_cases/azure_build_node_image_rhel_310.yml
  sjb/config/test_cases/azure_build_node_image_rhel_39.yml
  sjb/generated/azure_build_base_image_centos.xml
  sjb/generated/azure_build_base_image_rhel.xml
  sjb/generated/azure_build_node_image_centos.xml
  sjb/generated/azure_build_node_image_centos_310.xml
  sjb/generated/azure_build_node_image_centos_39.xml
  sjb/generated/azure_build_node_image_rhel_310.xml
  sjb/generated/azure_build_node_image_rhel_39.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: lgtm, size/L

#1494 Fowarding azure_vm_size.
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_310.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: lgtm, size/S

#1495 Fix openshift-ansible repo sync for azure jobs
  sjb/config/test_cases/test_branch_openshift_ansible_extended_conformance_azure.yml
  sjb/config/test_cases/test_branch_openshift_ansible_extended_conformance_azure_310.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_azure.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_azure_310.yml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure_310.xml
Labels: sig/azure, size/M

#1497 Copying artifacts from launch so that we can run e2e tests on same cluster.
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_310.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: lgtm, size/M

#1496 Use updated acs-engine-tests images in azure jobs
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_310.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/config/test_cases/azure_build_node_image_centos.yml
  sjb/config/test_cases/azure_build_node_image_centos_310.yml
  sjb/config/test_cases/azure_build_node_image_centos_39.yml
  sjb/config/test_cases/azure_build_node_image_rhel_310.yml
  sjb/config/test_cases/azure_build_node_image_rhel_39.yml
  sjb/generated/azure_build_node_image_centos.xml
  sjb/generated/azure_build_node_image_centos_310.xml
  sjb/generated/azure_build_node_image_centos_39.xml
  sjb/generated/azure_build_node_image_rhel_310.xml
  sjb/generated/azure_build_node_image_rhel_39.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: lgtm, sig/azure, size/M

#1498 Persist azure launch artifacts.
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_310.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_branch_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_310.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_310.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: lgtm, size/M

#1493 Return `openshift-ansible` changelog to ocp success email
  jobs/build/ocp/Jenkinsfile
Labels: size/M

#1500 Add functions to compare and sort version strings, and to select "build mode" automatically
  pipeline-scripts/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/buildlib_test.groovy
Labels: size/XL
