Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-09, with the labels that each got.

#1572 add wf14 tag+push
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/generated/push_wildfly_images.xml
Labels: size/S

#1570 Ensure cockpit image is set correctly
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_branch_jenkins_client_plugin.xml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_branch_jenkins_plugin.xml
  sjb/generated/test_branch_jenkins_sync_plugin.xml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
  sjb/generated/test_pull_request_jenkins_client_plugin.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_plugin.xml
  sjb/generated/test_pull_request_jenkins_sync_plugin.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install_39.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
  sjb/inventory/group_vars/OSEv3/general.yml
Labels: lgtm, size/L

#1571 CRI-O: forward BUILD_NUMBER
  sjb/config/common/test_cases/crio.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
  sjb/generated/test_pull_request_ovn_kubernetes_rhel.xml
Labels: size/S

#1574 Remove sjb extra_var openshift_cockpit_deployer_image
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_branch_jenkins_client_plugin.xml
  sjb/generated/test_branch_jenkins_openshift_login_plugin.xml
  sjb/generated/test_branch_jenkins_plugin.xml
  sjb/generated/test_branch_jenkins_sync_plugin.xml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_extended_builds.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_branch_origin_extended_image_ecosystem.xml
  sjb/generated/test_branch_origin_extended_image_registry.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
  sjb/generated/test_pull_request_jenkins_client_plugin.xml
  sjb/generated/test_pull_request_jenkins_openshift_login_plugin.xml
  sjb/generated/test_pull_request_jenkins_plugin.xml
  sjb/generated/test_pull_request_jenkins_sync_plugin.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install_39.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
Labels: size/L

#1575 only specify to sync openshift/origin for openshift/service-catalog prs
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/config/test_cases/test_branch_origin_service_catalog_310.yml
  sjb/config/test_cases/test_pull_request_openshift_service_catalog.yml
  sjb/config/test_cases/test_pull_request_openshift_service_catalog_310.yml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_branch_origin_service_catalog_310.xml
  sjb/generated/test_pull_request_openshift_service_catalog.xml
  sjb/generated/test_pull_request_origin_service_catalog.xml
  sjb/generated/test_pull_request_origin_service_catalog_310.xml
Labels: size/M

#1576 aws-ami: added option to not setup grpquota on root
  jobs/build/aws-ami/Jenkinsfile
Labels: size/XS

#1577 Fixup cri-o repository path to new kubernetes-sigs organization
  sjb/config/common/test_cases/crio.yml
  sjb/config/test_cases/ami_build_origin_int_rhel_crio.yml
  sjb/config/test_cases/test_branch_crio_e2e_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_ami_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_critest_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_e2e_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_integration_rhel.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
Labels: size/L

#1580 Cluster operator: Use 3.10 oc binary to start cluster up
  sjb/config/test_cases/test_branch_cluster_operator_e2e.yml
  sjb/generated/test_branch_cluster_operator_e2e.xml
  sjb/generated/test_pull_request_cluster_operator_e2e.xml
Labels: size/M

#1581 Fixup checkout directory for CRI-O
  sjb/config/test_cases/ami_build_origin_int_rhel_crio.yml
  sjb/config/test_cases/test_pull_request_crio_ami_rhel.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_origin_device_manager_plugin_gpu.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
Labels: size/M

#1583 Allow overrides for dedicated clusters
  jobs/starter/package-overrides/Jenkinsfile
  jobs/starter/package-overrides/scripts/update-cluster-overrides.sh
Labels: size/M

#1584 Adding 4.0 series options
  jobs/devex/jenkins-plugins/Jenkinsfile
Labels: size/S

#1578 add art libraries to manage Git repos, RPMs and versions in Jenkins jobs
  src/com/redhat/art/GitHubRepository.groovy
  src/com/redhat/art/Rpm.groovy
  src/com/redhat/art/RpmSpec.groovy
  src/com/redhat/art/Version.groovy
  src/com/redhat/art/VersionTest.groovy
Labels: size/XL

#1586 Run the mongodb ycsb jenkins job
  alderaan/Jenkinsfile
Labels: needs-ok-to-test, size/XS

#1589 use mailing lists instead of individuals
  jobs/build/ocp/Jenkinsfile
Labels: lgtm, size/S

#1590 add 3.11 e2e job
  sjb/config/test_cases/test_branch_origin_end_to_end_311.yml
  sjb/config/test_cases/test_pull_request_origin_end_to_end_311.yml
  sjb/generated/test_branch_origin_end_to_end_311.xml
  sjb/generated/test_pull_request_origin_end_to_end_311.xml
Labels: size/XXL

#1585 CRI-O: flatten artifacts for k8s gubernator
  sjb/config/common/test_cases/crio.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
Labels: size/M

#1591 Use terraform to provision resources
  sjb/config/test_cases/ci-kubernetes-aws-actuator.yml
  sjb/generated/ci-kubernetes-aws-actuator.xml
Labels: size/L

#1588 machine-api-operator: install tf and aws, create named resources
  sjb/config/test_cases/ci-kubernetes-machine-api-operator.yml
  sjb/generated/ci-kubernetes-machine-api-operator.xml
Labels: size/M

#1592 Make build machine api operator instead of go build
  sjb/config/test_cases/ci-kubernetes-machine-api-operator.yml
  sjb/generated/ci-kubernetes-machine-api-operator.xml
Labels: size/XS

#1593 Build AMI with playbooks from same release
  jobs/build/aws-ami/Jenkinsfile
Labels: size/S

#1594 Setting openshift_logging_install_eventrouter=True in 3.9 and above.
  sjb/config/test_cases/test_branch_openshift_ansible_logging.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_310.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file_310.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald_310.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_310.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file_310.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file_310.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_310.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_310.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_310.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
Labels: lgtm, size/M
