Repository openshift-eng/aos-cd-jobs, pull requests merged in 2018-04, with the labels that each got.

#1194 Add rpm based CRIO CI job
  sjb/config/test_cases/test_branch_origin_extended_conformance_crio_rpm.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_crio_rpm.yml
  sjb/generated/test_branch_origin_extended_conformance_crio_rpm.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_crio_rpm.xml
Labels: size/XXL

#1275 Introduce PR-based CI for openshift/descheduler repository
  sjb/config/common/test_cases/origin_release_install_descheduler_gce_39.yml
  sjb/config/test_cases/test_branch_origin_descheduler_gce_39.yml
  sjb/generated/test_branch_origin_descheduler_gce_39.xml
Labels: size/XXL

#1288 added cicd-control.py
  tower-scripts/bin/cicd-control.py
  tower-scripts/bin/ops_bin
Labels: size/L

#1289 fixed a few lingering test hacks
  tower-scripts/bin/cicd-control.py
Labels: size/XS

#1276 Handle syntax differences for "oc cluster up"
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/config/test_cases/test_pull_request_origin_service_catalog.yml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_pull_request_origin_service_catalog.xml
Labels: size/S

#1291 need to actually update ops git repos
  tower-scripts/bin/cicd-control.py
Labels: size/XS

#1292 cicd-control.py: setting paths correctly
  tower-scripts/bin/cicd-control.py
Labels: size/XS

#1295 cicd-control.py: reduced keep alive to 600 seconds
  tower-scripts/bin/cicd-control.py
Labels: size/XS

#1296 use debug_level=2 for logging CI to reduce flakes
  sjb/config/test_cases/test_branch_openshift_ansible_logging.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald_36.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_json_file_36.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
Labels: lgtm, size/M

#1300 Rename descheduler test_branch to test_pull_request
  sjb/config/test_cases/test_pull_request_descheduler_gce_39.yml
  sjb/generated/test_pull_request_descheduler_gce_39.xml
Labels: size/XS

#1293 Azure image build job
  sjb/config/test_cases/azure_build_node_image_rhel.yml
  sjb/generated/azure_build_node_image_rhel.xml
Labels: lgtm, size/L

#1298 Azure base image build job
  sjb/config/test_cases/azure_build_base_image_rhel.yml
  sjb/generated/azure_build_base_image_rhel.xml
Labels: lgtm, size/L

#1303 Build in LDAP periodic, dont build extended.test
  sjb/config/test_cases/test_branch_origin_extended_ldap_groups.yml
  sjb/config/test_cases/test_pull_request_origin_extended_ldap_groups.yml
  sjb/generated/test_branch_origin_extended_ldap_groups.xml
  sjb/generated/test_pull_request_origin_extended_ldap_groups.xml
Labels: size/M

#1299 Set openshift_image_tag explicitely
  jobs/package-dockertested/install-origin-release.sh
  sjb/config/common/test_cases/origin_built_installed_release_39.yml
  sjb/generated/test_branch_origin_extended_conformance_install_39.xml
Labels: size/XS

#1294 Azure pr testing job for 3.9
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_azure_39.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_azure_39.yml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: size/XXL

#1301 Azure pr testing job for master
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/test_cases/test_branch_origin_extended_conformance_azure.yml
  sjb/config/test_cases/test_pull_request_origin_extended_conformance_azure.yml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
Labels: size/XXL

#1304 Remove enable-statuspage and disable-statuspage operations
  jobs/starter/operation/Jenkinsfile
  jobs/starter/upgrade/Jenkinsfile
Labels: size/XS

#1282 Add CI jobs for catalog in openshift repo
  sjb/config/test_cases/test_branch_origin_service_catalog.yml
  sjb/config/test_cases/test_pull_request_origin_service_catalog.yml
  sjb/generated/test_branch_origin_service_catalog.xml
  sjb/generated/test_pull_request_origin_service_catalog.xml
Labels: size/XL

#1307 Azure: resource group name too long
  sjb/config/common/test_cases/origin_release_install_azure.yml
  sjb/config/common/test_cases/origin_release_install_azure_39.yml
  sjb/config/test_cases/azure_build_node_image_rhel.yml
  sjb/generated/azure_build_node_image_rhel.xml
  sjb/generated/test_branch_origin_extended_conformance_azure.xml
  sjb/generated/test_branch_origin_extended_conformance_azure_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure.xml
  sjb/generated/test_pull_request_origin_extended_conformance_azure_39.xml
Labels: size/M

#1312 catalog: add CI jobs for openshift/service-catalog
  sjb/config/test_cases/test_pull_request_openshift_service_catalog.yml
  sjb/generated/test_pull_request_openshift_service_catalog.xml
Labels: size/XL

#1311 Adds correct testing for catalog and origin 3.9
  sjb/config/test_cases/test_pull_request_origin_service_catalog_39.yml
  sjb/generated/test_pull_request_origin_service_catalog_39.xml
Labels: size/XL

#1284 Add new catalog repo to release push script
  sjb/config/test_cases/push_origin_release.yml
Labels: size/XS

#1315 Azure centos node image build job
  sjb/config/test_cases/azure_build_node_image_centos.yml
  sjb/generated/azure_build_node_image_centos.xml
Labels: size/L

#1314 Add Azure centos base image build job
  sjb/config/test_cases/azure_build_base_image_centos.yml
  sjb/generated/azure_build_base_image_centos.xml
Labels: size/L

#1318 Retry mirror pushes
  build-scripts/rcm-guest/push-to-mirrors.sh
Labels: size/XS

#1321 logging - push es5 image
  sjb/config/test_cases/push_origin_aggregated_logging_release.yml
  sjb/generated/push_origin_aggregated_logging_release.xml
Labels: size/XS

#1324 Add analyze-upgrade-log
  tower-scripts/bin/analyze-upgrade-log
Labels: size/M

#1323 Fix output_format when evars is set
  sjb/actions/clonerefs.py
  sjb/actions/evars.py
  sjb/actions/script.py
  sjb/generate.py
Labels: size/S

#1326 release-3.9: tag origin image with v3.9.x
  Dockerfile
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/generated/test_branch_image_registry_extended.xml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_image_registry_extended.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
  sjb/generated/test_pull_request_origin_extended_builds.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install_39.xml
  sjb/generated/test_pull_request_origin_extended_image_ecosystem.xml
  sjb/generated/test_pull_request_origin_extended_image_registry.xml
Labels: size/L
