Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-03, with the labels that each got.

#1719 Run the mao JJ over ginkgo test suite
  sjb/config/test_cases/pull-ci-openshift-machine-api-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-machine-api-operator-master-e2e.xml
Labels: size/XL

#1723 CAO: use official mao image to deploy kubemark
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
Labels: size/S

#1720 commonlib: separate major versions
  jobs/build/custom/Jenkinsfile
  jobs/build/incremental/Jenkinsfile
  jobs/build/ocp/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
  jobs/build/reposync/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: size/M

#1722 logging - use ansible vars.yaml files for branch specific params
  sjb/config/test_cases/test_pull_request_openshift_ansible_logging_39.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald_39.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_json_file_39.yml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
Labels: size/S

#1721 use commonlib.email to archive and suppress email
  jobs/build/custom/Jenkinsfile
  jobs/build/incremental/Jenkinsfile
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/ocp/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
  jobs/build/reposync/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/L

#1727 force s2i dependent jobs to use golang 1.10
  sjb/config/common/test_cases/s2i.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/push_wildfly_images.xml
  sjb/generated/test_branch_jenkins_images.xml
  sjb/generated/test_branch_wildfly_images.xml
  sjb/generated/test_pull_request_jenkins_images.xml
  sjb/generated/test_pull_request_wildfly_images.xml
Labels: size/XS

#1729 openshift-ansible - use ansible evars vars.yaml for branch specific params
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_release_39.yml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
Labels: lgtm, size/S

#1731 Fix a typo in openshift-origin-common repo excludes
  jjb/playbooks/openshift/roles/setup/templates/openshift-origin-common-repo.j2
Labels: size/XS

#1725 ART-268 email owners when their image build fails
  jobs/build/custom/Jenkinsfile
  jobs/build/incremental/Jenkinsfile
  jobs/build/ocp/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/commonlib.groovy
Labels: size/L

#1732 Add release-3.9 specific ansible config
  sjb/inventory/release-3.9.cfg
Labels: size/XS

#1733 Don't install CentOS Origin repo in 3.9
  sjb/inventory/release-3.9.cfg
Labels: size/XS

#1734 Set openshift_master_node_labels for 3.9 clusters
  sjb/inventory/release-3.9.cfg
Labels: size/XS

#1735 build/ocp(4): fix missing paren
  jobs/build/ocp/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
Labels: lgtm, size/XS

#1737 Remove quotes from evars flag so it is not skipped.
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_extended_builds_311.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_origin_device_manager_plugin_gpu.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install_39.xml
Labels: size/M

#1738 3.10 logging - use ansible vars.yaml files for branch specific params
  sjb/config/test_cases/test_branch_openshift_ansible_logging_310.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file_310.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald_310.yml
  sjb/generated/test_branch_openshift_ansible_logging_310.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file_310.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file_310.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_310.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_310.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_310.xml
Labels: size/S

#1739 Removing old deployment pipelines & cruft
  jobs/dedicated/operation
  jobs/dedicated/upgrade
  jobs/sprint/control/Jenkinsfile
  jobs/sprint/control/emails/devcut_start
  jobs/sprint/control/emails/feature_complete
  jobs/sprint/control/emails/online_first_signup
  jobs/sprint/control/emails/open_master
  jobs/sprint/control/emails/stagecut_start
  jobs/sprint/merge-gating/Jenkinsfile
  jobs/sprint/stage-to-prod/Jenkinsfile
  jobs/sprint/stage-to-prod/README.md
  jobs/sprint/stagecut/Jenkinsfile
  jobs/sprint/stagecut/README.md
  jobs/sprint/stagecut/scripts/stagecut.sh
  jobs/starter/operation/Jenkinsfile
  jobs/starter/operation/README.md
  jobs/starter/package-overrides/Jenkinsfile
  jobs/starter/package-overrides/README.md
  jobs/starter/package-overrides/scripts/update-cluster-overrides.sh
  jobs/starter/perf/Jenkinsfile
  jobs/starter/perf/README.md
  jobs/starter/rotate-log-access-key/Jenkinsfile
  jobs/starter/rotate-log-access-key/README.md
  jobs/starter/smoke-test/Jenkinsfile
  jobs/starter/smoke-test/README.md
  jobs/starter/upgrade/Jenkinsfile
  jobs/starter/upgrade/README.md
  scheduled-jobs/sprint/Jenkinsfile
  tower-scripts/README.md
  tower-scripts/bin/add_ssh_key_to_localhost.yml
  tower-scripts/bin/analyze-upgrade-log
  tower-scripts/bin/aos-cd-cluster-smoke-test.sh
  tower-scripts/bin/aos-cd-cluster-status.sh
  tower-scripts/bin/build-ci-msg.py
  tower-scripts/bin/cicd-control.py
  tower-scripts/bin/cicd-control.sh
  tower-scripts/bin/clone_ops_git_repos.yml
  tower-scripts/bin/disable-docker-timer-hack.sh
  tower-scripts/bin/gather-logs.py
  tower-scripts/bin/gather-logs.sh
  tower-scripts/bin/gogitit_online_int.yml
  tower-scripts/bin/gogitit_online_prod.yml
  tower-scripts/bin/gogitit_online_stg.yml
  tower-scripts/bin/ops-to-productization-inventory.py
  tower-scripts/bin/ops_bin
  tower-scripts/bin/ops_roles
  tower-scripts/bin/private_roles
  tower-scripts/bin/rotate-log-access-key.sh
  tower-scripts/bin/tools_roles
Labels: lgtm, size/XXL

#1741 Revert "Merge pull request #1733 from vrutkovs/3.9-disable-centos-repo"
  sjb/inventory/release-3.9.cfg
Labels: lgtm, size/XS

#1743 Revert "Merge pull request #1729 from patrickdillon/openshift-ansible-39-add-evars"
  sjb/config/test_cases/test_pull_request_openshift_ansible_extended_conformance_install_release_39.yml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
Labels: size/S

#1744 Change release-3.9 inventory label to openshift_node_label.
  sjb/inventory/release-3.9.cfg
Labels: lgtm, size/XS

#1745 Remove verify
  jobs/build/refresh-images/Jenkinsfile
Labels: lgtm, size/S

#1736 Run sync job after full/incremental ocp4 builds
  jobs/build/build-sync/Jenkinsfile
  jobs/build/build-sync/README.md
  jobs/build/incremental/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  scheduled-jobs/build/oc-mirror-quay-dev/Jenkinsfile
Labels: lgtm, size/L

#1746 Remove other quotation marks around evars so flag won't be skipped.
  sjb/config/common/test_cases/origin_built_installed_release.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_extended_builds_311.xml
  sjb/generated/test_branch_origin_extended_conformance_install.xml
  sjb/generated/test_branch_origin_extended_conformance_install_system_containers.xml
  sjb/generated/test_origin_device_manager_plugin_gpu.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_36.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_37.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_system_containers_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install.xml
  sjb/generated/test_pull_request_origin_extended_conformance_install_39.xml
Labels: lgtm, size/M

#1747 Add sync to custom build. Maybe fix missing body?
  jobs/build/build-sync/Jenkinsfile
  jobs/build/custom/Jenkinsfile
Labels: lgtm, size/S

#1748 custom only syncs for 4.x, build-sync updates description of progress
  jobs/build/build-sync/Jenkinsfile
  jobs/build/custom/Jenkinsfile
Labels: lgtm, size/S

#1749 Split on escaped dot
  jobs/build/custom/Jenkinsfile
Labels: lgtm, size/XS

#1750 buildlib: fix build-sync trigger
  jobs/build/build-sync/Jenkinsfile
  jobs/build/custom/Jenkinsfile
  jobs/build/incremental/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: lgtm, size/M

#1751 build/ocp(4) -> consolidate to buildlib
  jobs/build/ocp/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: lgtm, size/L

#1752 Adding 4.1 and now pushes
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/merge_ocp/merge_ocp.sh
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/S

#1728 add prometheus svt to pipeline
  alderaan/Jenkinsfile
  alderaan/pipeline-scripts/prometheus.groovy
  alderaan/property_files/prometheus.properties
Labels: lgtm, size/L

#1753 Push s2i-wildfly 16.0 images
  sjb/config/test_cases/push_wildfly_images.yml
  sjb/generated/push_wildfly_images.xml
Labels: size/XS

#1754 Add python dependencies for sjb/generate
  README.md
  sjb/requirements.txt
Labels: size/XS

#1758 build/custom: no need to check out ose repo at all
  jobs/build/custom/Jenkinsfile
Labels: size/M

#1756 build/merge_ocp: reuse a single clone and limit depth
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/merge_ocp/merge_ocp.sh
Labels: size/L

#1755 build/ocp4: unblock building 4.y with openshift package and new versioning
  build-scripts/rcm-guest/publish-oc-binary.sh
  build-scripts/rcm-guest/show-rpm-simple-errata-diff.sh
  build-scripts/rcm-guest/show-srpm-simple-errata-diff.sh
  build-scripts/rcm-guest/update-errata-with-diffs.sh
  jobs/build/ocp4/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/commonlib.groovy
Labels: size/XL

#1757 build/incremental: fix and update
  jobs/build/incremental/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/M

#1761 prevent silly errors on dockerfile reconciliation notices
  jobs/build/ocp/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/buildlib_test.groovy
Labels: lgtm, size/L

#1760 commonlib.shell wrapper for useful shell errors
  jobs/build/custom/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/commonlib.groovy
  pipeline-scripts/commonlib_test.groovy
Labels: lgtm, size/L

#1764 Move reposync to new storage
  jobs/build/reposync/Jenkinsfile
Labels: size/XS

#1763 Check for push.enterprise.sh failure
  jobs/build/reposync/Jenkinsfile
  scheduled-jobs/build/reposync/Jenkinsfile
Labels: lgtm, size/S

#1740 Update README.md with new Jenkins basic auth reqs
  README.md
Labels: lgtm, size/XS

#1768 Deploy more machines
  sjb/config/test_cases/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-machine-api-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
  sjb/generated/pull-ci-openshift-machine-api-operator-master-e2e.xml
Labels: size/S
