Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-06, with the labels that each got.

#1857 Add log sync stage
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: lgtm, size/XS

#1858 build/ocp3/Jenkinsfile: fix git checkouts that can fail
  jobs/build/ocp3/Jenkinsfile
Labels: size/XS

#1853 Update CVES base images
  jobs/build/update-base-images/Jenkinsfile
  jobs/build/update-base-images/README.md
  jobs/build/update-base-images/build.sh
  pipeline-scripts/commonlib.groovy
  scheduled-jobs/build/update-base-images/Jenkinsfile
  scheduled-jobs/build/update-base-images/README.md
Labels: size/L

#1859 Introduce kubemark based CI for github.com/openshift/kubernetes-autoscaler
  sjb/config/test_cases/pull-ci-openshift-kubernetes-autoscaler-master-e2e.yml
  sjb/generated/pull-ci-openshift-kubernetes-autoscaler-master-e2e.xml
Labels: size/XL

#1856 sign-artifacts tweaks
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/L

#1860 sign-artifacts: do not sign clients until RCM does
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/XS

#1861 fix escape
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/S

#1862 fix escape
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/S

#1864 fix escape
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/S

#1865 fix quote
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/XS

#1866 fix sign-artifacts
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/S

#1867 change dash to dot: tag name cant include dash
  pipeline-scripts/commonlib.groovy
Labels: size/XS

#1871 ocp3/Jenkinsfile: fix auto_mode version comparison
  jobs/build/ocp3/Jenkinsfile
Labels: size/XS

#1869 sign-artifacts: re-enable client signing; stage mode available
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: lgtm, size/S

#1874 sweep: send 4.x bugs to image advisory
  jobs/build/sweep/Jenkinsfile
Labels: lgtm, size/S

#1877 Adding 4.3 option
  pipeline-scripts/commonlib.groovy
Labels: size/XS

#1878 Add 4.2 bug sweep
  scheduled-jobs/build/bug-sweeps/4.2/Jenkinsfile
  scheduled-jobs/build/bug-sweeps/4.2/README.md
Labels: size/S

#1872 update-base-images: ubi7 + pkgs
  jobs/build/update-base-images/Jenkinsfile
  jobs/build/update-base-images/build.sh
  pipeline-scripts/commonlib.groovy
Labels: size/M

#1879 Disable job nobody seems to think is needed anymore
  jobs/package-dockertested/Jenkinsfile
Labels: size/S
