Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-05, with the labels that each got.

#1811 Make bug-sweep use default advisory if one is available
  jobs/build/sweep/Jenkinsfile
Labels: lgtm, size/S

#1813 Adding release job
  jobs/build/release/Jenkinsfile
  jobs/build/release/release.groovy
Labels: lgtm, size/L

#1814 added return this to release.groovy
  jobs/build/release/release.groovy
Labels: size/XS

#1815 Revert "Merge pull request #1811 from tbielawa/20190425-repair-bugs-a…
  jobs/build/sweep/Jenkinsfile
Labels: size/S

#1816 Fix metadata format
  jobs/build/release/release.groovy
Labels: size/XS

#1817 fix for calling oc sync job
  jobs/build/release/release.groovy
Labels: lgtm, size/XS

#1818 Build the latest kubemark controllers image in JJs
  sjb/config/test_cases/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-machine-api-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
  sjb/generated/pull-ci-openshift-machine-api-operator-master-e2e.xml
Labels: size/M

#1819 update oc command
  jobs/build/release/Jenkinsfile
  jobs/build/release/release.groovy
Labels: size/M

#1820 Fixing sleep and dry run for get info
  jobs/build/release/release.groovy
Labels: size/XS

#1821 More release job fixes
  jobs/build/release/Jenkinsfile
  jobs/build/release/release.groovy
Labels: size/S

#1823 release job tweaks
  jobs/build/release/Jenkinsfile
  jobs/build/release/release.groovy
Labels: size/XS

#1825 Create ocp latest job
  jobs/build/oc_sync/publish-clients-from-payload.sh
  jobs/build/set_client_latest/Jenkinsfile
  jobs/build/set_client_latest/set-latest.sh
Labels: lgtm, size/M

#1827 fix build-maint running doozer without --working-dir specify
  jobs/build/buildvm-maint/Jenkinsfile
Labels: lgtm, size/S

#1828 fix single quote problem
  jobs/build/buildvm-maint/Jenkinsfile
Labels: lgtm, size/XS

#1830 Force REQUESTS_CA_BUNDLE
  jobs/build/ocp3/Jenkinsfile
  jobs/build/ose/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  src/com/redhat/art/Rpm.groovy
Labels: size/M

#1831 Add GOTRACEBACK env var for full trace
  jobs/build/oc_sync/publish-clients-from-payload.sh
  jobs/build/release/release.groovy
  pipeline-scripts/buildlib.groovy
Labels: size/S

#1826 Bumping default to 4.2
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/XS

#1832 remove errant if from latest sync
  jobs/build/set_client_latest/Jenkinsfile
Labels: size/XS

#1833 Fix set-latest.sh
  jobs/build/set_client_latest/set-latest.sh
Labels: size/XS

#1834 Alderaan: First steps to run HTTP tests on any cluster.
  alderaan/pipeline-scripts/http.groovy
  alderaan/property_files/http.properties
Labels: lgtm, size/M

#1837 scheduled-jobs/build/rhcos-puddle: export REQUESTS_CA_BUNDLE
  scheduled-jobs/build/rhcos-puddle/Jenkinsfile
Labels: size/XS

#1836 appregistry: don't sync for 4.2 yet
  jobs/build/appregistry/Jenkinsfile
Labels: lgtm, size/XS

#1840 Keep 4.x builds forever
  jobs/build/appregistry/Jenkinsfile
  jobs/build/build-sync/Jenkinsfile
  jobs/build/custom/Jenkinsfile
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/odo_sync/Jenkinsfile
  jobs/build/ose4.1/Jenkinsfile
  jobs/build/release/Jenkinsfile
  jobs/build/reposync/Jenkinsfile
  jobs/build/set_client_latest/Jenkinsfile
Labels: size/S

#1841 Adding more explicit brew certs
  jobs/build/ocp3/Jenkinsfile
  jobs/build/openshift-online/scripts/merge-and-build-openshift-scripts.sh
  jobs/build/ose/scripts/build-32-rpm.sh
  jobs/build/ose/scripts/merge-and-build.sh
Labels: size/S

#1842 Retry 'stable updated' check for up to 2 hours.
  jobs/build/release/release.groovy
Labels: size/S

#1843 Adding errata URL option
  jobs/build/release/Jenkinsfile
  jobs/build/release/release.groovy
Labels: lgtm, size/S

#1844 Use uppercase names for PUDDLE_URL and IMAGE_REGISTRY_ROOT
  jobs/build/ocp3/Jenkinsfile
Labels: lgtm, size/XS

#1839 Signing request and copy jobs
  jobs/signing/mirror-artifacts/Jenkinsfile
  jobs/signing/sign-artifacts/Jenkinsfile
  jobs/signing/sign-artifacts/umb_producer.py
Labels: size/XL

#1847 Update find-bugs call for elliott upgrade
  jobs/build/sweep/Jenkinsfile
Labels: size/XS

#1851 Added producer/consumer threads to umb scripts
  jobs/signing/sign-artifacts/umb_producer.py
Labels: lgtm, size/M

#1852 Stub out mirroring artifacts to mirror.openshift.com
  jobs/signing/mirror-artifacts-stage/Jenkinsfile
  jobs/signing/mirror-artifacts/Jenkinsfile
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/XL

#1850 Adding 4.2 job
  jobs/build/ose4.2/Jenkinsfile
Labels: size/M

#1849 rhcos-puddle: add puddle for 4.2 builds
  scheduled-jobs/build/rhcos-puddle/Jenkinsfile
  scheduled-jobs/build/rhcos-puddle/README.md
Labels: size/M

#1854 sign-artifacts: use workDir and push pub
  build-scripts/use-mirror/push.pub.sh
  jobs/signing/sign-artifacts/Jenkinsfile
  jobs/signing/sign-artifacts/umb_producer.py
Labels: size/L
