Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-07, with the labels that each got.

#1881 scheduled-jobs/build/ocp-4.1-full: auto-bump version
  scheduled-jobs/build/ocp-4.1-full/Jenkinsfile
Labels: size/XS

#1882 appregistry: ignore 4.2 failures until we get it sorted
  jobs/build/appregistry/Jenkinsfile
Labels: size/XS

#1883 Start using the new aos-art-automation address
  jobs/build/appregistry/Jenkinsfile
  jobs/build/custom/Jenkinsfile
  jobs/build/ocp3/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/ocp4/build.groovy
  jobs/build/release/Jenkinsfile
  jobs/build/reposync/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/M

#1876 Migrate s2i docker tests to aos-cd-jobs
  sjb/config/test_cases/test_pull_request_s2i_master.yml
  sjb/generated/test_pull_request_s2i_master.xml
Labels: size/XL

#1885 update-base-images: fix package list bug
  jobs/build/update-base-images/Jenkinsfile
Labels: size/XS

#1887 update refresh-image jobs to disableConcurrentBuilds, add use-default…
  jobs/build/refresh-images/Jenkinsfile
Labels: size/S

#1888 Add new developers to MAIL_LIST_SUCCESS
  jobs/devex/jenkins-plugins/Jenkinsfile
Labels: size/XS

#1889 Update to use release:gen-payload
  jobs/build/build-sync/Jenkinsfile
Labels: size/S

#1891 Add job for 4.2 repo sync.
  scheduled-jobs/build/reposync-4.2/Jenkinsfile
  scheduled-jobs/build/reposync-4.2/README.md
Labels: size/S

#1890 slove jenkins job partial failed no display problem
  jobs/build/update-base-images/Jenkinsfile
  jobs/build/update-base-images/build.sh
Labels: size/S

#1893 Update Jenkinsfile: Triming recipient list for ART build notification
  jobs/devex/jenkins-plugins/Jenkinsfile
Labels: size/XS

#1894 Fix kustomize version
  sjb/config/test_cases/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-cluster-api-provider-kubemark-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-kubernetes-autoscaler-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-machine-api-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-api-provider-kubemark-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
  sjb/generated/pull-ci-openshift-kubernetes-autoscaler-master-e2e.xml
  sjb/generated/pull-ci-openshift-machine-api-operator-master-e2e.xml
Labels: size/L

#1895 Fix up mail/SSL errors for devex jenkins jobs
  jobs/devex/jenkins-bump-version/Jenkinsfile
  jobs/devex/jenkins-bump-version/bump-jenkins.sh
  jobs/devex/jenkins-plugins/Jenkinsfile
Labels: lgtm, size/M

#1896 advisory_images.py: get image names for docs
  jobs/build/release/advisory_images.py
Labels: size/M

#1898 added repair-bugs as part of bug sweep job
  jobs/build/sweep/Jenkinsfile
Labels: size/XS

#1899 make release.groovy can be reused by other jobs
  jobs/build/release/Jenkinsfile
  jobs/build/release/release.groovy
Labels: size/S

#1901 pull release.groovy out of build/release, make oc_sync more flexiable
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
  jobs/build/release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: size/M

#1902 update release.groovy path
  jobs/build/release/Jenkinsfile
Labels: size/XS

#1903 update parameter name of oc_sync
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
Labels: size/S

#1906 add new pre-release job
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
  jobs/build/pre-release/Jenkinsfile
  jobs/build/release/Jenkinsfile
  jobs/build/set_client_latest/Jenkinsfile
  jobs/build/set_client_latest/set-latest.sh
  pipeline-scripts/release.groovy
Labels: size/L
