Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-02, with the labels that each got.

#1687 merge_ocp: minor tweaks
  jobs/build/merge_ocp/merge_ocp.sh
Labels: lgtm, size/XS

#1693 Introduce cluster-autoscaler-operator over kubemark
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
Labels: size/XL

#1690 update build/refresh-images
  jobs/build/refresh-images/Jenkinsfile
  jobs/build/refresh-images/README.md
Labels: lgtm, size/M

#1694 Add reposync job
  build-scripts/use-mirror/push.enterprise.sh
  jobs/build/reposync/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/L

#1695 fix var issue for reposync
  jobs/build/reposync/Jenkinsfile
Labels: lgtm, size/XS

#1696 fix ssh key id
  jobs/build/reposync/Jenkinsfile
Labels: size/XS

#1698 build/custom: build signed when set
  jobs/build/custom/Jenkinsfile
Labels: lgtm, size/XS

#1699 CAO: bump k8s to 1.12.0
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
Labels: size/XS

#1700 Adding cachedir option to reposync
  jobs/build/reposync/Jenkinsfile
Labels: size/XS

#1701 fixing push.enterprise to use right dir
  build-scripts/use-mirror/push.enterprise.sh
Labels: size/XS

#1702 Minor changes:
  sjb/config/test_cases/ci-kubernetes-aws-actuator.yml
  sjb/config/test_cases/ci-kubernetes-machine-api-operator.yml
  sjb/generated/ci-kubernetes-aws-actuator.xml
  sjb/generated/ci-kubernetes-machine-api-operator.xml
Labels: size/M

#1691 introduce incremental builds
  jobs/build/incremental/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/L

#1703 build/ocp: sanitize and add in some status
  jobs/build/ocp/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/M

#1704 Adding reposync schedule
  jobs/build/reposync/Jenkinsfile
  scheduled-jobs/build/reposync/Jenkinsfile
  scheduled-jobs/build/reposync/README.md
Labels: size/M

#1705 build/ocp: fix and expand safeArchiveArtifacts call
  jobs/build/ocp/Jenkinsfile
Labels: lgtm, size/XS

#1707 disable concurrent builds in reposync
  jobs/build/reposync/Jenkinsfile
  scheduled-jobs/build/reposync/Jenkinsfile
Labels: size/S

#1697 Don't mail ART JIRA build results anymore
  jobs/build/custom/Jenkinsfile
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/ocp/Jenkinsfile
  jobs/build/ose/Jenkinsfile
  jobs/build/reposync/Jenkinsfile
Labels: lgtm, size/S

#1706 standardize some initialization
  jobs/build/custom/Jenkinsfile
  jobs/build/incremental/Jenkinsfile
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/ocp/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
  jobs/build/reposync/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/XXL

#1708 New job for cluster-api-actuator-pkg
  sjb/config/test_cases/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.xml
Labels: size/XL

#1709 No need to override cao image
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
Labels: size/XS

#1710 machine API: Bump golang version to 1.10.1
  sjb/config/test_cases/ci-kubernetes-aws-actuator.yml
  sjb/generated/ci-kubernetes-aws-actuator.xml
Labels: size/S

#1711 commonlib: fix cleanCommaList
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/XS

#1712 Moving 4.0 to pre-release
  jobs/build/ose4.0/Jenkinsfile
Labels: size/XS

#1510 Typo and team name
  jobs/build/ocp/Jenkinsfile
Labels: lgtm, size/XS

#1713 Creating 4.x job
  jobs/build/ocp4/Jenkinsfile
  jobs/build/ose4.0/Jenkinsfile
  jobs/build/ose4.1/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: size/XL

#1716 Get mao image from payload
  sjb/config/test_cases/pull-ci-openshift-cluster-api-provider-libvirt-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-provider-libvirt-master-e2e.xml
Labels: size/S

#1715 remove more openshift-ansible refs
  jobs/build/ocp4/Jenkinsfile
Labels: size/S

#1714 build/custom: wishlist items
  jobs/build/custom/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/L

#1717 Bump CAO to Ginkgo test suite
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
Labels: size/L

#1718 ocp/4 RPM rebuilds
  jobs/build/ocp/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
Labels: lgtm, size/M
