Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-09, with the labels that each got.

#1942 build/release: Increase timeout for upgrade testing
  pipeline-scripts/release.groovy
Labels: lgtm, size/XS

#1944 call_puddle_advisory.sh: 'building' symlink used for el7 builds
  build-scripts/rcm-guest/call_puddle_advisory.sh
Labels: size/XS

#1943 buildvm_backup job
  jobs/maintenance/buildvm_backup/Jenkinsfile
  jobs/maintenance/buildvm_backup/build.groovy
Labels: size/L

#1946 Fix oc push to find older rpm
  build-scripts/rcm-guest/publish-oc-v4-binary.sh
Labels: size/XS

#1947 signed-compose: 3.x do not use rhel8 compose
  jobs/build/signed-compose/Jenkinsfile
  jobs/build/signed-compose/build.groovy
Labels: lgtm, size/S

#1948 Fix path inside RPM & allow expansion to occur before other steps
  build-scripts/rcm-guest/publish-oc-v4-binary.sh
Labels: size/S

#1949 Bump go version to support go modules in CAO
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
Labels: lgtm, size/S

#1951 Run backup job during maintenance
  scheduled-jobs/build/buildvm-maint/Jenkinsfile
Labels: lgtm, size/XS

#1952 Fix build mailer footer
  pipeline-scripts/commonlib.groovy
Labels: size/S

#1918 [ART-733] Create build/advisories job
  jobs/build/advisories/Jenkinsfile
Labels: size/L

#1939 [ART-877] use metadata containers on appregistry
  jobs/build/appregistry/Jenkinsfile
Labels: size/M

#1945 ART-947: fix release job ADVISORY parameter and remove ERRATA_URL par…
  jobs/build/pre-release/Jenkinsfile
  jobs/build/release/Jenkinsfile
  pipeline-scripts/commonlib.groovy
  pipeline-scripts/release.groovy
Labels: size/M

#1954 Add build/ose4.3 job + corresponding scheduled builds
  jobs/build/ose4.3/Jenkinsfile
  scheduled-jobs/build/ocp-4.3-full/Jenkinsfile
  scheduled-jobs/build/ocp-4.3-full/README.md
  scheduled-jobs/build/ocp-4.3-incremental/Jenkinsfile
  scheduled-jobs/build/ocp-4.3-incremental/README.md
  scheduled-jobs/build/reposync-4.3/Jenkinsfile
  scheduled-jobs/build/reposync-4.3/README.md
Labels: size/M

#1955 Add 4.3 scheduled bug sweep job
  scheduled-jobs/build/bug-sweeps/4.3/Jenkinsfile
  scheduled-jobs/build/bug-sweeps/4.3/README.md
Labels: size/S

#1957 adding new job sync kn client
  build-scripts/rcm-guest/publish-kn-binary.sh
  jobs/build/kn_sync/Jenkinsfile
Labels: size/L

#1960 [ART-627] followup changes
  build-scripts/rcm-guest/publish-kn-binary.sh
  build-scripts/rcm-guest/publish-oc-binary.sh
  jobs/build/kn_sync/Jenkinsfile
Labels: size/L

#1938 Use commonlib.buildURL
  Jenkinsfile
  jobs/build/appregistry/Jenkinsfile
  jobs/build/aws-ami/Jenkinsfile
  jobs/build/custom/Jenkinsfile
  jobs/build/make-puddle/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/ocp4/build.groovy
  jobs/build/openshift-online/Jenkinsfile
  jobs/build/ose/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
  scheduled-jobs/build/logging-and-metrics-distgit-populator/Jenkinsfile
  scheduled-jobs/build/rhel7next/Jenkinsfile
Labels: size/M

#1950 ART-777: Send UMB message when release job completes
  jobs/build/release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: lgtm, size/M

#1956 Initial iptables output lockdown helper
  hacks/iptables/buildvm-scripts/canttouchthat.md
  hacks/iptables/buildvm-scripts/canttouchthat.py
Labels: lgtm, size/L

#1962 Allow full depth clone
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/merge_ocp/merge_ocp.sh
Labels: lgtm, size/S

#1964 Default to full depth
  jobs/build/merge_ocp/Jenkinsfile
Labels: lgtm, size/XS

#1963 odo_sync: Add token to GitHub API request
  build-scripts/rcm-guest/publish-odo-binary.sh
  jobs/build/odo_sync/Jenkinsfile
Labels: lgtm, size/S

#1961 Update more email addresses to use new mailing list pattern
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/ocp3/Jenkinsfile
  jobs/build/odo_sync/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
Labels: size/M

#1965 Force no depth limit on clone
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/ocp3/Jenkinsfile
  jobs/build/odo_sync/Jenkinsfile
  scheduled-jobs/build/merge/Jenkinsfile
Labels: size/S

#1967 Reuse ose repo to speed up merge / lock github activity
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/merge_ocp/merge_ocp.sh
  jobs/build/ocp4/Jenkinsfile
Labels: lgtm, size/L

#1970 Scripts to help find which rpms are not being used by containers
  hacks/refine-candidate/download-logs.sh
  hacks/refine-candidate/findit.sh
Labels: size/M

#1966 Single reposync for all releases
  scheduled-jobs/build/reposync-4.2/Jenkinsfile
  scheduled-jobs/build/reposync-4.2/README.md
  scheduled-jobs/build/reposync-4.3/Jenkinsfile
  scheduled-jobs/build/reposync-4.3/README.md
  scheduled-jobs/build/reposync/Jenkinsfile
Labels: size/M

#1973 Enabling 4.3 merges
  jobs/build/merge_ocp/Jenkinsfile
  pipeline-scripts/commonlib.groovy
  scheduled-jobs/build/merge/Jenkinsfile
Labels: lgtm, size/S

#1974 Add 4.3 puddle configurations
  build-scripts/puddle-conf/atomic_openshift-4.3.conf
  build-scripts/puddle-conf/atomic_openshift-4.3.el8.conf
  build-scripts/puddle-conf/errata-puddle-4.3-signed.conf
  build-scripts/puddle-conf/errata-puddle-4.3-signed.el8.conf
Labels: size/M

#1884 Use print() function in both Python 2 and Python 3
  build-scripts/rcm-guest/errata_json.py
  jobs/build/aws-ami/oo-ec2-find-ami.py
  jobs/build/ose/scripts/sanity_check_test.py
  sjb/find_abandoned_xmls.py
  sjb/graph.py
Labels: lgtm, size/M

#1870 chore(sjb/**): change aos-auth-team emails to aos-apiserver
  sjb/config/test_cases/test_branch_origin_extended_gssapi.yml
  sjb/config/test_cases/test_branch_origin_extended_gssapi_310.yml
  sjb/config/test_cases/test_branch_origin_extended_ldap_groups.yml
  sjb/config/test_cases/test_branch_origin_extended_ldap_groups_310.yml
  sjb/generated/test_branch_origin_extended_gssapi.xml
  sjb/generated/test_branch_origin_extended_gssapi_310.xml
  sjb/generated/test_branch_origin_extended_ldap_groups.xml
  sjb/generated/test_branch_origin_extended_ldap_groups_310.xml
Labels: lgtm, size/S

#1975 Remove Gabe from devex jenkins email lists
  jobs/devex/jenkins-bump-version/Jenkinsfile
  jobs/devex/jenkins-plugins/Jenkinsfile
Labels: size/XS

#1976 Prevent waiting for 4.y while 4.x is building
  jobs/build/custom/Jenkinsfile
  jobs/build/merge_ocp/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: size/L

#1978 rpmdiff complete checker fix
  jobs/build/signed-compose/rpmdiff.py
Labels: lgtm, size/XS

#1979 hacks/refine-candidate tweaks
  hacks/refine-candidate/download-logs.sh
  hacks/refine-candidate/findit.sh
  hacks/refine-candidate/untag.sh
Labels: size/L
