Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-11, with the labels that each got.

#2022 ART-1149: [4.4] add new release to rhcos-puddle
  jobs/build/rhcos-puddle/Jenkinsfile
Labels: size/XS

#2023 RHCOS Sync job.
  build-scripts/use-mirror/rhcossync.sh
  jobs/build/rhcos_sync/Jenkinsfile
  jobs/build/rhcos_sync/build.groovy
Labels: size/L

#2021 ART-1196: scope "release" job to look at "latest" for the same version
  jobs/build/release/Jenkinsfile
  pipeline-scripts/commonlib.groovy
  pipeline-scripts/release.groovy
Labels: size/M

#2025 [ART-1228] Fix broken sweep job
  pipeline-scripts/buildlib.groovy
Labels: lgtm, size/XS

#2026 adding 4.3 release to send-umb-message job
  jobs/build/send-umb-messages/Jenkinsfile
Labels: lgtm, size/XS

#2028 Update CRC job
  jobs/build/crc/Jenkinsfile
  jobs/build/crc/build.groovy
Labels: lgtm, size/L

#2030 update-base-images: Lock ansible-runner version
  jobs/build/update-base-images/build.sh
Labels: lgtm, size/XS

#2032 [ART-617] improve appregistry
  jobs/build/appregistry/Jenkinsfile
  jobs/build/appregistry/appregistry.groovy
Labels: lgtm, size/XL

#2036 improve signed-compose job
  jobs/build/signed-compose/Jenkinsfile
  jobs/build/signed-compose/build.groovy
Labels: size/M

#2033 [ART-1214] Renames kn binary name in compressed deliverable
  build-scripts/rcm-guest/publish-kn-binary.sh
Labels: lgtm, size/XS

#2031 Add latest-major.minor links and multi-arch support
  build-scripts/use-mirror/set-v4-client-latest.sh
  jobs/build/set_client_latest/Jenkinsfile
  jobs/build/set_client_latest/set-latest.sh
Labels: lgtm, size/L

#2029 [ART-1122] make set_client_latest multi-version aware
  jobs/build/set_client_latest/set-latest.sh
Labels: size/S

#2035 Make release multi-arch aware
  jobs/build/build-sync/build.groovy
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
  jobs/build/pre-release/Jenkinsfile
  jobs/build/release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: size/L

#2041 No more unlabeled src_dest files in build-sync
  jobs/build/build-sync/build.groovy
Labels: size/XS

#2043 Pull release from api.ci
  jobs/build/release/Jenkinsfile
Labels: size/XS

#2040 hardcode logging proxy image
  sjb/inventory/group_vars/OSEv3/logging.yml
Labels: lgtm, size/XS

#2042 Temp fix to push client to new multi-arch location
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
  jobs/build/release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: size/L

#2044 Send arch into client publish
  jobs/build/pre-release/Jenkinsfile
  jobs/build/release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: size/S

#2045 Fix redundant arches in description
  jobs/build/build-sync/build.groovy
Labels: size/XS

#2048 Make oc_sync multi-arch aware
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
Labels: size/M

#2050 [ART-675] Usage instructions for release DESCRIPTION param
  jobs/build/release/Jenkinsfile
Labels: lgtm, size/XS

#2046 [ART-1258] scope mirror pushes to client dir
  build-scripts/rcm-guest/publish-oc-v4-binary.sh
  build-scripts/rcm-guest/publish-odo-binary.sh
  build-scripts/use-mirror/set-v4-client-latest.sh
  jobs/build/crc/build.groovy
Labels: lgtm, size/L

#2047 signed-compose: [ART-1065] use same method for el7 as el8
  build-scripts/puddle-conf/errata-puddle-3.10-signed.conf
  build-scripts/puddle-conf/errata-puddle-3.10-signed.el7.conf
  build-scripts/puddle-conf/errata-puddle-3.10.conf
  build-scripts/puddle-conf/errata-puddle-3.11-signed.conf
  build-scripts/puddle-conf/errata-puddle-3.11-signed.el7.conf
  build-scripts/puddle-conf/errata-puddle-3.11.conf
  build-scripts/puddle-conf/errata-puddle-3.9-signed.conf
  build-scripts/puddle-conf/errata-puddle-3.9-signed.el7.conf
  build-scripts/puddle-conf/errata-puddle-3.9.conf
  build-scripts/puddle-conf/errata-puddle-4.1-signed.conf
  build-scripts/puddle-conf/errata-puddle-4.1-signed.el7.conf
  build-scripts/puddle-conf/errata-puddle-4.1.conf
  build-scripts/puddle-conf/errata-puddle-4.2-signed.conf
  build-scripts/puddle-conf/errata-puddle-4.2-signed.el7.conf
  build-scripts/puddle-conf/errata-puddle-4.3-signed.conf
  build-scripts/puddle-conf/errata-puddle-4.3-signed.el7.conf
  build-scripts/puddle-conf/errata-puddle-4.4-signed.conf
  build-scripts/puddle-conf/errata-puddle-4.4-signed.el7.conf
  build-scripts/rcm-guest/call_puddle_advisory.sh
  build-scripts/rcm-guest/call_puddle_signed_tag.sh
  jobs/build/signed-compose/Jenkinsfile
  jobs/build/signed-compose/build.groovy
Labels: size/XL

#2038 [ART-675] trigger signing after release job
  jobs/build/release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: lgtm, size/S

#2054 Allow pre-release to autodetect latest nightly
  jobs/build/pre-release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: lgtm, size/M

#2057 build/release: refresh quay auth before client sync
  jobs/build/release/Jenkinsfile
Labels: lgtm, size/XS

#2056 Query separate release controllers
  jobs/build/pre-release/Jenkinsfile
  jobs/build/release/Jenkinsfile
  jobs/build/send-umb-messages/Jenkinsfile
  jobs/signing/sign-artifacts/umb_producer.py
  pipeline-scripts/commonlib.groovy
  pipeline-scripts/release.groovy
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: size/M

#2055 [ART-1231] adding sign-artifacts to support multiarch
  jobs/build/release/Jenkinsfile
  jobs/signing/sign-artifacts/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: lgtm, size/S

#2061 Bump openshift-ansible version for gogitit
  tower-scripts/bin/gogitit_online_int.yml
  tower-scripts/bin/gogitit_online_prod.yml
  tower-scripts/bin/gogitit_online_stg.yml
Labels: size/XS

#2060 [ART-1293] Fix broken UMB messages job
  jobs/build/send-umb-messages/Jenkinsfile
Labels: lgtm, size/XS

#2049 [ART-1252] remove refresh-image jobs and move attach advisory to custom job
  jobs/build/custom/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
  jobs/build/refresh-images/README.md
Labels: size/L

#2037 [ART-675] Add release name to release and signing jobs
  jobs/build/release/Jenkinsfile
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/S

#2063 signing: Fix always dryrun
  jobs/signing/sign-artifacts/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: lgtm, size/S

#2062 cri-o: force a checkout
  sjb/config/test_cases/test_pull_request_crio_critest_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_e2e_features_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_e2e_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_integration_rhel.yml
Labels: lgtm, size/S

#2064 Fix release job calling signArtifacts
  pipeline-scripts/release.groovy
Labels: lgtm, size/S

#2051 [ART-675] Update description of release PREVIOUS param
  jobs/build/release/Jenkinsfile
Labels: lgtm, size/XS

#2059 [ART-675] Create release image-list artifact
  jobs/build/release/Jenkinsfile
Labels: lgtm, size/S

#2065 Fix a syntax error in set-client-latest
  build-scripts/use-mirror/set-v4-client-latest.sh
Labels: lgtm, size/XS
