Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-08, with the labels that each got.

#1892 update Jenkinsfile to enable specifying DOOZER_DATA_PATH
  jobs/build/custom/Jenkinsfile
Labels: size/S

#1907 merge_ocp.sh: scope magic to OCP 3
  jobs/build/merge_ocp/merge_ocp.sh
Labels: size/S

#1905 Add a job to send UMB messages for new releases
  jobs/build/send-umb-messages/Jenkinsfile
  jobs/build/send-umb-messages/README.md
Labels: lgtm, size/M

#1910 Use capital Custom type
  jobs/build/send-umb-messages/Jenkinsfile
Labels: size/XS

#1911 Send UMB tweaks
  jobs/build/send-umb-messages/Jenkinsfile
Labels: size/S

#1913 Discard new-payload builds and include 4.1-nightly
  jobs/build/send-umb-messages/Jenkinsfile
Labels: size/S

#1914 Switch back to JSON for QE new payload messages
  jobs/build/send-umb-messages/Jenkinsfile
Labels: size/S

#1916 add an e.g. to make parameter more clear to understand
  jobs/build/set_client_latest/Jenkinsfile
Labels: lgtm, size/XS

#1917 Remove individual from buildvm snapshot email
  jobs/build/buildvm-maint/Jenkinsfile
Labels: lgtm, size/S

#1897 New job to quickly create signed composes
  build-scripts/rcm-guest/call_puddle_advisory.sh
  jobs/build/signed-compose/Jenkinsfile
  jobs/build/signed-compose/build.groovy
  jobs/build/signed-compose/rpmdiff.py
  pipeline-scripts/buildlib.groovy
Labels: size/L

#1919 [ART-877] Use metadata containers on appregistry job
  jobs/build/appregistry/Jenkinsfile
Labels: lgtm, size/M

#1924 Remove that weird 7.2 extras thing from the puddle confs
  build-scripts/puddle-conf/errata-puddle-3.10-signed.conf
  build-scripts/puddle-conf/errata-puddle-3.11-signed.conf
  build-scripts/puddle-conf/errata-puddle-3.7-signed.conf
  build-scripts/puddle-conf/errata-puddle-3.8-signed.conf
  build-scripts/puddle-conf/errata-puddle-3.9-signed.conf
  build-scripts/puddle-conf/errata-puddle-4.0-signed.conf
  build-scripts/puddle-conf/errata-puddle-4.1-signed.conf
Labels: size/S

#1925 Include link to broken build sync job on failure
  jobs/build/oc_sync/Jenkinsfile
Labels: size/S

#1927 Smarter build URL link
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/commonlib.groovy
Labels: size/M

#1929 pre-release: make client mirroring optional
  jobs/build/pre-release/Jenkinsfile
Labels: lgtm, size/S

#1928 update-base-images: fail faster on missing rpms
  jobs/build/update-base-images/build.sh
Labels: lgtm, size/XS

#1933 Change advisory state to attach metadata build on appregistry job
  jobs/build/appregistry/Jenkinsfile
Labels: size/XS

#1926 update-base-images: enable s390x builds
  jobs/build/update-base-images/build.sh
Labels: do-not-merge/hold, size/S
