Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-01, with the labels that each got.

#1679 aws actuator: test-e2e renamed to k8s-e2e
  sjb/config/test_cases/ci-kubernetes-aws-actuator.yml
  sjb/generated/ci-kubernetes-aws-actuator.xml
Labels: size/XS

#1680 Use origin-cli for 3.10+ to get oc for console tests
  sjb/config/test_cases/test_branch_origin_web_console_310.yml
  sjb/config/test_cases/test_branch_origin_web_console_311.yml
  sjb/generated/test_branch_origin_web_console_310.xml
  sjb/generated/test_branch_origin_web_console_311.xml
  sjb/generated/test_pull_request_origin_web_console_310.xml
  sjb/generated/test_pull_request_origin_web_console_311.xml
Labels: lgtm, size/S

#1681 Refactor versioned origin-web-console test branch
  sjb/config/test_cases/test_branch_origin_web_console_310.yml
  sjb/config/test_cases/test_branch_origin_web_console_311.yml
  sjb/config/test_cases/test_branch_origin_web_console_39.yml
  sjb/generated/test_branch_origin_web_console_310.xml
  sjb/generated/test_branch_origin_web_console_311.xml
  sjb/generated/test_branch_origin_web_console_39.xml
  sjb/generated/test_pull_request_origin_web_console_310.xml
  sjb/generated/test_pull_request_origin_web_console_311.xml
  sjb/generated/test_pull_request_origin_web_console_39.xml
Labels: lgtm, size/L

#1682 Add some debugging to quay syncing
  scheduled-jobs/build/oc-mirror-quay-dev/Jenkinsfile
Labels: size/XS

#1683 Abort on image mirror failures. Save input artifacts. Retry mirroring.
  scheduled-jobs/build/oc-mirror-quay-dev/Jenkinsfile
Labels: lgtm, size/M

#1685 Lock pulled oc binary to v3.11 version when testing against master branch
  sjb/config/test_cases/test_branch_origin_web_console.yml
  sjb/generated/test_branch_origin_web_console.xml
  sjb/generated/test_pull_request_origin_web_console.xml
Labels: lgtm, size/L

#1688 Don't set openshift_node_labels
  sjb/inventory/host_vars/localhost.yml
Labels: lgtm, size/XS

#1689 Replace outdated openshift_logging_elasticsearch_proxy_image_.* vars
  sjb/inventory/group_vars/OSEv3/logging.yml
Labels: lgtm, size/XS
