Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-10, with the labels that each got.

#1980 Job result status is not determined by SRC=DEST filtering
  jobs/build/build-sync/Jenkinsfile
Labels: size/S

#1982 ART-1078: package-dockertested seen as cruft
  jobs/package-dockertested/.gitignore
  jobs/package-dockertested/Jenkinsfile
  jobs/package-dockertested/README.md
  jobs/package-dockertested/build-openshift-ansible-release.sh
  jobs/package-dockertested/build-origin-release.sh
  jobs/package-dockertested/configure-tmpfs.sh
  jobs/package-dockertested/install-ansible-plugins.sh
  jobs/package-dockertested/install-openshift-ansible-release.sh
  jobs/package-dockertested/install-origin-release.sh
  jobs/package-dockertested/install-rhel7next-dependencies.sh
  jobs/package-dockertested/rhel7next.repo
  jobs/package-dockertested/run-origin-tests.sh
Labels: size/L

#1984 Remove unused job
  continuous-upgrade/actions/install_junit.sh
  continuous-upgrade/generate-jobs.sh
  continuous-upgrade/generated/continuous-upgrade_cicd-dump-load-logs-job.xml
  continuous-upgrade/generated/continuous-upgrade_cicd-get-load-logs-job.xml
  continuous-upgrade/generated/continuous-upgrade_cicd-start-load-job.xml
  continuous-upgrade/generated/continuous-upgrade_cicd-upgrade-job.xml
  continuous-upgrade/generated/continuous-upgrade_provision-job.xml
  continuous-upgrade/generated/continuous-upgrade_terminate-job.xml
  continuous-upgrade/generated/continuous-upgrade_upgrade-job.xml
  continuous-upgrade/jobs/cicd-download-artifacts.sh
  continuous-upgrade/jobs/cicd-dump-load-logs-job.yml
  continuous-upgrade/jobs/cicd-get-load-logs-job.yml
  continuous-upgrade/jobs/cicd-start-load-job.yml
  continuous-upgrade/jobs/cicd-start-load.sh
  continuous-upgrade/jobs/cicd-upgrade-job.yml
  continuous-upgrade/jobs/cicd-upgrade-ocp.sh
  continuous-upgrade/jobs/download-artifacts.sh
  continuous-upgrade/jobs/global-defaults.yml
  continuous-upgrade/jobs/install-ocp.sh
  continuous-upgrade/jobs/install-oct.sh
  continuous-upgrade/jobs/provision-cloud-resources.sh
  continuous-upgrade/jobs/provision-job.yml
  continuous-upgrade/jobs/terminate-cloud-resources.sh
  continuous-upgrade/jobs/terminate-job.yml
  continuous-upgrade/jobs/upgrade-job.yml
  continuous-upgrade/jobs/upgrade-ocp.sh
  continuous-upgrade/reliability-test/config.yaml
  continuous-upgrade/reliability-test/tasks/day
  continuous-upgrade/reliability-test/tasks/hour
  continuous-upgrade/reliability-test/tasks/minute
  continuous-upgrade/reliability-test/tasks/month
  continuous-upgrade/reliability-test/tasks/pre
  continuous-upgrade/reliability-test/tasks/test
  continuous-upgrade/reliability-test/tasks/week
Labels: size/XL

#1971 [ART-999] Create Extras & OLM Operators metadata advisories w/ placeholders for 4.x
  jobs/build/advisories/Jenkinsfile
Labels: size/M

#1983 Improve owner feedback if there is a merge error into distgit.
  pipeline-scripts/buildlib.groovy
Labels: size/M

#1986 build/ocp4: only lock while updating dist-git
  jobs/build/ocp4/Jenkinsfile
Labels: size/S

#1987 [ART-1084] do repair bugs before sweep
  jobs/build/sweep/Jenkinsfile
Labels: lgtm, size/M

#1989 Differentiate email subjects for error / success reconciliations
  pipeline-scripts/buildlib.groovy
Labels: size/XS

#1992 Retry ssh command upon failure
  jobs/build/oc_sync/publish-clients-from-payload.sh
Labels: lgtm, size/S

#1988 OpenShift-Ansible 3.9 Install pip Directly
  sjb/config/test_cases/test_pull_request_openshift_ansible_tox.yml
  sjb/config/test_cases/test_pull_request_openshift_ansible_tox_310.yml
  sjb/generated/test_branch_origin_extended_conformance_install_39.xml
  sjb/generated/test_pull_request_openshift_ansible_extended_conformance_install_release_39.xml
  sjb/generated/test_pull_request_openshift_ansible_tox.xml
  sjb/generated/test_pull_request_openshift_ansible_tox_310.xml
Labels: lgtm, size/L

#1995 Lock Chrome to v76 for 3.11 console tests
  sjb/config/test_cases/test_branch_origin_web_console_311.yml
  sjb/generated/test_branch_origin_web_console_311.xml
  sjb/generated/test_pull_request_origin_web_console_311.xml
Labels: size/M

#1997 update gitlab refs to github
  jobs/build/advisories/Jenkinsfile
  jobs/build/custom/Jenkinsfile
Labels: lgtm, size/XS

#1991 Bring multiarch support to the build-sync job
  jobs/build/build-sync/Jenkinsfile
  jobs/build/build-sync/build.groovy
  pipeline-scripts/buildlib.groovy
Labels: size/L

#1999 fix logging CI for 3.11 - let ansible set proxy image
  sjb/config/test_cases/test_branch_openshift_ansible_logging.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_311.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file.yml
  sjb/config/test_cases/test_branch_openshift_ansible_logging_json_file_311.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald-release-3.11.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml
  sjb/config/test_cases/test_pull_request_origin_aggregated_logging_json_file.yml
  sjb/generated/test_branch_openshift_ansible_logging.xml
  sjb/generated/test_branch_openshift_ansible_logging_311.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file.xml
  sjb/generated/test_branch_openshift_ansible_logging_json_file_311.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file.xml
  sjb/generated/test_branch_origin_aggregated_logging_json_file_311.xml
  sjb/generated/test_pull_request_openshift_ansible_logging-release-3.11.xml
  sjb/generated/test_pull_request_openshift_ansible_logging.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_311.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_36.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_37.xml
  sjb/generated/test_pull_request_openshift_ansible_logging_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald-release-3.11.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_journald_39.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file-release-3.11.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_36.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_37.xml
  sjb/generated/test_pull_request_origin_aggregated_logging_json_file_39.xml
  sjb/inventory/group_vars/OSEv3/logging.yml
Labels: size/M

#1998 Disable pigz during client extraction
  jobs/build/oc_sync/publish-clients-from-payload.sh
Labels: lgtm, size/XS

#2002 Use new arches code from doozer config:read-group
  pipeline-scripts/buildlib.groovy
Labels: size/S

#1968 Add Jenkins Openshift-dev-services group members
  sjb/config/test_cases/push_jenkins_images.yml
  sjb/generated/push_jenkins_images.xml
Labels: lgtm, size/S

#2007 Initial pass at candidate tagging script
  hacks/refine-candidate/README.MD
  hacks/refine-candidate/tag-em.sh
Labels: size/M

#2003 Add build/ose4.4 job + corresponding scheduled builds
  jobs/build/ose4.4/Jenkinsfile
  scheduled-jobs/build/ocp-4.4-full/Jenkinsfile
  scheduled-jobs/build/ocp-4.4-full/README.md
  scheduled-jobs/build/ocp-4.4-incremental/Jenkinsfile
  scheduled-jobs/build/ocp-4.4-incremental/README.md
  scheduled-jobs/build/reposync/Jenkinsfile
Labels: lgtm, size/M

#2008 Make scheduled reposync job multi-arch aware
  scheduled-jobs/build/reposync/Jenkinsfile
Labels: lgtm, size/S

#2012 Checkout scm
  scheduled-jobs/build/reposync/Jenkinsfile
Labels: size/XS

#2013 Adding 4.4 puddle files
  build-scripts/puddle-conf/atomic_openshift-4.4.conf
  build-scripts/puddle-conf/atomic_openshift-4.4.el8.conf
  build-scripts/puddle-conf/errata-puddle-4.4-signed.conf
  build-scripts/puddle-conf/errata-puddle-4.4-signed.el8.conf
Labels: size/M

#2014 Lower sanity check for reposync to 7000
  jobs/build/reposync/Jenkinsfile
Labels: size/XS

#2006 [ART-1146] Enable 4.4 merges
  pipeline-scripts/commonlib.groovy
Labels: size/XS

#2016 advisories: adjust parameter descriptions
  jobs/build/advisories/Jenkinsfile
Labels: lgtm, size/S

#2015 signing: clean up parameters
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: lgtm, size/XS

#2004 make signedComposeStateQE retry 3 times
  jobs/build/signed-compose/build.groovy
Labels: lgtm, size/XS

#2001 ART-1006: Fetch OLM operators NVRs from advisories
  jobs/build/appregistry/Jenkinsfile
Labels: size/L

#1996 Honor freeze_automation in group.yml for ocp4
  jobs/build/ocp4/Jenkinsfile
  jobs/build/sweep/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/M

#2019 Adding 4.4 bugsweep job
  scheduled-jobs/build/bug-sweeps/4.4/Jenkinsfile
  scheduled-jobs/build/bug-sweeps/4.4/README.md
Labels: size/S

#2020 ART-1160: Automate running pre-release job
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: size/M
