Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-04, with the labels that each got.

#1769 Introduce CI for kubemark-actuator
  sjb/config/test_cases/pull-ci-openshift-cluster-api-provider-kubemark-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-provider-kubemark-master-e2e.xml
Labels: size/XL

#1770 Tag docker images instead of changing deployments
  sjb/config/test_cases/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
Labels: size/M

#1765 buildlib: wait before re-submitting brew tasks
  pipeline-scripts/buildlib.groovy
Labels: lgtm, size/XS

#1771 build/ocp: watch/retry o-a/a-o builds in serial for now
  jobs/build/ocp/Jenkinsfile
Labels: lgtm, size/XS

#1773 Add 4.1 RHEL8 puddle conf
  build-scripts/puddle-conf/atomic_openshift-4.1.el8.conf
  scheduled-jobs/build/rhcos-puddle/Jenkinsfile
  scheduled-jobs/build/rhcos-puddle/README.md
Labels: size/M

#1772 build-sync: Parameterize selecting base image stream file
  jobs/build/build-sync/Jenkinsfile
Labels: size/XS

#1774 Fixups for moving to cri-o/cri-o
  sjb/config/common/test_cases/crio.yml
  sjb/config/test_cases/ami_build_origin_int_rhel_crio.yml
  sjb/config/test_cases/test_branch_crio_e2e_features_rhel.yml
  sjb/config/test_cases/test_branch_crio_e2e_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_ami_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_critest_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_e2e_features_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_e2e_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_integration_rhel.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_features_fedora.xml
  sjb/generated/test_branch_crio_e2e_features_rhel.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_features_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_features_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
  sjb/generated/test_pull_request_crio_managed_net_ns_e2e_fedora.xml
Labels: size/L

#1762 build/ocp4: converged incremental or full build
  jobs/build/ocp4/Jenkinsfile
  jobs/build/ocp4/build.groovy
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/XXL

#1778 build/*: background cleaning workdir
  jobs/build/build-sync/Jenkinsfile
  jobs/build/custom/Jenkinsfile
  jobs/build/incremental/Jenkinsfile
  jobs/build/ocp/Jenkinsfile
  jobs/build/ocp4/build.groovy
  jobs/build/openshift-online/Jenkinsfile
  jobs/build/refresh-images/Jenkinsfile
  jobs/build/reposync/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: lgtm, size/M

#1780 updating oc mirror for v4
  build-scripts/rcm-guest/publish-oc-v4-binary.sh
  jobs/build/ocp4/build.groovy
Labels: size/M

#1779 build/ocp4: improve display of build plan
  jobs/build/ocp4/build.groovy
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/M

#1782 rhcos-puddle: add openshift el8 RPM build
  scheduled-jobs/build/rhcos-puddle/Jenkinsfile
  scheduled-jobs/build/rhcos-puddle/README.md
Labels: lgtm, size/M

#1783 remove errant ln call
  build-scripts/rcm-guest/publish-oc-v4-binary.sh
Labels: size/XS

#1784 build/ocp: fix python-style comments in groovy
  jobs/build/ocp/Jenkinsfile
Labels: size/XS

#1786 Move oc sync path
  build-scripts/rcm-guest/publish-oc-v4-binary.sh
Labels: lgtm, size/XS

#1785 Publish to 4.0/4.1 IS's during transition to 4.1
  jobs/build/build-sync/Jenkinsfile
Labels: size/S

#1787 Fix ocp job and rename to ocp3
  jobs/build/ocp3/Jenkinsfile
  jobs/build/ose3.10/Jenkinsfile
  jobs/build/ose3.11/Jenkinsfile
  jobs/build/ose3.7/Jenkinsfile
  jobs/build/ose3.8/Jenkinsfile
  jobs/build/ose3.9/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/M

#1788 Publish ODO binary
  build-scripts/rcm-guest/publish-odo-binary.sh
  jobs/build/odo_sync/Jenkinsfile
  scheduled-jobs/build/odo_sync/Jenkinsfile
  scheduled-jobs/build/odo_sync/README.md
Labels: lgtm, size/L

#1791 Fix missing param
  jobs/build/odo_sync/Jenkinsfile
Labels: size/XS

#1792 Reverting 33a2095 to bring back 4.0 sync
  jobs/build/build-sync/Jenkinsfile
Labels: size/S

#1776 Run bug sweeps on a schedule
  jobs/build/sweep/Jenkinsfile
  jobs/build/sweep/README.md
  scheduled-jobs/build/bug-sweeps/4.1/Jenkinsfile
  scheduled-jobs/build/bug-sweeps/4.1/README.md
Labels: lgtm, size/M

#1795 Try to debug elliott path reference error
  jobs/build/sweep/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/S

#1796 Fix job refence path for bug sweeps
  scheduled-jobs/build/bug-sweeps/4.1/Jenkinsfile
Labels: size/XS

#1793 minor build tweaks
  jobs/build/ocp4/Jenkinsfile
  jobs/build/ocp4/build.groovy
  pipeline-scripts/buildlib.groovy
Labels: lgtm, size/M

#1781 Removing 4.0 refs
  jobs/build/build-sync/Jenkinsfile
  jobs/build/build-sync/README.md
  jobs/build/custom/Jenkinsfile
  jobs/build/incremental/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/commonlib.groovy
  scheduled-jobs/build/dev/Jenkinsfile
  scheduled-jobs/build/oc-mirror-quay-dev/Jenkinsfile
  scheduled-jobs/build/oc-mirror-quay-dev/README.md
  scheduled-jobs/build/reposync/Jenkinsfile
Labels: lgtm, size/L

#1797 build/build-sync: syncing into 4.0 repo indefinitely
  jobs/build/build-sync/Jenkinsfile
  jobs/build/build-sync/README.md
Labels: lgtm, size/XS

#1794 enhance custom job, retire incremental
  jobs/build/custom/Jenkinsfile
  jobs/build/incremental/Jenkinsfile
  jobs/build/ocp4/build.groovy
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/commonlib.groovy
Labels: lgtm, size/XL

#1798 scheduled-jobs/build/ose-master-full: force build for reals
  scheduled-jobs/build/ose-master-full/Jenkinsfile
  scheduled-jobs/build/ose-master/Jenkinsfile
Labels: lgtm, size/XS

#1799 build/custom: doozer expects version to start with v
  jobs/build/custom/Jenkinsfile
Labels: size/XS

#1800 Docker tag CAO image in MAO JJ
  sjb/config/test_cases/pull-ci-openshift-machine-api-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-machine-api-operator-master-e2e.xml
Labels: size/S

#1801 Build MAO and CAO images locally instead of pulling them from the payload
  sjb/config/test_cases/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-cluster-api-provider-kubemark-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-machine-api-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-api-provider-kubemark-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
  sjb/generated/pull-ci-openshift-machine-api-operator-master-e2e.xml
Labels: size/M

#1802 Adding new ocp sync job
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
Labels: lgtm, size/L

#1803 Build cluster-autoscaler image in machine-api tests
  sjb/config/test_cases/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-cluster-api-provider-kubemark-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.yml
  sjb/config/test_cases/pull-ci-openshift-machine-api-operator-master-e2e.yml
  sjb/generated/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-api-provider-kubemark-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
  sjb/generated/pull-ci-openshift-machine-api-operator-master-e2e.xml
Labels: size/L

#1805 Sync oc from `.nightly` instead of `.ci` stream
  jobs/build/oc_sync/Jenkinsfile
Labels: size/XS

#1806 oc-sync needs to write to 'latest' always, also respect `mock` parameter
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
Labels: size/XS

#1807 minimally need 4.1 option for bump core jenkins version rpm job
  jobs/devex/jenkins-bump-version/Jenkinsfile
Labels: size/XS

#1809 Fix oc_sync makes 'latest' symlinks and registry auth
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
Labels: lgtm, size/XS

#1808 Add app registry image search job
  jobs/build/appregistry/Jenkinsfile
  jobs/build/appregistry/appreg.py
Labels: lgtm, size/M

#1804 DRY, elliottest=>elliott
  jobs/build/sweep/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: lgtm, size/M

#1810 refresh-image:fix elliott old command to new
  jobs/build/refresh-images/Jenkinsfile
Labels: size/XS

#1812 build/appregistry: enhance, push operator metadata
  jobs/build/appregistry/Jenkinsfile
  jobs/build/appregistry/appreg.py
  pipeline-scripts/buildlib.groovy
Labels: lgtm, size/L
