Repository openshift-eng/aos-cd-jobs, pull requests merged in 2019-12, with the labels that each got.

#2067 [ART-1301] signing/sign-artifacts: Accept Digest parameter
  jobs/signing/sign-artifacts/Jenkinsfile
  jobs/signing/sign-artifacts/umb_producer.py
  pipeline-scripts/buildlib.groovy
Labels: lgtm, size/M

#2069 Add force checkout for target branches
  sjb/config/test_cases/test_branch_crio_e2e_features_rhel.yml
  sjb/config/test_cases/test_branch_crio_e2e_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_critest_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_e2e_features_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_e2e_rhel.yml
  sjb/config/test_cases/test_pull_request_crio_integration_rhel.yml
Labels: size/S

#2070 Remove redundant build param from signArtifacts
  pipeline-scripts/release.groovy
Labels: size/XS

#2072 cri-o: run generate.sh
  sjb/generated/test_branch_crio_e2e_features_fedora.xml
  sjb/generated/test_branch_crio_e2e_features_rhel.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_features_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_features_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
  sjb/generated/test_pull_request_crio_managed_net_ns_e2e_fedora.xml
Labels: size/M

#2068 [ART-1301] release: Use digest for signing job
  jobs/build/release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: lgtm

#2073 [ART-1345] backup: ensure destination directory exists
  jobs/maintenance/buildvm_backup/build.groovy
Labels: lgtm, size/XS

#2074 Fix copying of artifacts in s2i jobs
  sjb/config/common/test_cases/minimal.yml
  sjb/generated/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-api-provider-kubemark-master-e2e.xml
  sjb/generated/pull-ci-openshift-cluster-autoscaler-operator-master-e2e.xml
  sjb/generated/pull-ci-openshift-kubernetes-autoscaler-master-e2e.xml
  sjb/generated/pull-ci-openshift-machine-api-operator-master-e2e.xml
  sjb/generated/test_pull_request_s2i_master.xml
Labels: size/M

#2053 ART-1210: Auto run multiarch pre-release job for 4.3 and 4.4
  pipeline-scripts/commonlib.groovy
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: size/L

#2075 Fix calling sign-artifacts job
  pipeline-scripts/release.groovy
Labels: lgtm, size/XS

#2076 Enable multi-arch signing, and RHCOS signing
  jobs/signing/sign-artifacts/Jenkinsfile
  jobs/signing/sign-artifacts/umb_producer.py
Labels: size/L

#2077 release: allow concurrent execution
  jobs/build/release/Jenkinsfile
Labels: size/XS

#2078 release: target IS needs archSuffix too
  jobs/build/release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: size/S

#2081 build/custom: set default value of SIGNED to true
  jobs/build/custom/Jenkinsfile
Labels: lgtm, size/XS

#2083 Fix array index out of bounds exception in rhcos signing
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: lgtm, size/XS

#2017 Require action on failed RPM Diffs
  jobs/build/signed-compose/rpmdiff.py
Labels: lgtm, size/S

#2027 crio: e2e/integration tests with crun on Fedora
  sjb/config/test_cases/test_pull_request_crio_e2e_crun_fedora.yml
  sjb/config/test_cases/test_pull_request_crio_integration_crun_fedora.yml
  sjb/generate.sh
  sjb/generated/test_pull_request_crio_e2e_crun_fedora.xml
  sjb/generated/test_pull_request_crio_integration_crun_fedora.xml
Labels: size/XXL

#2082 Enable pre-release to get signed automatically
  jobs/build/pre-release/Jenkinsfile
  jobs/build/release/Jenkinsfile
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/S

#2034 [ART-722] Sweep builds and bugs after incremental and custom builds
  jobs/build/custom/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/signed-compose/Jenkinsfile
  jobs/build/signed-compose/build.groovy
  jobs/build/sweep/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: size/L

#2087 Work around sandbox
  pipeline-scripts/release.groovy
Labels: lgtm, size/S

#2088 Fix broken signing on pre-release job
  jobs/build/pre-release/Jenkinsfile
Labels: lgtm, size/XS

#2089 remove ose github token
  jobs/build/ocp3/Jenkinsfile
Labels: lgtm, size/M

#2090 fix broken ocp3 job: No such property: GITHUB_BASE
  jobs/build/ocp3/Jenkinsfile
Labels: size/XS

#2091 Rebase ose-base:rhscl.nodejs.6.rhel7 on rhscl/nodejs-6-rhel7:latest
  jobs/build/update-base-images/build.sh
Labels: size/XS
