Repository openshift-eng/aos-cd-jobs, pull requests merged in 2020-12, with the labels that each got.

#2411 ART-1812: Deprecate el8-rebuilds
  jobs/build/custom/Jenkinsfile
  jobs/build/el8-rebuilds/Jenkinsfile
  jobs/build/ocp4/build.groovy
Labels: do-not-merge/hold

#2438 ART-2134: add prepare-release job
  .devcontainer/README.md
  .devcontainer/brewkoji.conf
  .devcontainer/dev.Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yaml
  .devcontainer/doozer.settings.yaml
  .devcontainer/elliott.settings.yaml
  .devcontainer/krb5-redhat.conf
  config/artcd.toml
  jobs/build/prepare-release/Jenkinsfile
  pyartcd/config.example.toml
  pyartcd/prepare_release.py
  pyartcd/pyartcd/__init__.py
  pyartcd/pyartcd/jira.py
  pyartcd/pyartcd/mail.py
  pyartcd/pyartcd/pipelines/__init__.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/requirements-dev.txt
  pyartcd/requirements.txt
  pyartcd/setup.py
  pyartcd/tests/__init__.py
  pyartcd/tests/test_jira.py
  pyartcd/tests/test_mail.py
  pyartcd/tox.ini
Labels: lgtm, merge-post-promote

#2455 [ART-2146] add teketon tasks to suitable place
  tekton-pipelines/pipelines/pipeline-jenkins-bump-version.yaml
  tekton-pipelines/pipelines/pipeline-jenkins-plugins.yaml
  tekton-pipelines/tasks/task-bump-jenkins.yaml
  tekton-pipelines/tasks/task-jenkins-plugin-postmail.yaml
  tekton-pipelines/tasks/task-jenkins-plugin.yaml
  tekton-pipelines/tasks/task-send-email.yaml
Labels: merge-post-promote

#2476 plashet from-tags: Add option to inherit
  build-scripts/plashet.py
  pipeline-scripts/buildlib.groovy
Labels: lgtm
