Repository openshift-eng/aos-cd-jobs, pull requests merged in 2020-01, with the labels that each got.

#2066 adding ssh-agent([openshift-bot]) to jobs missing sshkey
  jobs/build/advisories/Jenkinsfile
  jobs/build/build-sync/Jenkinsfile
Labels: size/L

#2084 [ART-1351] Separate release image tag from name so name is not arch-specific
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/pre-release/Jenkinsfile
  jobs/build/release/Jenkinsfile
  jobs/signing/sign-artifacts/umb_producer.py
  pipeline-scripts/release.groovy
Labels: lgtm, size/L

#2093 Stop 'Error building custom OCP: #XYZ' going to aos-team-art@redhat.com
  jobs/build/custom/Jenkinsfile
Labels: lgtm, size/XS

#2094 Preserve shas for nightlies on pre-release
  pipeline-scripts/release.groovy
Labels: size/S

#2096 Preserve payload digest when pre-releasing nightly
  pipeline-scripts/release.groovy
Labels: size/S

#2098 Allow payload overwrites
  jobs/build/release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: size/S

#2039 Merge gen-payloads into one
  jobs/build/build-sync/build.groovy
Labels: size/M

#2095 Adding jobs for 4.5
  build-scripts/puddle-conf/atomic_openshift-4.5.conf
  build-scripts/puddle-conf/atomic_openshift-4.5.el8.conf
  build-scripts/puddle-conf/errata-puddle-4.5-signed.el7.conf
  build-scripts/puddle-conf/errata-puddle-4.5-signed.el8.conf
  jobs/build/ose4.5/Jenkinsfile
  pipeline-scripts/commonlib.groovy
  scheduled-jobs/build/bug-sweeps/4.5/Jenkinsfile
  scheduled-jobs/build/bug-sweeps/4.5/README.md
  scheduled-jobs/build/ocp-4.5-full/Jenkinsfile
  scheduled-jobs/build/ocp-4.5-full/README.md
  scheduled-jobs/build/ocp-4.5-incremental/Jenkinsfile
  scheduled-jobs/build/ocp-4.5-incremental/README.md
  scheduled-jobs/build/reposync/Jenkinsfile
Labels: lgtm, size/L

#2100 Send UMB messages for 4.4 nightlies
  jobs/build/send-umb-messages/Jenkinsfile
Labels: lgtm, size/XS

#2101 cri-o: force update on crun test
  sjb/generated/test_pull_request_crio_e2e_crun_fedora.xml
  sjb/generated/test_pull_request_crio_integration_crun_fedora.xml
Labels: size/XS

#2099 Scan all sources for changes to schedule incrementals
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/ocp4/build.groovy
  pipeline-scripts/buildlib.groovy
Labels: size/M

#2103 Adjust rhcos sync for multiarch builds
  jobs/build/rhcos_sync/Jenkinsfile
  jobs/build/rhcos_sync/build.groovy
Labels: size/M

#2104 [ART-1376] Fix sandbox error in scheduled-jobs/reposync
  scheduled-jobs/build/reposync/Jenkinsfile
Labels: lgtm, size/XS

#2105 [ART-1191] New build/helm_sync job
  jobs/build/helm_sync/Jenkinsfile
Labels: lgtm, size/M

#2102 [ART-1455] Reflect new `build/odo_sync` workflow
  jobs/build/odo_sync/Jenkinsfile
Labels: size/M

#2107 [ART-1455] Fix latest symlink update
  jobs/build/odo_sync/Jenkinsfile
Labels: size/XS

#2108 [ART-1191] Fix latest symlink update
  jobs/build/helm_sync/Jenkinsfile
Labels: size/XS

#2109 [ART-1455] Apply feedback from "helm_sync" review
  jobs/build/odo_sync/Jenkinsfile
Labels: lgtm, size/S

#2110 have advisory job re-enable automation
  jobs/build/advisories/Jenkinsfile
Labels: lgtm, size/L

#2079 Fix up RHCOS sync handling of arches
  build-scripts/use-mirror/rhcossync.sh
  jobs/build/rhcos_sync/Jenkinsfile
  jobs/build/rhcos_sync/build.groovy
Labels: size/M
