Repository openshift-eng/aos-cd-jobs, pull requests merged in 2020-04, with the labels that each got.

#2177 [ART-1712] Update kn sync-to-mirror script
  build-scripts/rcm-guest/publish-kn-binary.sh
Labels: lgtm

#2153 Open cincinnati PRs on release
  jobs/build/build-sync/build.groovy
  jobs/build/release/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/release.groovy
Labels: size/M

#2182 Make method available
  jobs/build/release/Jenkinsfile
Labels: lgtm

#2184 [ART-1066] add KEEP_ADVISORY_STATE option
  jobs/build/signed-compose/Jenkinsfile
  jobs/build/signed-compose/build.groovy
Labels: lgtm

#2185 tarball-sources: change project from RCM to EXD SP Cloud Distribution
  jobs/build/tarball-sources/Jenkinsfile
Labels: do-not-merge/hold, lgtm

#2190 add some failures check for tarball job
  jobs/build/tarball-sources/Jenkinsfile
Labels: lgtm

#2210 Wait for tagging
  jobs/build/signed-compose/ocp-tag-signed-errata-builds.py
Labels: lgtm

#2208 some small error message updates
  jobs/build/signed-compose/build.groovy
Labels: lgtm

#2204 Programmatic previous
  jobs/build/release/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: lgtm
