Repository openshift-eng/aos-cd-jobs, pull requests merged in 2020-03, with the labels that each got.

#2141 Add predictable links to release & pre-release client directories
  pipeline-scripts/release.groovy
Labels: size/S

#2140 [ART-1564] Escape $ from `sed` expression on advisories job
  jobs/build/advisories/Jenkinsfile
Labels: lgtm, size/XS

#2143 Ensure the metadata advisories are updated
  jobs/build/advisories/Jenkinsfile
Labels: size/XS

#2139 Allow links to be managed by Cincinnati data
  build-scripts/use-mirror/set-v4-client-latest.sh
  jobs/build/set_client_latest/Jenkinsfile
  pipeline-scripts/release.groovy
  scheduled-jobs/maintenance/set_cincinnati_links/Jenkinsfile
  scheduled-jobs/maintenance/set_cincinnati_links/README.md
Labels: lgtm, size/L

#2144 Enable reposync for ci-deps group
  jobs/build/reposync/Jenkinsfile
  scheduled-jobs/build/reposync/Jenkinsfile
Labels: size/M

#2123 Use build profile and support 3.11 signed build with ODCS
  jobs/build/custom/Jenkinsfile
  jobs/build/ocp3/Jenkinsfile
  jobs/build/ocp4/build.groovy
  jobs/build/openshift-online/scripts/merge-and-build-openshift-scripts.sh
  jobs/build/ose/scripts/merge-and-build.sh
Labels: size/S

#2147 ART-1652: 3.11 patch version shouldn't be zeroed out
  pipeline-scripts/buildlib.groovy
Labels: size/XS

#2146 ART-1650: Fix send-umb-message Invalid JSON String error
  jobs/build/send-umb-messages/Jenkinsfile
Labels: lgtm, size/M

#2150 Switch signing-job log archiver to use rclone
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/S

#2151 rclone log archiving was too noisy with -P
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: size/XS

#2149 Initial slacklib
  jobs/build/release/Jenkinsfile
  pipeline-scripts/slacklib.groovy
Labels: size/L

#1767 Add a link to credentials section on sjb/push* 403
  README.md
  sjb/push-update.sh
Labels: size/XS

#2138 Demo: Automatic publish to PyPI
  openshift-pipelines/README.md
  openshift-pipelines/images/art-jenkins-slave.Dockerfile
  openshift-pipelines/images/art-jenkins.Dockerfile
  openshift-pipelines/images/repos/rcm-tools-rhel-7-server.repo
  openshift-pipelines/images/repos/rhel-7.repo
  openshift-pipelines/infra/art-jenkins-bc.yaml
  openshift-pipelines/infra/art-jenkins-is.yaml
  openshift-pipelines/infra/art-jenkins-slave-bc.yaml
  openshift-pipelines/infra/art-jenkins-slave-is.yaml
  openshift-pipelines/jobs/doozer-poll-tags.yaml
  openshift-pipelines/jobs/doozer-release.yaml
  openshift-pipelines/jobs/elliott-poll-tags.yaml
  openshift-pipelines/jobs/elliott-release.yaml
  vars/artToolRelease.groovy
  vars/pollGitRefs.groovy
Labels: size/L

#2120 Track latest-x.y for rhcos dependencies
  build-scripts/use-mirror/rhcossync.sh
Labels: size/M

#2124 [ART-1353] Add script to identify buildroot of golang packages
  build-scripts/golang-built-rpms/golang-built-rpms
Labels: size/L

#2152 Make release controller acceptance retry with input
  jobs/build/release/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  pipeline-scripts/commonlib.groovy
  pipeline-scripts/release.groovy
  pipeline-scripts/slacklib.groovy
Labels: size/L

#2158 Fix slacklib redefinition in release job
  jobs/build/release/Jenkinsfile
Labels: lgtm

#2161 rpmdiff: Blurp to list
  jobs/build/signed-compose/rpmdiff.py
Labels: lgtm

#2166 Add ocp-cat
  hacks/ocp-cat/ocp-cat
Labels: lgtm

#2080 Switch Jenkins to use minimal profile
  sjb/config/test_cases/test_branch_jenkins_images.yml
  sjb/generated/push_jenkins_images.xml
  sjb/generated/test_branch_jenkins_images.xml
  sjb/generated/test_pull_request_jenkins_images.xml
Labels: lgtm, size/L

#2173 Enable ff-only synchronization of ose
  jobs/build/merge_ocp/Jenkinsfile
  jobs/build/merge_ocp/merge_ocp.sh
Labels: lgtm
