Repository openshift-eng/aos-cd-jobs, pull requests merged in 2020-02, with the labels that each got.

#2111 update-base-images: use most recent builds of ansible-runner and nodejs-6
  jobs/build/update-base-images/build.sh
Labels: lgtm, size/XS

#2113 crio: e2e/integration tests on Fedora with cgroup v2
  sjb/config/test_cases/test_pull_request_crio_e2e_crun_fedora_cgroupv2.yml
  sjb/config/test_cases/test_pull_request_crio_integration_crun_fedora_cgroupv2.yml
  sjb/generated/test_pull_request_crio_e2e_crun_fedora_cgroupv2.xml
  sjb/generated/test_pull_request_crio_integration_crun_fedora_cgroupv2.xml
Labels: size/XXL

#2118 rhcos_sync: use whitelist when publishing artifacts to mirror
  jobs/build/rhcos_sync/build.groovy
Labels: size/XS

#2116 Allow release job to run in any advisory state
  jobs/build/release/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: lgtm, size/S

#2115 ART-1475: allow ignoring lock in custom builds
  jobs/build/custom/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
Labels: size/M

#2119 Make arch dir follow build_id
  jobs/build/rhcos_sync/build.groovy
Labels: size/S

#2121 crio: use podman-docker on Fedora
  sjb/config/common/test_cases/crio.yml
  sjb/config/test_cases/test_pull_request_crio_integration_rhel.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_features_fedora.xml
  sjb/generated/test_branch_crio_e2e_features_rhel.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_crun_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_crun_fedora_cgroupv2.xml
  sjb/generated/test_pull_request_crio_e2e_features_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_features_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_crun_fedora.xml
  sjb/generated/test_pull_request_crio_integration_crun_fedora_cgroupv2.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
  sjb/generated/test_pull_request_crio_managed_net_ns_e2e_fedora.xml
  sjb/generated/test_pull_request_ovn_kubernetes_rhel.xml
Labels: size/L

#2122 crio: drop managed ns test
  sjb/config/common/test_cases/crio.yml
  sjb/config/test_cases/test_pull_request_crio_managed_net_ns_e2e_fedora.yml
  sjb/generated/ami_build_origin_int_fedora_crio.xml
  sjb/generated/ami_build_origin_int_rhel_crio.xml
  sjb/generated/test_branch_crio_e2e_features_fedora.xml
  sjb/generated/test_branch_crio_e2e_features_rhel.xml
  sjb/generated/test_branch_crio_e2e_fedora.xml
  sjb/generated/test_branch_crio_e2e_rhel.xml
  sjb/generated/test_branch_ovn_kubernetes_unit.xml
  sjb/generated/test_pull_request_crio_ami_fedora.xml
  sjb/generated/test_pull_request_crio_ami_rhel.xml
  sjb/generated/test_pull_request_crio_critest_fedora.xml
  sjb/generated/test_pull_request_crio_critest_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_crun_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_crun_fedora_cgroupv2.xml
  sjb/generated/test_pull_request_crio_e2e_features_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_features_rhel.xml
  sjb/generated/test_pull_request_crio_e2e_fedora.xml
  sjb/generated/test_pull_request_crio_e2e_rhel.xml
  sjb/generated/test_pull_request_crio_integration_crun_fedora.xml
  sjb/generated/test_pull_request_crio_integration_crun_fedora_cgroupv2.xml
  sjb/generated/test_pull_request_crio_integration_fedora.xml
  sjb/generated/test_pull_request_crio_integration_rhel.xml
  sjb/generated/test_pull_request_crio_managed_net_ns_e2e_fedora.xml
  sjb/generated/test_pull_request_ovn_kubernetes_rhel.xml
Labels: size/XL

#2125 Add non-versioned symlinks for ART-1349
  jobs/build/oc_sync/publish-clients-from-payload.sh
Labels: size/S

#2127 ART-1388 - Sign-Artifacts can hang forever
  jobs/signing/sign-artifacts/Jenkinsfile
Labels: lgtm, size/M

#2128 Zero out patch version for >= 4.4
  pipeline-scripts/buildlib.groovy
Labels: size/S

#2129 ART-1555: Fix appregistry job NoStaplerConstructorException
  jobs/build/appregistry/appregistry.groovy
Labels: lgtm, size/S

#2130 rhcos_sync: add QEMU artifact to whitelist
  jobs/build/rhcos_sync/build.groovy
Labels: lgtm, size/XS

#2131 [ART-1564] Fix group.yml update on advisories job
  jobs/build/advisories/Jenkinsfile
Labels: size/XS

#2132 Allow no patch specified
  build-scripts/rcm-guest/push-to-mirrors.sh
Labels: size/S

#2133 [ART-1564] Fix group.yml update on advisories job
  jobs/build/advisories/Jenkinsfile
Labels: lgtm, size/XS

#2136 Add 4.5 in places it should exist now post-branch-cut
  jobs/build/rhcos-puddle/Jenkinsfile
  jobs/build/send-umb-messages/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: size/XS

#2137 Verbosity & error reporting
  aos_cd_jobs/common.py
  aos_cd_jobs/updater.py
Labels: size/M

#2134 ART-1554: Makes send-umb-messages more verbose
  jobs/build/send-umb-messages/Jenkinsfile
Labels: lgtm, size/S
