Repository openshift-eng/aos-cd-jobs, pull requests merged in 2021-03, with the labels that each got.

#2532 Allow caller to include previous build in plashet
  build-scripts/plashet.py
Labels: merge-post-promote

#2542 Bug 1930378: operator-sdk_sync: Extract darwin artifact
  jobs/build/operator-sdk_sync/Jenkinsfile
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#2546 tkn-sync: Fix recursive copy
  jobs/build/tkn_sync/Jenkinsfile
Labels: lgtm

#2553 [ART-2532] Notify when sweep job is used to modify advisories
  jobs/build/sweep/Jenkinsfile
Labels: lgtm

#2552 [ART-2798] Update `build/crc_sync` job
  jobs/build/crc/Jenkinsfile
  jobs/build/crc/build.groovy
Labels: lgtm

#2550 [CONSOLE-2782] update-base-images: rebase ubi8.nodejs.14 to 14.16.0
  jobs/build/update-base-images/pullspecs.yaml
Labels: lgtm

#2555 [GRPA-3309] Copy AMIs to ROSA staging account
  jobs/build/rhcos_sync/Jenkinsfile
Labels: lgtm

#2561 olm_bundles - Validate advisories and group
  jobs/build/olm_bundle/Jenkinsfile
  jobs/build/olm_bundle/olm_bundles.groovy
Labels: lgtm
