Repository openshift-eng/aos-cd-jobs, pull requests merged in 2021-05, with the labels that each got.

#2611 Try all umb hosts
  jobs/signing/sign-artifacts/umb_producer.py
Labels: lgtm

#2573 Promote: Run `attach-cve-flaws`
  jobs/build/promote/Jenkinsfile
  pipeline-scripts/release.groovy
Labels: lgtm

#2615 [ART-1517] Ensure filename length does not exceed max
  pipeline-scripts/commonlib.groovy
Labels: merge-post-promote

#2614 [ART-2877] Create build/butane_sync job
  jobs/build/butane_sync/Jenkinsfile
  jobs/build/butane_sync/README.md
Labels: merge-post-promote

#2623 Supply assembly argument to all doozer invocations
  pipeline-scripts/buildlib.groovy
Labels: merge-post-promote

#2599 [ART-2752] add alert when all images build failed in ocp4
  jobs/build/ocp4/Jenkinsfile
  jobs/build/ocp4/build.groovy
Labels: lgtm, merge-post-promote

#2621 ART-2949 Sync rhcos for pre-releases in promote
  jobs/build/promote/Jenkinsfile
Labels: lgtm, merge-post-promote

#2626 ART-2937 Allow a manual build-sync run to trigger the release controller
  jobs/build/build-sync/Jenkinsfile
Labels: lgtm

#2620 aarch64 enablement
  build-scripts/use-mirror/set-v4-client-latest.sh
  jobs/build/build-sync/build.groovy
  jobs/build/coreos-installer_sync/extract.sh
  jobs/build/custom/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
  jobs/build/operator-sdk_sync/Jenkinsfile
  jobs/build/promote/Jenkinsfile
  pipeline-scripts/commonlib.groovy
  pipeline-scripts/release.groovy
  pyartcd/pyartcd/pipelines/prepare_release.py
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: merge-post-promote

#2629 Include all package NVREs in plashet.yml
  build-scripts/plashet.py
Labels: lgtm
