Repository openshift-eng/aos-cd-jobs, pull requests merged in 2023-08, with the labels that each got.

#3869 ART-7242 port github-activity-lock into pyartcd
  jobs/build/ocp4/Jenkinsfile
  jobs/build/ocp4_scan/Jenkinsfile
  jobs/build/rebuild/Jenkinsfile
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/tests/pipelines/test_check_bugs.py
  pyartcd/tests/pipelines/test_ocp4.py
Labels: lgtm, approved

#3871 Add redis env vars to jobs
  jobs/build/ocp4_scan/Jenkinsfile
  jobs/build/rebuild/Jenkinsfile
Labels: approved

#3872 Remove custom pipeline from pyartcd
  pyartcd/pyartcd/pipelines/custom.py
Labels: lgtm, approved

#3875 Fail counter only for stream
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: lgtm, approved

#3877 Get fresh stunnel before images:health
  scheduled-jobs/scanning/images-health/Jenkinsfile
Labels: lgtm, approved

#3874 Refactor pyartcd locks handling
  jobs/build/ocp4_scan/Jenkinsfile
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/pipelines/olm_bundle.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/tests/pipelines/test_ocp4.py
  pyartcd/tests/test_locks.py
Labels: lgtm, approved

#3880 Preserve links to caller job
  pyartcd/pyartcd/jenkins.py
Labels: lgtm, approved

#3883 build-microshift: disable concurrent builds
  jobs/build/build-microshift/Jenkinsfile
Labels: lgtm, approved

#3884 Prevent long lines getting wrapped in ruamel.yaml
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/review_cvp.py
Labels: lgtm, approved

#3885 Revert "build-microshift: disable concurrent builds"
  jobs/build/build-microshift/Jenkinsfile
Labels: lgtm, approved

#3891 Enable 4.15
  pipeline-scripts/commonlib.groovy
Labels: lgtm, approved

#3893 [ocp4] Have block_until_building=False for sync-for-ci
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: lgtm

#3894 Rename function to not conflict with param name
  pyartcd/pyartcd/jenkins.py
Labels: lgtm

#3895 Add jenkins.py unit tests
  pyartcd/pyartcd/jenkins.py
  pyartcd/tests/pipelines/test_ocp4.py
  pyartcd/tests/test_jenkins.py
Labels: lgtm, approved

#3896 [ART-3476] fix parameter error in signing job
  jobs/build/coreos-installer_sync/Jenkinsfile
Labels: lgtm, approved

#3899 [ART-7544] Add sast-scanning job
  jobs/build/scan-osh/Jenkinsfile
Labels: lgtm, approved

#3904 Refactor jenkins.py
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/run_details.py
  pyartcd/tests/pipelines/test_ocp4.py
Labels: lgtm, approved

#3903 [ART-7544] Kick off SAST scan for successful builds
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/tests/pipelines/test_ocp4.py
Labels: do-not-merge/hold

#3905 sast scan nvrs not found case fix
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: lgtm, approved

#3907 sha256sum.txt: Write correct archive name
  pyartcd/pyartcd/pipelines/promote.py
Labels: lgtm

#3906 Simplify starting of jenkins jobs
  pyartcd/pyartcd/jenkins.py
  pyartcd/tests/test_jenkins.py
Labels: lgtm, approved

#3910 Set fail counter to 0 only for 'stream' assembly
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: lgtm, approved

#3913 add [TEST] to title for test ocp4 build
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: lgtm, approved

#3911 [ART-7593] Trigger SAST scanning for rpms
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/record.py
Labels: lgtm, approved

#3914 Fix doozer data path in freeze automation check
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/util.py
  pyartcd/tests/test_util.py
Labels: lgtm, approved

#3886 ART-7624 Improve GitHub lock scope
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/pipelines/olm_bundle.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/tests/pipelines/test_ocp4.py
  pyartcd/tests/pipelines/test_rebuild.py
  pyartcd/tests/test_locks.py
Labels: lgtm, approved

#3915 ART-7622 Do not have ocp4 check for automation freeze state
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: lgtm, approved

#3918 Revert "ART-7624 Improve GitHub lock scope"
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/pipelines/olm_bundle.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/tests/pipelines/test_ocp4.py
  pyartcd/tests/pipelines/test_rebuild.py
  pyartcd/tests/test_locks.py
Labels: lgtm

#3923 build-sync: Add support for re-triggering aarch64 nightly
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: lgtm, approved

#3920 Allow multiple ironic packages versions in plashets
  pyartcd/pyartcd/plashets.py
Labels: lgtm, approved
