Repository openshift-eng/aos-cd-jobs, pull requests merged in 2023-10, with the labels that each got.

#3985 [gen-assembly] Remove limit arches warning
  jobs/build/gen-assembly/Jenkinsfile
Labels: lgtm, approved

#3997 fix compress log error in golang builder job
  jobs/build/golang-builder/Jenkinsfile
  jobs/build/golang-builder/find-and-compress-brew-logs.sh
Labels: lgtm, approved

#3994 Clear aws cache for mirror_path as well
  jobs/build/microshift_sync/Jenkinsfile
Labels: lgtm, approved

#4001 rebuild job: define builderEmail
  jobs/build/rebuild/Jenkinsfile
Labels: lgtm, approved

#4003 fix golang builder job
  jobs/build/golang-builder/Jenkinsfile
  jobs/build/golang-builder/find-and-compress-brew-logs.sh
Labels: lgtm, approved

#4010 Ensure current setuptools
  pipeline-scripts/buildlib.groovy
Labels: lgtm, approved

#4016 Display removed locks in build title
  jobs/maintenance/cleanup-locks/Jenkinsfile
Labels: lgtm

#4017 Set DEBUG level for artcd to see how rebase-into-priv behaves
  jobs/build/ocp4_scan/Jenkinsfile
Labels: lgtm

#4022 [ART-7387] [WIP] Build base image for Tekton release pipeline
  tekton-pipelines/images/artcd/Containerfile.base
Labels: lgtm, approved

#4029 ocp4: BUILD_RPMS and BUILD_IMAGES default to "none"
  jobs/build/ocp4/Jenkinsfile
Labels: lgtm, do-not-merge/hold, approved

#4030 use "only" as default
  jobs/build/ocp4/Jenkinsfile
Labels: lgtm, approved

#4033 Add commonlib.artToolsParam() to check-bugs
  jobs/build/check-bugs/Jenkinsfile
Labels: lgtm, approved
