Repository openshift-eng/aos-cd-jobs, pull requests merged in 2023-12, with the labels that each got.

#4060 enable 4.16
  pipeline-scripts/commonlib.groovy
Labels: lgtm, approved

#4061 Run nag-upstream against groups in random order
  scheduled-jobs/build/nag-upstream/Jenkinsfile
Labels: lgtm, approved

#4062 [ART-8305] Enable microshift build and publish rpms job for 4.16
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: lgtm, approved

#4063 [ART-8173] Bump early operator index to track 4.16
  scheduled-jobs/build/early-operator-index/Jenkinsfile.groovy
Labels: lgtm, approved

#4064 [scan-osh] Update scheduled job to once an hour
  scheduled-jobs/build/scan-osh/Jenkinsfile
Labels: approved

#4066 Disable logging into reg-aws
  pipeline-scripts/buildlib.groovy
Labels: lgtm

#4067 Throw an explicit error when ART_TOOLS_COMMIT is not a valid committish
  pipeline-scripts/buildlib.groovy
Labels: lgtm, approved

#4065 Track Jenkins job run on alignment PRs
  scheduled-jobs/build/sync-ci-images/Jenkinsfile
Labels: lgtm

#4068 add owner
  OWNERS
Labels: lgtm
