Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-02, with the labels that each got.

#4080 Stop SAST scanning
  scheduled-jobs/build/scan-osh/Jenkinsfile
Labels: lgtm, approved

#4081 ocp3: Skip logging into reg-aws
  pipeline-scripts/buildlib.groovy
Labels: lgtm, approved

#4082 gen-assembly: define valid values for LIMIT_ARCHES
  jobs/build/gen-assembly/Jenkinsfile
Labels: lgtm, approved

#4085 Chunk slack response in nag upstream
  jobs/build/nag-upstream/Jenkinsfile
  pipeline-scripts/slacklib.groovy
Labels: lgtm

#4078 Do reconciliation PRs for 4.12+
  scheduled-jobs/build/sync-ci-images/Jenkinsfile
Labels: lgtm

#4088 skip validate rhsa
  jobs/build/promote-assembly/Jenkinsfile
Labels: lgtm, approved, tide/merge-method-squash
