Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-01, with the labels that each got.

#4070 support extract file from el9
  jobs/build/coreos-installer_sync/extract.sh
Labels: lgtm, approved

#4044 [ART-8189] Create a update image for tekton-pipeline
  tekton-pipelines/images/artcd/Containerfile.base
  tekton-pipelines/images/artcd/Containerfile.latest
Labels: lgtm, approved

#4074 Add redis information for golang builder job
  jobs/build/golang-builder/Jenkinsfile
Labels: lgtm, approved

#4076 Add kubeconfig for aws backup
  jobs/build/promote-assembly/Jenkinsfile
Labels: lgtm

#4071 ART-8472: make in fight not required
  jobs/build/gen-assembly/Jenkinsfile
  jobs/build/prepare-release/Jenkinsfile
Labels: lgtm, do-not-merge/hold, approved, jira/valid-reference

#4079 Provide ocp4-scan with IGNORE_LOCKS (only permitted in dry-run mode)
  jobs/build/ocp4_scan/Jenkinsfile
Labels: lgtm
