Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-08, with the labels that each got.

#4212 Fix camel-k sync
  jobs/build/camel-k_sync/Jenkinsfile
Labels: lgtm, approved

#4213 Only report on jobs that were triggered by automation
  scheduled-jobs/scanning/art-notify/art-notify.py
Labels: lgtm

#4215 Add support for force rebuilding rpms
  jobs/build/rebuild-golang-rpms/Jenkinsfile
Labels: do-not-merge/hold

#4216 ROX-17632: Add OpenAPI spec synchronization to mirror.openshift.com/pub/rhacs
  scheduled-jobs/build/sync-rhacs/Jenkinsfile
Labels: lgtm, needs-ok-to-test, approved, jira/valid-reference

#4217 Use rsync to clean up artcd_working
  jobs/build/build-sync/Jenkinsfile
  jobs/build/check-bugs/Jenkinsfile
  jobs/build/drop_advisories/Jenkinsfile
  jobs/build/golang-builder/Jenkinsfile
  jobs/build/k_ocp4/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/ocp4_scan/Jenkinsfile
  jobs/build/olm_bundle/Jenkinsfile
  jobs/build/operator-sdk_sync/Jenkinsfile
  jobs/build/promote-assembly/Jenkinsfile
  jobs/build/rebuild-golang-rpms/Jenkinsfile
  jobs/build/rhcos/Jenkinsfile
  jobs/build/tarball-sources/Jenkinsfile
  jobs/maintenance/cleanup-locks/Jenkinsfile
  jobs/signing/sigstore-sign/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: lgtm, approved

#4219 Use rsync to clean up artcd_working
  jobs/build/build-sync/Jenkinsfile
  jobs/build/check-bugs/Jenkinsfile
  jobs/build/drop_advisories/Jenkinsfile
  jobs/build/golang-builder/Jenkinsfile
  jobs/build/k_ocp4/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/ocp4_scan/Jenkinsfile
  jobs/build/olm_bundle/Jenkinsfile
  jobs/build/operator-sdk_sync/Jenkinsfile
  jobs/build/promote-assembly/Jenkinsfile
  jobs/build/rebuild-golang-rpms/Jenkinsfile
  jobs/build/rhcos/Jenkinsfile
  jobs/build/tarball-sources/Jenkinsfile
  jobs/maintenance/cleanup-locks/Jenkinsfile
  jobs/signing/sigstore-sign/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: lgtm, approved

#4220 Do not fail on mkdir if /tmp/empty already exists
  pipeline-scripts/buildlib.groovy
Labels: lgtm

#4221 Remove k_ocp4 job
  jobs/build/k_ocp4/Jenkinsfile
  jobs/build/k_ocp4/README.md
Labels: lgtm, approved

#4223 #aos-art has been renamed into #forum-ocp-art
  jobs/scanning/images-health/Jenkinsfile
Labels: lgtm

#4224 aos-art has been renamed into #forum-ocp-art
  jobs/scanning/images-health/Jenkinsfile
Labels: lgtm, approved

#4211 ART-10048: Enable microshift nightly build and publish-rpms job
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: lgtm, approved, jira/valid-reference

#4210 ART-1004: bump early operator index to track 4.18
  scheduled-jobs/build/early-operator-index/Jenkinsfile.groovy
Labels: lgtm, approved, jira/valid-reference

#4225 ART-10297 Bump python to 3.11
  .devcontainer/dev.Dockerfile
  pipeline-scripts/buildlib.groovy
Labels: lgtm, do-not-merge/hold, approved

#4228 set client latest: Remove 4.11 specific code paths
  jobs/build/set_client_latest/S3-set-v4-client-latest.sh
Labels: lgtm, approved

#4231 ART-10428 add ovs 3.3
  jobs/build/publish-rpms/collect_deps.py
Labels: lgtm, approved

#4227 art-notify: Include job fail rate
  scheduled-jobs/scanning/art-notify/art-notify.py
Labels: do-not-merge/hold, approved

#4207 Update comments in sync-iib-images
  scheduled-jobs/build/sync-iib-images/Jenkinsfile.groovy
Labels: lgtm

#4232 set_cincinnati_links: Mark build as unstable instead of failure on child fail
  scheduled-jobs/maintenance/set_cincinnati_links/Jenkinsfile
Labels: lgtm, approved

#4229 Delete previous dev preview rather than current
  jobs/build/set_client_latest/S3-set-v4-client-latest.sh
Labels: lgtm, approved

#4234 ose-operator-registry move to rhel9
  scheduled-jobs/build/early-operator-index/Jenkinsfile.groovy
Labels: lgtm, approved

#4238 ocp4: never scan for changes, always build what's pinned
  jobs/build/ocp4/Jenkinsfile
Labels: lgtm, approved

#4239 images-health: Resume reporting to public channel
  scheduled-jobs/scanning/images-health/Jenkinsfile
Labels: lgtm, approved

#4226 ART-10562 Run scheduled ocp4 scan in pyartcd
  jobs/build/ocp4_scan/Jenkinsfile
  scheduled-jobs/build/ocp4_scan/Jenkinsfile
Labels: lgtm, approved

#4241 remote output reading logic
  jobs/build/promote-assembly/Jenkinsfile
Labels: lgtm, approved

#4242 ocp4-scan do not flake out on podman login
  jobs/build/ocp4_scan/Jenkinsfile
Labels: lgtm, approved
