Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-10, with the labels that each got.

#4260 ART-10881 Give olm-bundle access to BigQuery
  jobs/build/olm_bundle/Jenkinsfile
Labels: lgtm, approved

#4265 Provide build-microshift with BigQuery access
  jobs/build/build-microshift/Jenkinsfile
Labels: lgtm, approved

#4266 deprecate advance release
  jobs/build/gen-assembly/Jenkinsfile
Labels: lgtm, approved

#4261 improve assembly-urls
  hacks/triage/assembly-urls
  hacks/triage/install
Labels: lgtm, approved

#4258 update disk partition path
  jobs/maintenance/check-disk-usage-on-buildvm/Jenkinsfile
Labels: lgtm, approved

#4268 Fix golang-builder job
  jobs/build/golang-builder/Jenkinsfile
Labels: lgtm, approved

#4269 Make images:health public again
  scheduled-jobs/scanning/images-health/Jenkinsfile
Labels: lgtm, approved

#4271 limit logrotator to 15 days and clean workspace
  jobs/build/scan-for-kernel-bugs/Jenkinsfile
Labels: lgtm, approved

#4272 Accept fixed cves in golang jobs
  jobs/build/golang-builder/Jenkinsfile
  jobs/build/rebuild-golang-rpms/Jenkinsfile
Labels: tide/merge-method-squash

#4273 Dump versions at init
  pipeline-scripts/buildlib.groovy
Labels: tide/merge-method-squash

#4167 Fail if target directrory for butane sync exists on mirror
  jobs/build/butane_sync/Jenkinsfile
Labels: lgtm, approved, tide/merge-method-squash
