Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-03, with the labels that each got.

#4089 Skip plashets in ocp4 builds by default; automation will re-enable them
  jobs/build/ocp4/Jenkinsfile
Labels: lgtm, approved

#4092 Add ART_TOOLS_COMMIT param to olm-bundle
  jobs/build/olm_bundle/Jenkinsfile
Labels: lgtm, approved

#4094 changed parameter name ocp_build_data_url to data_path
  jobs/build/build-microshift/Jenkinsfile
Labels: lgtm, approved

#4096 Provide prepare-release with GITLAB_TOKEN env var
  jobs/build/prepare-release/Jenkinsfile
Labels: lgtm

#4097 Reduce notifications about tag_rpms failure
  jobs/build/tag-rpms/Jenkinsfile
Labels: lgtm, approved

#4101 Use 9.4 stream for 4.16
  jobs/build/rhcos_sync/rhcoslib.groovy
Labels: lgtm, approved

#4100 WIP：Fix ocp4_scan
  pipeline-scripts/buildlib.groovy
Labels: lgtm, do-not-merge/work-in-progress, approved

#4103 jenkins-workspace
  jobs/build/sync-for-ci/Jenkinsfile
  jobs/maintenance/buildvm_backup/build.groovy
  jobs/scanning/covscan-images/Jenkinsfile
  scheduled-jobs/build/sync-rhacs/Jenkinsfile
Labels: lgtm, approved

#4105 Remove snippet from art-attention
  scheduled-jobs/scanning/unresolved-art-threads/unresolved-thread-notification.py
Labels: lgtm, approved

#4106 fix http url with https
  README.md
  build-scripts/golang-built-rpms/golang-built-rpms
  hacks/coverity/convert.py
  hacks/new_minor/verify-distgit-branch
  jobs/build/aws-iso-marketplace-quay-image-builder/runner-image.repo
  jobs/build/butane_sync/Jenkinsfile
  jobs/build/butane_sync/README.md
  jobs/build/camel-k_sync/Jenkinsfile
  jobs/build/client_sync/Jenkinsfile
  jobs/build/coreos-installer_sync/Jenkinsfile
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/pre-release/Jenkinsfile
  jobs/build/promote-assembly/README.md
  jobs/build/publish-rpms/collect_deps.py
  jobs/build/rhcos_sync/Jenkinsfile
  jobs/build/set_client_latest/Jenkinsfile
  jobs/build/sync-for-ci/Jenkinsfile
  jobs/devex/jenkins-bump-version/Jenkinsfile
  jobs/devex/jenkins-plugins/Jenkinsfile
  jobs/signing/sign-artifacts/Jenkinsfile
  jobs/signing/sign-rhacs/Jenkinsfile
  openshift-pipelines/images/repos/rcm-tools-rhel-7-server.repo
  openshift-pipelines/images/repos/rhel-7.repo
  scheduled-jobs/build/rhacs-sigstore/Jenkinsfile
Labels: lgtm, approved

#4107 Update olm_bundle jenkins
  jobs/build/olm_bundle/Jenkinsfile
Labels: lgtm, approved

#4110 Fix accept-release
  jobs/build/accept-release/Jenkinsfile
Labels: lgtm, approved

#4111 Remove advisories job
  jobs/build/advisories/Jenkinsfile
  jobs/build/advisories/README.md
  jobs/build/advisories/advisories.groovy
Labels: lgtm, approved

#4112 fix accept release job
  jobs/build/accept-release/Jenkinsfile
Labels: lgtm

#4114 Fix golang builder job
  jobs/build/golang-builder/Jenkinsfile
Labels: lgtm, approved

#4115 Fix promote pipeline
  jobs/build/promote-assembly/Jenkinsfile
Labels: lgtm, approved

#4116 Fix cincinnati job
  jobs/build/cincinnati-prs/Jenkinsfile
Labels: lgtm, approved

#4117 golang-builder - Drop release suffix
  jobs/build/golang-builder/Jenkinsfile
Labels: lgtm, approved

#4109 ART-9183 Add rclone() wrapper function
  jobs/build/buildvm-maint/Jenkinsfile
  jobs/build/set_client_latest/Jenkinsfile
  jobs/build/set_client_latest/S3-set-v4-client-latest.sh
  jobs/signing/sign-artifacts/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: lgtm, approved

#4119 Get rid of declarative pipelines
  jobs/build/aws-iso-marketplace-quay-image-builder/Jenkinsfile
  jobs/build/butane_sync/Jenkinsfile
  jobs/build/camel-k_sync/Jenkinsfile
Labels: lgtm, approved

#4120 fix camel-k_sync
  jobs/build/camel-k_sync/Jenkinsfile
Labels: lgtm, approved

#4121 Fix set_client_latest
  jobs/build/set_client_latest/S3-set-v4-client-latest.sh
Labels: lgtm, approved

#4122 Update job description
  jobs/build/drop_advisories/Jenkinsfile
Labels: lgtm, approved
