Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-05, with the labels that each got.

#4142 consolidate invalidate aws cache commands
  jobs/build/microshift_sync/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: lgtm, approved

#4144 Revert "Stop SAST scanning"
  scheduled-jobs/build/scan-osh/Jenkinsfile
Labels: do-not-merge/hold

#4146 [ART-7995] promote-assembly: enable sigstore signing
  jobs/build/promote-assembly/Jenkinsfile
Labels: lgtm, approved

#4148 Revert "Bump early operator index to track 4.17"
  scheduled-jobs/build/early-operator-index/Jenkinsfile.groovy
Labels: lgtm, approved

#4152 ART-8353: files removed from gs bucket gets removed
  scheduled-jobs/build/sync-rhacs/Jenkinsfile
Labels: lgtm, approved, jira/valid-reference

#4151 Promote: Retry to parse json
  jobs/build/promote-assembly/Jenkinsfile
Labels: lgtm, approved

#4159 Enlarge timeout of ocp4_scan
  scheduled-jobs/build/ocp4_scan/Jenkinsfile
Labels: lgtm, approved

#4161 Prune running under scl
  jobs/build/accept-release/Jenkinsfile
  pipeline-scripts/buildlib.groovy
  scheduled-jobs/scanning/unresolved-art-threads/Jenkinsfile
Labels: lgtm, approved

#4160 update rpm sign method
  jobs/build/microshift_sync/Jenkinsfile
Labels: lgtm

#4165 ART-9308: [4.17 branch] update nightly index operator image
  scheduled-jobs/build/early-operator-index/Jenkinsfile.groovy
Labels: lgtm, approved, jira/valid-reference

#4166 ART-9310: Enable microshift nightly build and publish-rpms job for 4.17
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: lgtm, approved, jira/valid-reference

#4164 Add confirm flag to update-golang to enable local script runs
  jobs/build/golang-builder/Jenkinsfile
Labels: lgtm

#4168 ruby gems is no longer needed
  jobs/build/buildvm-maint/scripts/gen_snapshot.sh
Labels: lgtm, approved
