Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-12, with the labels that each got.

#4300 Start building OCP 4.19 in konflux
  scheduled-jobs/build/ocp4_scan_konflux/Jenkinsfile
Labels: lgtm, approved

#4304 [konflux] Add ignore locks option
  jobs/build/ocp4-konflux/Jenkinsfile
Labels: lgtm

#4305 ART-11024: update nightly index operator image
  scheduled-jobs/build/early-operator-index/Jenkinsfile.groovy
Labels: lgtm, jira/valid-reference

#4306 Consider failed jobs in the number of threads
  scheduled-jobs/scanning/art-notify/art-notify.py
Labels: lgtm, approved

#4307 Provide ocp4-konflux with Jenkins env vars
  jobs/build/ocp4-konflux/Jenkinsfile
Labels: lgtm, approved

#4309 [konflux] enable 4.17 scan
  scheduled-jobs/build/ocp4_scan_konflux/Jenkinsfile
Labels: lgtm, approved

#4310 deprecate 2015 IT cert
  tekton-pipelines/images/artcd/Containerfile
  tekton-pipelines/images/artcd/Containerfile.base
Labels: lgtm, approved

#4312 Enable 4.16 konflux scan
  scheduled-jobs/build/ocp4_scan_konflux/Jenkinsfile
Labels: lgtm, approved

#4313 [konflux] allow field to override konflux template url
  jobs/build/ocp4-konflux/Jenkinsfile
Labels: lgtm, approved

#4314 ART-11093 ADD ignore-non-x86-nightlies parameter
  jobs/build/gen-assembly/Jenkinsfile
Labels: lgtm, approved

#4324 enable all versions for konflux
  scheduled-jobs/build/ocp4_scan_konflux/Jenkinsfile
Labels: lgtm, approved
