Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-11, with the labels that each got.

#4278 Add flexibility to rhcos job
  jobs/build/rhcos/Jenkinsfile
Labels: lgtm, approved

#4280 [ART-11040] start automation for 4.19
  pipeline-scripts/commonlib.groovy
Labels: lgtm, do-not-merge/hold, approved

#4281 Fix s3 mirror sync dry-run
  jobs/build/microshift_sync/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: lgtm, approved

#4286 Add scheduled job for ocp4-scan-konflux
  scheduled-jobs/build/ocp4_scan_konflux/Jenkinsfile
Labels: lgtm, approved

#4288 ocp4-scan: ignore lock on dry run mode
  jobs/build/ocp4-scan-konflux/Jenkinsfile
  jobs/build/ocp4_scan/Jenkinsfile
Labels: lgtm, approved

#4285 ART-10946 - Upload rhcos-id.txt
  jobs/build/rhcos_sync/Jenkinsfile
  jobs/build/rhcos_sync/S3-rhcossync.sh
  jobs/build/rhcos_sync/rhcoslib.groovy
Labels: tide/merge-method-squash

#4295 ART-10946 rhcos_sync nightlies to dev dir
  jobs/build/rhcos_sync/Jenkinsfile
  jobs/build/rhcos_sync/S3-rhcossync.sh
  jobs/build/rhcos_sync/rhcoslib.groovy
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: do-not-merge/hold, approved, tide/merge-method-squash

#4294 ART-10882: use new rhcos itup cluster for all versions
  jobs/build/rhcos/Jenkinsfile
Labels: lgtm, approved, jira/valid-reference

#4292 Adjust poll-payload actions
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: lgtm, approved

#4289 Deprecate sigstore-sign pipeline
  jobs/signing/sigstore-sign/Jenkinsfile
Labels: lgtm, approved

#4299 ART-11441: [konflux] Trigger builds in new cluster
  jobs/build/build-microshift-bootc/Jenkinsfile
  jobs/build/ocp4-konflux/Jenkinsfile
Labels: lgtm, approved, jira/valid-reference

#4298 Enable telemetry sink for build-sync
  jobs/build/build-sync/Jenkinsfile
  pipeline-scripts/commonlib.groovy
Labels: lgtm

#4301 golang-builder: Add option to force image build
  jobs/build/golang-builder/Jenkinsfile
Labels: lgtm, approved
