Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-09, with the labels that each got.

#4243 ART-10668 Replace pip with uv when setting up art-tools venv
  pipeline-scripts/buildlib.groovy
Labels: lgtm, approved

#4244 Give ocp4 access to konflux DB
  jobs/build/ocp4/Jenkinsfile
Labels: lgtm, approved

#4245 Fix init step in groovy
  jobs/build/promote-assembly/Jenkinsfile
  jobs/build/rhcos/Jenkinsfile
Labels: lgtm, approved

#4246 add option to skip get-nightlies
  jobs/build/gen-assembly/Jenkinsfile
Labels: lgtm, approved

#4248 Also print out artcommon version
  pipeline-scripts/buildlib.groovy
Labels: lgtm, approved

#4222 Add ocp4-konflux job to build images with Konflux
  jobs/build/ocp4-konflux/Jenkinsfile
Labels: lgtm, approved

#4247 update gen-assembly NIGHTLIES param help
  jobs/build/gen-assembly/Jenkinsfile
Labels: lgtm, approved

#4249 Use GCP service account for BigQuery connections
  jobs/build/ocp4/Jenkinsfile
Labels: lgtm, approved

#4250 Move GCP project, dataset and table ID to art-tools constants
  jobs/build/ocp4/Jenkinsfile
Labels: lgtm, approved

#4251 Move redis port and hostname to art-tools
  jobs/build/build-sync/Jenkinsfile
  jobs/build/golang-builder/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/ocp4_scan/Jenkinsfile
  jobs/build/olm_bundle/Jenkinsfile
  jobs/build/promote-assembly/Jenkinsfile
  jobs/build/rebuild/Jenkinsfile
  jobs/build/scan-osh/Jenkinsfile
  jobs/build/tag-rpms/Jenkinsfile
  jobs/maintenance/cleanup-locks/Jenkinsfile
  scheduled-jobs/build/ocp4_scan/Jenkinsfile
Labels: lgtm, approved

#4254 Add REKOR_URL to the environment to provide cosign tlog
  jobs/signing/sigstore-sign/Jenkinsfile
Labels: lgtm, approved

#4253 Fix rhcos sync
  jobs/build/rhcos_sync/S3-rhcossync.sh
Labels: tide/merge-method-squash

#4259 ocp4-konflux: Add SKIP_REBASE parameter
  jobs/build/ocp4-konflux/Jenkinsfile
Labels: lgtm
