Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-07, with the labels that each got.

#4189 Remove the ocp-artifacts label from the built-in Jenkins node
  jobs/build/build-microshift/Jenkinsfile
  jobs/build/scan-osh/Jenkinsfile
Labels: lgtm, approved

#4190 use build-in label for build-sync and olm_bundle
  jobs/build/build-sync/Jenkinsfile
  jobs/build/olm_bundle/Jenkinsfile
Labels: lgtm, approved

#4191 deprecate covscan job
  jobs/scanning/covscan-images/Jenkinsfile
Labels: lgtm, approved

#4192 Periodically build plashets for test assembly
  scheduled-jobs/build/build-plashets-for-test-assembly/Jenkinsfile
Labels: lgtm, approved

#4193 Deprecate buildvm-maint job
  jobs/build/buildvm-maint/Jenkinsfile
  jobs/build/buildvm-maint/README.md
  jobs/build/buildvm-maint/scripts/gen_snapshot.sh
  jobs/build/buildvm-maint/scripts/maintenance.sh
  jobs/build/buildvm-maint/scripts/snapshot.sh
  scheduled-jobs/build/buildvm-maint/Jenkinsfile
  scheduled-jobs/build/buildvm-maint/README.md
Labels: lgtm, approved

#4188 Update art-unresolved-threads job
  scheduled-jobs/scanning/__init__.py
  scheduled-jobs/scanning/art-notify/Jenkinsfile
  scheduled-jobs/scanning/art-notify/README.MD
  scheduled-jobs/scanning/art-notify/art-notify.py
  scheduled-jobs/scanning/art-notify/check_expired_certificates.py
  scheduled-jobs/scanning/art-notify/res/art-attention.gif
  scheduled-jobs/scanning/art-notify/res/art-done.png
  scheduled-jobs/scanning/art-notify/res/bot-manifest.yaml
  scheduled-jobs/scanning/art-notify/res/insight.png
  scheduled-jobs/scanning/art-notify/res/insight.png-attribution.html
Labels: lgtm, approved, tide/merge-method-squash

#4179 Update versions in triage scripts
  hacks/triage/install
Labels: lgtm, approved

#4195 Link failed builds in job failure message
  scheduled-jobs/scanning/art-notify/art-notify.py
Labels: tide/merge-method-squash

#4197 Fix job name quoting in url
  scheduled-jobs/scanning/art-notify/art-notify.py
Labels: lgtm, approved

#4196 ART-9182 Trigger rhcos_sync for ECs and GA
  jobs/build/promote-assembly/Jenkinsfile
  jobs/build/rhcos_sync/Jenkinsfile
Labels: lgtm, approved

#4198 Capture scheduled-jobs build failures as well
  scheduled-jobs/scanning/art-notify/art-notify.py
Labels: lgtm, approved

#4199 [ART-10184] sync to cloudflare
  pipeline-scripts/commonlib.groovy
  pipeline-scripts/release.groovy
Labels: lgtm, do-not-merge/hold, approved

#4202 Deprecate jenkins plugins and rpm jobs
  hacks/iptables/buildvm-scripts/known-networks.txt
  hacks/update-jenkins-plugins/README.MD
  hacks/update-jenkins-plugins/backup/individual_repos/README.MD
  hacks/update-jenkins-plugins/backup/individual_repos/collect-jenkins-plugins.sh
  hacks/update-jenkins-plugins/backup/individual_repos/plugins.txt
  hacks/update-jenkins-plugins/backup/individual_repos/update-dist-git-plugins.sh
  hacks/update-jenkins-plugins/collect-jenkins-plugins.sh
  hacks/update-jenkins-plugins/plugins.txt
  hacks/update-jenkins-plugins/update-dist-git.sh
  jobs/devex/jenkins-bump-version/Jenkinsfile
  jobs/devex/jenkins-bump-version/README.md
  jobs/devex/jenkins-bump-version/bump-jenkins.sh
  jobs/devex/jenkins-bump-version/rpm-bump-version.sh
  jobs/devex/jenkins-plugins/Jenkinsfile
  jobs/devex/jenkins-plugins/README.md
  tekton-pipelines/tasks/task-bump-jenkins.yaml
  tekton-pipelines/tasks/task-jenkins-plugin-postmail.yaml
  tekton-pipelines/tasks/task-jenkins-plugin.yaml
Labels: lgtm, approved, tide/merge-method-squash

#4204 Sync to cloudflare
  jobs/build/k_ocp4/Jenkinsfile
  jobs/build/oc_sync/Jenkinsfile
  jobs/build/oc_sync/publish-clients-from-payload.sh
  jobs/build/ocp3/Jenkinsfile
  jobs/build/ocp3/s3-publish-oc-binary.sh
  jobs/build/ocp4/Jenkinsfile
  jobs/build/operator-sdk_sync/Jenkinsfile
  jobs/build/promote-assembly/Jenkinsfile
  jobs/build/publish-rpms/Jenkinsfile
  jobs/build/rhcos_sync/S3-rhcossync.sh
  jobs/build/rhcos_sync/rhcoslib.groovy
  jobs/build/set_client_latest/Jenkinsfile
  jobs/build/set_client_latest/S3-set-v4-client-latest.sh
  jobs/signing/sign-artifacts/Jenkinsfile
  jobs/signing/sign-rhacs/Jenkinsfile
  pipeline-scripts/commonlib.groovy
  pipeline-scripts/release.groovy
  scheduled-jobs/build/sync-rhacs/Jenkinsfile
Labels: lgtm, do-not-merge/hold

#4208 ART-10043: start automation for 4.18
  pipeline-scripts/commonlib.groovy
Labels: lgtm, approved, jira/valid-reference

#4118 Remove sending email code from Jenkinsfile
  config/artcd.toml
  jobs/build/promote-assembly/Jenkinsfile
Labels: lgtm
