Repository openshift-eng/aos-cd-jobs, pull requests merged in 2024-06, with the labels that each got.

#4171 Notify when no unresolved threads are found
  scheduled-jobs/scanning/unresolved-art-threads/Jenkinsfile
  scheduled-jobs/scanning/unresolved-art-threads/unresolved-thread-notification.py
Labels: lgtm, approved

#4172 Disable content_set check in ocp4/rebuild jobs
  jobs/build/k_ocp4/Jenkinsfile
  jobs/build/ocp4/Jenkinsfile
  jobs/build/rebuild/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: lgtm, approved

#4173 Get a failed jobs notification periodically
  scheduled-jobs/scanning/unresolved-art-threads/Jenkinsfile
  scheduled-jobs/scanning/unresolved-art-threads/unresolved-thread-notification.py
Labels: lgtm, approved, tide/merge-method-squash

#4174 publish_azure_marketplace: check if blob exists before uploading it
  jobs/build/publish_azure_marketplace/Jenkinsfile
Labels: lgtm, approved

#4176 tag-rhcos-snapshot: region needed for boto3 client
  hacks/prune-rhcos-snapshots/tag-rhcos-snapshots.py
Labels: needs-ok-to-test

#4177 Revert "Remove snippet from art-attention"
  scheduled-jobs/scanning/unresolved-art-threads/unresolved-thread-notification.py
Labels: lgtm, approved

#4178 Tweak publish rpms
  jobs/build/publish-rpms/Jenkinsfile
  jobs/build/publish-rpms/collect_deps.py
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: lgtm, approved

#4180 [poll-payload] different working dir to handle concurrent runs
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: lgtm, approved

#4183 Prune publish-rpms targets
  scheduled-jobs/build/poll-payload/Jenkinsfile
Labels: lgtm, approved

#4184 [ART-9930] fix publish rpms job for aarch64 builds
  jobs/build/publish-rpms/collect_deps.py
Labels: lgtm, approved

#4175 ART-6673 Deprecate sending umb event to QE
  jobs/build/promote-assembly/Jenkinsfile
Labels: lgtm, approved

#4185 ART-9938: prevent full disk problems on buildvm
  jobs/build/build-sync/Jenkinsfile
  jobs/build/prepare-release/Jenkinsfile
  jobs/build/tag-rpms/Jenkinsfile
Labels: lgtm, approved, jira/valid-reference

#4186 sigstore: Make all default
  jobs/signing/sigstore-sign/Jenkinsfile
Labels: lgtm, approved
