Repository openshift-eng/aos-cd-jobs, pull requests merged in 2025-03, with the labels that each got.

#4364 fix boolparam issue
  jobs/build/butane_sync/Jenkinsfile
Labels: lgtm, approved

#4373 Include maintenance project jobs in failed job notification
  scheduled-jobs/scanning/art-notify/art-notify.py
Labels: lgtm, approved

#4374 Run functional-tests in a job
  jobs/build/functional-tests/Jenkinsfile
  pipeline-scripts/buildlib.groovy
Labels: lgtm, approved, tide/merge-method-squash

#4360 Add build-fbc job to build file-based catalogs on Konflux
  jobs/build/build-fbc/Jenkinsfile
Labels: lgtm, approved

#4361 Add fbc-import-from-index job
  jobs/build/fbc-import-from-index/Jenkinsfile
Labels: lgtm, approved

#4378 Use registry.redhat.io pull secret
  jobs/build/build-fbc/Jenkinsfile
  jobs/build/fbc-import-from-index/Jenkinsfile
Labels: lgtm, approved

#4379 Prioritize konflux scans based on the OCP version
  scheduled-jobs/build/ocp4_scan_konflux/Jenkinsfile.hp
  scheduled-jobs/build/ocp4_scan_konflux/Jenkinsfile.lp
Labels: lgtm, approved

#4381 Disable telemetry
  pipeline-scripts/commonlib.groovy
Labels: lgtm, approved

#4380 fix: check for file type before zstd
  extract.sh
Labels: lgtm, approved

#4382 ART-12297: new ocp version
  pipeline-scripts/commonlib.groovy
Labels: lgtm, approved, jira/valid-reference

#4384 Update rhcos release browser url
  jobs/build/rhcos_sync/rhcoslib.groovy
Labels: lgtm, approved

#4385 build-fbc: Use registry config file for pull secret
  jobs/build/build-fbc/Jenkinsfile
Labels: lgtm, approved

#4383 [ART-12287] Update rhcos job
  jobs/build/rhcos/Jenkinsfile
Labels: lgtm, approved
