Repository openshift-eng/aos-cd-jobs, pull requests merged in 2025-01, with the labels that each got.

#4325 Mark jobs as UNSTABLE upon build failures; archive artifacts
  jobs/build/ocp4-konflux/Jenkinsfile
Labels: lgtm, approved

#4326 ART-11793 add openshift-kubelet to beta repo
  jobs/build/publish-rpms/collect_deps.py
Labels: lgtm, approved

#4327 Add Rayford to OWNERS
  OWNERS
Labels: lgtm, approved

#4329 rhcos_sync - Don't wait on azure job to finish
  jobs/build/rhcos_sync/Jenkinsfile
Labels: lgtm

#4336 Add olm_bundle_konflux job
  jobs/build/ocp4-konflux/Jenkinsfile
  jobs/build/olm_bundle_konflux/Jenkinsfile
Labels: lgtm, approved

#4337 [ART-11852] add create microshift flag for gen assembly job
  jobs/build/gen-assembly/Jenkinsfile
Labels: lgtm, approved

#4338 ocp4-konflux: Build OLM bundles by default
  jobs/build/ocp4-konflux/Jenkinsfile
Labels: lgtm

#4340 Filter out unviable build-sync runs
  scheduled-jobs/scanning/art-notify/art-notify.py
Labels: lgtm, approved, tide/merge-method-squash

#4341 build-sync clean comma-separated list exclude_arches
  jobs/build/build-sync/Jenkinsfile
Labels: lgtm, approved

#4339 ART-11901: Ensure OCP container tools are available in beta repo
  jobs/build/publish-rpms/collect_deps.py
Labels: lgtm, approved, jira/valid-reference

#4342 add lgarciaaco to OWNERS
  OWNERS
Labels: lgtm, approved

#4343 OCPBUGS-48831: Fix bash glob exclusion in S3-rhcossync.sh
  jobs/build/rhcos_sync/S3-rhcossync.sh
Labels: lgtm, approved, jira/invalid-bug, jira/severity-moderate, jira/valid-reference

#4344 changed construction of URL for syncing artifacts
  jobs/build/rhcos_sync/rhcoslib.groovy
Labels: lgtm, approved
