Repository openshift-eng/aos-cd-jobs, pull requests merged in 2025-06, with the labels that each got.

#4407 add build-system to build-sync params
  jobs/build/build-sync/Jenkinsfile
Labels: lgtm

#4405 Add build-plashets job
  jobs/build/build-plashets/Jenkinsfile
Labels: lgtm, do-not-merge/hold, approved

#4409 add jenkins service account to bootc job
  jobs/build/build-microshift-bootc/Jenkinsfile
Labels: lgtm, approved

#4412 Fix ocp-scan-konflux hp
  scheduled-jobs/build/ocp4_scan_konflux/Jenkinsfile.hp
Labels: lgtm, approved

#4417 [rhcos-sync] Do not pip install awscli
  jobs/build/rhcos_sync/rhcoslib.groovy
Labels: lgtm, approved, tide/merge-method-squash

#4420 add SKIP_PREPARE_ADVISORY and DATE in build-microshift job
  jobs/build/build-microshift/Jenkinsfile
Labels: lgtm

#4427 feat: add telemetry configuration to Jenkins pipeline
  Jenkinsfile
Labels: lgtm, approved
